<div class="row">
    <script type='text/javascript' src='https://www.kymenlaaksonyt.fi/widget-loader/66ced9efe83d471552a0da7d'>
    </script><div id='EVENTZWIDGET-66ced9efe83d471552a0da7d' class='EVENTZWIDGET'></div>
    
    <?php
    $script = <<<JS
    const searchTerms = new Map([
        ['Valitse aihe',''],
        ['Digiopastukset','Digiopastus'],
        ['Elokuvat','Elokuvvtatt'],
        ['Kirjailijavieraat','kirjailija'],
        ['Kirjallisuus','Kirjallisuus'],
        ['Lukukoirat','lukukoiratt'],
        ['Lukupiirit','lukupiiiri'],
        ['Musiikki','Musiikki'],
        ['Näyttelyt','Näyttelyt'],
        ['Pelaaminen','Pelaaminen'],
        ['Satutuokiot','satutuokio']
    ]);
                
    waitForWidgets(searchTerms);
    JS;
    echo $this->assetManager()->outputInlineScriptString($script);
    ?>
</div>
<div class="row">
    <div class="col-md-12">
        <?= $this->feed('e-aineistojen_nosto'); ?>
    </div>
</div>
<br>
<br>
