<div class="row">
    <div class="englishInfobox">
        <div class="col-md-10">
            <div class="no-shadow-white-box">
                <h2>About Kyyti.finna.fi</h2>
                <p>Welcome to the the website of the libraries in the Kymenlaakso area and Iitti.
                The Kyyti network comprises the libraries of Hamina, Iitti, Kotka, Kouvola, Miehikkälä, Pyhtää and Virolahti.</p>
            </div>
        </div>
        <div class="col-md-10">
            <div class="white-box">
                <h2>Many benefits from joint library services</h2>
                <ul class="list-bullets-english-home">
                    <li>The web library gives you access to the Kyyti Libraries’ joint collections</li>
                    <li>Reserved materials are transported to the library of your choice</li>
                    <li>You can return your loans to any Kyyti library</li>
                    <li>The same library card is valid at all Kyyti libraries</li>
                </ul>
            </div>
        </div>
    </div>
</div>