<!-- START of: finna - content/accessibility-statement_fi.phtml -->
<?php $this->headTitle($this->translate('accessibility_statement'));  ?>
<div class="page-content">
    <h1>Finna.fi-sivuston saavutettavuusseloste</h1>
    <p>Kyyti-kirjastot pyrkii takaamaan verkkosivustonsa saavutettavuuden Lain digitaalisten palvelujen tarjoamisesta 306/2019 mukaisesti.</p>
    <p>Tämä saavutettavuusseloste koskee kyyti.finna.fi-sivustoa.</p>
    
    <h2>Saavutettavuuden tila</h2>
    <p>Kyyti.finna.fi täyttää Verkkosisällön saavutettavuusohjeiden (WCAG) 2.1 -tason AA-vaatimukset osittain.
    Vaatimusten noudattamatta jättämiset ja vaatimuksiin sovellettavat poikkeukset mainitaan jäljempänä.</p>
    
    <h2>Ei-saavutettava sisältö</h2>
    
    <p>Jäljempänä mainittu sisältö ei ole saavutettavissa seuraavista syistä:</p>
    <p>Lain digitaalisten palvelujen tarjoamisesta 306/2019 noudattamatta jättäminen</p>
    
    <h3>Yleistä</h3>
    
    <ul class="list-bullets">
        <li>
            <b>Kontrastit:</b> Palvelussa on joitakin riittämättömiä tekstikontrasteja, lähinnä syötekenttien paikanvaraajateksteissä (placeholder) (WCAG 1.4.3). Myös joidenkin käyttöliittymäkomponenttien, kuten syötekenttien ja erilaisten ikoneiden erottuminen taustasta voi olla hankalaa riittämättömien kontrastien takia (WCAG 1.4.11).
        </li>
        <li>
            <b>Tekstin suurentaminen:</b> Pelkän tekstin suurentaminen 200 % aiheuttaa esimerkiksi hakukentän pudotusvalikon sisällön valumisen pääkuvan päälle, jolloin teksti voivat olla vaikeasti luettavissa.
            Samoin erityisesti englannin- ja ruotsinkielisillä puolilla myös etusivulla joidenkin komponenttien tekstit rivittyvät niin, että niiden lukeminen on hankalaa. Joidenkin ikonien kohdalla ikoni valuu pois sille varatulta taustalta, jolloin ikonin ymmärtäminen voi olla vaikeaa taustan riittämättömän kontrastin takia. (WCAG 1.4.4)
        </li>
        <li>
            <b>Skaalautuvuus:</b> Kirjautumispuolella jotkin painikkeet menevät päällekkäin 320 x 256 kokoisella mobiilinäytöllä, jolloin niitä voi olla hankala hahmottaa ja käyttää (WCAG 1.4.10).
        </li>
        <li>
            <b>Otsikot:</b> Sivustolla on puutteita otsikoinnissa. Joidenkin otsikkotasojen yli on hypätty, jotkin otsikot puuttuvat kokonaan ja jotkin otsikot on esitetty vain lihavoiduin tekstein (WCAG 1.3.1).
        </li>
        <li>
            <b>Taulukot:</b> Taulukoissa on käytetty vaihtelevasti taulukko-otsikointia, joissain taulukoista ne esimerkiksi puuttuvat kokonaan. Taulukoista löytyy myös paikoin paljon tyhjiä sarakkeita. Joitain taulukoita (esimerkiksi teosten saatavuustietoja) ei ole toteutettu html-taulukoina, jolloin niiden hahmottaminen ja käyttö voi olla haastavaa ruudunlukijalla. (WCAG 1.3.1)
        </li>
        <li>
            <b>Ohjelmallisen ja visuaalisen toteutuksen vastaavuus:</b> Joitain elementtejä, kuten esimerkiksi hakutulosten voimassa olevia rajauksia tai mobiilivalikosta aukeavaa alavalikkoa ei ole ryhmitelty ohjelmallisesti, jolloin niiden ymmärtäminen ruudunlukijaa käyttäen voi olla vaikeaa. Kirjautumispuolella olevasta sivutuselementistä puuttuu myös ruudunlukijalle luettava tieto siitä, millä sivulla käyttäjä on.  Joissain elementeissä, esimerkiksi tarkennetun haun Aineistotyyppi-puunäkymässä, on ruudunlukijalla hankala hahmottaa eri elementtien välistä hierarkiaa, sillä niitä ei ole merkitty ohjelmallisesti. (WCAG 1.3.1)
        </li>
        <li>
            <b>Sivurakenteet:</b>Kaikkia sivunavigaatioita ja sivutuselementtejä ei ole merkitty ohjelmallisesti (WCAG 1.3.1).
        </li>
        <li>
            <b>Kohdistusjärjestys:</b> Esimerkiksi hakutulossivulla ja yksittäisen teoksen sivulla kohdistusjärjestys poikkeaa oletetusta kohdistusjärjestyksestä (WCAG 2.4.3).
        </li>
        <li>
            <b>Tekstivastineet:</b> Sivustolla on joitain visuaalisesti informatiivisia ikoneita, joilta puuttuu kuitenkin tekstivastine ruudunlukijan käyttäjälle. Samaten esimerkiksi kaikkia kehyksiä ei ole nimetty, jotta käyttäjä tietäisi, mitä kehyksen sisällä on. (WCAG 1.1.1)
        </li>
    </ul>
    
    <h3>Linkit ja navigointi</h3>
    
    <ul class="list-bullets">
        <li>
            <b>Uuteen välilehteen avautuvat linkit: </b>Uuteen välilehteen ja/tai palveluun avautumisesta ei aina kerrota, sillä kaikissa linkeissä ja painikkeissa ei ole käytetty kuvaketta eikä tietoa löydy aina myöskään ohjelmallisesti ruudunlukijan käyttäjille. (WCAG 2.4.4, 2.5.3)
        </li>
        <li>
            <b>Näppäimistönavigointi: </b> Näppäimistöllä ei pääse kaikkiin sivuston elementteihin. Esimerkiksi haitarielementtejä ei aina saa avattua tai suljettua. Jotkin elementit, kuten hampurilaisvalikko, taas eivät saa näppäimistökohdistusta pienellä näyttökoolla. (WCAG 2.1.1)
        </li>
        <li>
            <b>Näkyvä kohdistus:</b> Karusellielementtien nuolipainikkeet eivät saa näkyvää näppäimistökohdistusta (WCAG 2.4.7).
        </li>
        <li>
            <b>Välilehdet:</b> Välilehtiä ei aina ole toteutettu ohjelmallisesti oikein, jotta ruudunlukija välittäisi käyttäjälle tiedon siitä, millainen elementti on kyseessä. Valittua välilehteä ei ole aina myöskään korostettu ohjelmallisesti. (WCAG 1.3.1 & 4.1.2)
        </li>
        <li>
            <b>Hyppylinkki:</b>Joka sivulla toistuva, päänavigaation ohi hyppäävä hyppylinkki ei toimi kaikilla ruudunlukijoilla. Esimerkiksi Siirry sisältöön -linkki säilyttää kohdistuksen hyppylinkissä eikä siirrä sitä sisältöön. (WCAG 2.4.1)
        </li>
        <li>
            <b>Linkkien tarkoitus:</b> Kaikkien linkkien tarkoitus ei selviä linkkitekstistä (WCAG 2.4.4).
        </li>
    </ul>
    
    <h3>Lomakkeet</h3>
    
    <ul class="list-bullets">
        <li>
            <b>Ohjeet:</b> Joidenkin lomakekenttien täyttöohjeet on kerrottu vasta itse kentän tai lomakkeen lähettävän painikkeen jälkeen (WCAG 1.3.1 & 3.3.2).
        </li>
        <li>
            <b>Automaattinen täydennys:</b> Kaikilla lomakekentillä, joilla tämä olisi periaatteessa mahdollista, ei ole automaattisen täytön mahdollisuutta (WCAG 1.3.5).
        </li>
        <li>
            <b>Lomakekenttien otsikot:</b> Lomakekentillä ei aina ole nimilappuja (label) tai nimilappua ei ole yhdistetty kenttään ohjelmallisesti (WCAG 3.3.2).
        </li>
        <li>
            <b>Lomake-elementtien merkinnät:</b> Valintapainikkeita ja kokonaisuuden muodostavia elementtejä ei olla merkitty ohjelmallisesti ryhmäksi, esimerkiksi Omien tietojen viestiasetusten muutospyynnöissä (WCAG 1.3.1 & 3.3.2 & 4.1.2).
        </li>
        <li>
            <b>Pakolliset kentät:</b> Pakollisten kenttien visuaalisessa ilmaisussa on ajoittain epäselvyyksiä (WCAG 1.4.1 & 3.3.2).
        </li>
    </ul>
    
    <h3>Muut yksittäiset toiminnallisuudet</h3>
    
    <ul class="list-bullets">
        <li>
            <b>Modaalidialogit: </b>Modaalin otsikkoa ei lueta ruudunlukijalle automaattisesti, vaan kohdistus siirtyy pelkästään sulkupainikkeeseen. Ruudunlukijalla kohdistus myös siirtyy modaalin alla olevaan sisältöön, kun modaalin sisältö päättyy. Kun käyttäjä sulkee modaalin, kohdistus siirtyy takaisin koko sivun alkuun eikä modaalin avanneeseen elementtiin. Myös modaalien otsikkohierarkioissa on ajoittain epäselvyyksiä. (WCAG 1.3.1 & 2.4.3)
        </li>
        <li>
            <b>Karusellit: </b>Palvelussa on karuselleja, joita ei ole ohjelmallisesti ryhmitelty, jolloin niiden funktiota voi olla vaikea ymmärtää ruudunlukijalla. Osa karusellien navigaatioelementeistä on myös englanniksi suomenkielisellä sivustolla. (WCAG 1.3.1 & 4.1.2)
        </li>
        <li>
            <b>Rikastietoeditori: </b>Kirjautumispuolella on suosikkilista, jonka nimeämisessä käytetään rikastietoeditoria. Kyseiseen editoriin ei pääse lainkaan käsiksi näppäimistökäytöllä ja sen käyttö on monin tavoin hankalaa eri apuvälineillä. Se muun muassa tallentuu dynaamisesti, mistä ei kerrota ruudunlukijalle, ja lisäksi editorin painikkeilla (esim. lihavoitu teksti jne.) ei ole tekstivastineita, jotta niistä selviäisi, mitä niistä tapahtuu. (WCAG 1.3.1 & 2.1.2 & 2.4.6)
        </li>
        <li>
            <b>Sisäänkirjautuminen:</b>Ruudunlukijan käyttäjälle ei ilmaista painiketekstissä selkeästi, että hän on kirjautunut sisään (WCAG 1.3.1 & 2.4.4).
        </li>
        <li>
            <b>Haku: </b>Hakuelementti on koodattu niin, että aina kun käyttäjä alkaa kirjoittaa sivulla, kaikki merkit kirjautuvat hakuelementtiin, vaikkei se olisi valittuna. Tämä tuo ongelmia joillain apuvälineillä, jos sivulla on muita lomakkeita (esimerkiksi Vinkkitorin Tiedonhaku-sivulla Kysy kirjastonhoitajalta -lomake). Kun hakukenttään alkaa kirjoittaa, sen alle ilmestyy dynaamisesti hakuehdotuksia. Ruudunlukijan käyttäjä ei kuitenkaan saa näistä mitään tietoa. (WCAG 1.3.1 & 2.1.4 & 3.2.1)
        </li>
        <li>
            <b>Sijaintikartta:</b>Yksittäisten kirjastojen sivuilla on kartta, jonka painikkeisiin ei pääse käsiksi näppäimistöllä. Lisäksi kartassa on ilmaistu auki ja kiinni olevat kirjastot käyttäen vain punaista ja vihreää väriä. (WCAG 1.4.1 & 2.1.1)
        </li>
        <li>
            <b>Kirjautumisen aikaraja:</b>Sisäänkirjautuminen on voimassa rajoitetun ajan.
        </li>
    </ul>
    
    <h3>Videot</h3>
    
    <p>Sivustolla on joitain 23.9.2020 jälkeen julkaistuja videoita, joiden saavutettavuutta ei ole varmistettu. (WCAG 1.2.1, 1.2.2, 1.2.3, 1.2.5)</p>
    
    <h3>Liitetiedostot</h3>
    
    <p>Sivustolla on liitetiedostoja, jotka eivät ole kaikin osin saavutettavia.</p>
    
    <p>Sovellettava lainsäädäntö ei kata kyseistä sisältöä.</p>
    
    <h2>Tämän saavutettavuusselosteen laatiminen</h2>
    
    <p>Tämä seloste on laadittu 19.1.2021 </p>
    
    <p>Seloste perustuu ulkopuolisen asiantuntijaorganisaation (Eficode Oy) toteuttamaan arviointiin siitä, täyttääkö verkkosivusto Lain digitaalisten palvelujen tarjoamisesta 306/2019 vaatimukset.</p>
    
    
    
    <h2>Palaute ja yhteystiedot</h2>
    <p>Kyyti.finna.fi-verkkosivuston saavutettavuudesta voi antaa palautetta.</p>
    <p><a href="<?=$this->url('feedback-home') ?>">Anna saavutettavuuspalautetta tällä verkkolomakkeella</a>.</p>
    <h3>Sähköpostilla</h3>
    <p>koha.posti(at)kouvola.fi</p>
    <p>Samojen yhteystietojen kautta voit pyytää direktiivin soveltamisalan ulkopuolelle jätettyjä tietoja ja sisältöä.</p>
    
    <h2>Täytäntöönpanomenettely</h2>
    
    <p>Jos huomaat sivustolla saavutettavuusongelmia, anna ensin palautetta sivuston ylläpitäjälle. Vastauksessa voi mennä 14 päivää. Jos et ole tyytyväinen saamaasi vastaukseen tai et saa vastausta lainkaan kahden viikon aikana, voit antaa palautteen Etelä-Suomen aluehallintovirastoon. </p>
    
    <h2>Valvontaviranomaisen yhteystiedot</h2>
    
    <p>Saavutettavuuden valvonnan yksikkö</p>
    <ul>
        <li><a href="https://www.saavutettavuusvaatimukset.fi">Saavutettavuusvaatimukset.fi</a></li>
        <li><a href="mailto:saavutettavuus@avi.fi">saavutettavuus@avi.fi</a></li>
        <li>Vaihde <a href="tel:0295016000">0295 016 000</a></li>
    </ul>
    
</div>
<!-- END of: finna - content/accessibility-statement_fi.phtml -->
