<!-- START of: Content/asiakkaana.en-gb.phtml -->

<? $this->headTitle('Using the library'); $this->content()->setHeading('Using the library'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>

    <div class="col-sm-9">

        <div id="libcard" class="content-section">
            
            <br>
            <img src="<?=$this->imageSrc('asiakkaana.jpg')?>" alt="Young person reading a book in library" />
            
            <h2>Applying for library card</h2>
            
            <p>You can get a library card from all Kyyti libraries by presenting a photo ID. If you are under 15 years old, you also need parental consent. You can print 
            the <a href="<?= $this->fileSrc('ilmoittautumislomake_eng_2024.pdf')?>" target="blank">Application Form for a Library Card</a> and fill it out before your visit.
            You can also get forms at the library.</p>
            <p>You can use your library card at all Kyyti libraries, which include all libraries in Kymenlaakso and Iitti.</p> 
            <p>The library card is free, but there is a fee for replacing a lost card. 
            If you suspect your library card might be lost, please report us about the loss of the card immediately. You are responsible for all borrowed items on your card until you report it missing.</p>
            
            <h3 id="pin">Library card PIN code</h3>
            <p>You can link a four-digit PIN code to your library card, which allows you to</p>
            <ul class="list-bullets">
                <li>Log in to the online library (renew loans, make reservations, update contact information)</li>
                <li>Access e-resources</li>
                <li>Use any self-service library of the Kyyti network</li>
                <li>Use self-service machines for borrowing items</li>
            </ul>
            <p>You can obtain the PIN code from any Kyyti library. Please bring your library card and a photo ID. The PIN code will not be provided over the phone or via email.</p>

            <h3>Keep Your Contact Information Up to Date</h3>
            <p>If your name, address, or other contact information changes, please inform the library.
            You can also update your information in the online library's <a href="https://kyyti.finna.fi/MyResearch/Profile" target="_blank">My Profile</a> section.</p>
            <p><a href="https://kyyti.finna.fi/Content/ohje#edit_information" target="_blank">Guide: Editing Your Information in the Online Library</a></p>
        </div>
        

        <div id="loans-renewals" class="content-section">
            <h2>Loans, renewals and returning</h2>
            <h3>Loan times vary based on content types</h3>    
            <p>Loan times for each content type in Kyyti libraries:</p>
            <ul class="list-bullets">
                <li>books, CDs, audiobooks: 28 days</li>
                <li>magazines and console games: 14 days</li>
                <li>DVD- and Blu-ray-discs: 14 days</li>
            </ul>
            <p>You can check the due date for your loans on the loan receipt or <a href="https://kyyti.finna.fi/MyResearch/CheckedOut" target="blank">in the "Checked Out Items" section of the online library.</a></p>
            
            <h3>Reminder message of the upcoming duedate</h3>
            <p>You can order a reminder for approaching due dates via email or text message from the <a href="https://kyyti.finna.fi/MyResearch/Profile" target="blank">"Your Account" section</a> of the online library or by contacting the library. The service is free of charge.</p>
            
            <p>However, please note that you are responsible for any late fees even if the reminders do not reach you.</p>
            
            <h3>Renewing your loans</h3>
            <p>You can renew your loans in the online library's <a href="https://kyyti.finna.fi/MyResearch/CheckedOut" target="blank">Loans section</a>, by phone, or at the library.</p>
            <p><a href="https://kyyti.finna.fi/Content/ohje#loans" target="blank">Instructions: renewing loans in the online library</a></p>

            <h3>You can return materials from Kyyti libraries to any Kyyti library.</h3>

            <p>When the library is closed, you can return loans through book drop box. Items left in the book drop box will be checked in on the next opening day of the library.
            Late fees may accrue during the waiting period. Note that the book drop boxes are available only in some libraries.</p>
        </div>
            
        <div id="organization" class="content-section">
            <h2>Kyyti libraries and opening hours</h2>
            
            <p>The libraries of Kymenlaakso and Iitti together form the Kyyti library network. The network's libraries share a common collection, reservation queue, and electronic resources.
            With your local municipality's library card, you can borrow materials from any library within the network and return the items to any Kyyti library. 
            If the material you are looking for is in the collection of another Kyyti library, you can request it free of charge to be delivered to your local library by placing a reservation on it.</p>
            
            <p>The Kyyti libraries consist of the following:</p>
            <ul class="list-bullets">
              <li>The city library of Hamina</li>
              <li>The municipal library of Iitti</li>          
              <li>The city library of Kotka</li>
              <li>The city library of Kouvola</li>
              <li>The municipal library of Miehikkälä</li>
              <li>The municipal library of Pyhtää</li>
              <li>The municipal library of Virolahti</li>
            </ul>
            <p>The library buses operate in Hamina, Iitti, Kotka, Kouvola, and Pyhtää.</p>
            
            <p>For further information and opening hours, check <a href="/OrganisationInfo">organisation info-pages of Kyyti libraries.</a></p>
        </div>


        <div id="holds" class="content-section">
            <h2>Reservations</h2>
            <h3>Placing a reservation</h3>

            <p>Instructions for reserving materials through online library</p>
            <ol class="list-numbers">
            <li>Search the content of your choice from online library catalogue.</li>
            <li>Click "Place a hold on this title" from search results or from info page of the title.</li>
            <li>Choose the pickup location for the reservation and click "Submit Request".</li>
            </ol>
            
            <p>You can also place the reservation through phone or from library's customer service.</p>
        
            <h3>Picking up and cancelling the reservation</h3>
            
            <p>You will receive a notification of the reserved material's arrival via email, text message, or postal letter. 
            You can change the notification delivery method in the <a href="https://kyyti.finna.fi/MyResearch/Profile" target="blank">"Your Account" section</a> of the online library, by phone, or at the library.</p>
            <p>Reserved materials will be held for seven days from the date the notification is sent."</p>
            
            <p>Reservation is free of charge, a fee is charged for unclaimed materials. 
            You can cancel the reservation in the online library's "Holds" section if the reservation has not been processed yet. 
            If the reservation has already been processed, please contact the library you have selected as the pickup location.</p>
            
            <p>Reserved materials will be held for seven days from the date the notification is sent.</p>
            
        </div>
            
        <div id="payments" class="content-section">
            <h2>Fees</h2>
            <p>Fees by municipality: </p>
            <ul class="list-bullets">
                <li><a href="<?=$this->url('content-page',  ['page' => 'maksut-hamina'])?>">Hamina</a></li>
                <li><a href="<?=$this->url('content-page',  ['page' => 'maksut-iitti'])?>">Iitti</a></li>
                <li><a href="<?=$this->url('content-page',  ['page' => 'maksut-kotka'])?>">Kotka</a></li>
                <li><a href="<?=$this->url('content-page',  ['page' => 'maksut-kouvola'])?>">Kouvola</a></li>
                <li><a href="<?=$this->url('content-page',  ['page' => 'maksut-miehikkala'])?>">Miehikkälä</a></li>
                <li><a href="<?=$this->url('content-page',  ['page' => 'maksut-pyhtaa'])?>">Pyhtää</a></li>
                <li><a href="<?=$this->url('content-page',  ['page' => 'maksut-virolahti'])?>">Virolahti</a></li>
            </ul>
            </div>
        
        <div id="userrights" class="content-section">
        <h2>User regulations</h2>
        <p>By receiving library card, you commit to adhering to the <a href="<?=$this->url('content-page',  ['page' => 'kayttosaannot'])?>">User regulations</a> of the Kyyti libraries.</p>
        </div>
        
    </div>
</div>


<!-- END of: Content/asiakkaana.en-gb.tpl -->
  
