<!-- START of: Content/digituki.fi.phtml -->

<? $this->headTitle('Digituki'); $this->content()->setHeading('Digituki'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>
    
    <div class="col-sm-9">
        <p><img src="<?=$this->imageSrc('palvelut/digituki_banneri.jpg')?>" alt="Kaksi vanhusta tutkii yhdessä tablettia ja kännykkää" /></p>
        
        <div id="digituen_esittely" class="content-section">
            <h2>Kirjastojen digituki</h2>
            <p>Kirjaston henkilökunta opastaa sinua kirjaston digitaalisten palvelujen käytössä ja muiden digitaalisten palveluiden äärelle.
            Neuvomme esimerkiksi tiedonhaussa, tulostamisessa, skannaamisessa sekä kirjaston e-aineistojen ja verkkopalvelujen käytössä.</p>
            
            <p>Osassa Kymenlaakson kirjastoja vierailee myös vapaaehtoisia digiavustajia. Digiavustajien kanssa voit tutustua syvemmin sinua kiinnostaviin digipalveluihin 
            ja opetella käyttämään omia laitteitasi.</p>
            <p>Autamme mielellämme arjen digiongelmissa, mutta salasanat tai vahvan tunnistautumisen välineet, kuten pankkitunnukset, ovat henkilökohtaisia ja opastajat eivät kirjaudu 
            niillä verkkopalveluihin asiakkaiden puolesta. Opastajat eivät tee puolestasi hakemuksia, ostoja, virallisia dokumentteja, tilisiirtoja tai korjaa laitteita. 
            Pankkipalveluissa opastajat voivat auttaa ainoastaan yksinkertaisissa teknisissä toimenpiteissä, kuten tilitapahtumien tulostamisessa. 
            Opastuksen aikana vastuu omasta laitteesta ja ohjelmistoista on asiakkaalla.</p>
            
            <p style="text-align:left;">Kouvolan, Kotkan ja Iitin kirjastot ovat osa valtakunnallista digitukiverkostoa. Digitukiverkoston jäsenet ovat sitoutuneet tarjoamaan ja kehittämään digitukea ja noudattamaan Digi- ja väestötietoviraston 
            <a href="https://dvv.fi/digituen-eettinen-ohjeistus" target="blank">Digituen eettinen ohjeistus -sivulla</a> olevia ohjeita. 
            Linkki suomenkielisiin ohjeisiin <a href="https://dvv.fi/documents/16079645/0/Digituen+eettinen+ohjeistus+FI_2023.pdf/d20d67cf-34aa-c2a0-0e19-8d22d20bac47/Digituen+eettinen+ohjeistus+FI_2023.pdf?t=1685687267931" target="blank">tästä</a></p>
        </div>

        <div id="digitukea_kunnittain" class="content-section">
            <h2>Digitukea kunnittain</h2>
            <h3>Kouvola</h3>
            <h4>Digitukea kirjastosta</h4>
            <p>Kirjaston asiakaspalvelussa opastetaan päivittäisissä digiasioissa. Pääkirjaston Mediamajassa autetaan vaativammissa digiasioissa.</p>

            <p>Kirjaston asiakaspalvelun digituki</p>
            <ul class="list-bullets">
                <li>Kirjaston verkkopalvelut</li>
                <li>Tiedonhaku ja -palvelu</li>
                <li>E-aineistot, esim. e-kirjat ja -äänikirjat</li>
                <li>Kirjastossa käytettävien laitteiden opastus</li>
            </ul>
            <p><a href="https://kyyti.finna.fi/OrganisationInfo" target="blank">Voit tarkastaa kirjastojen yhteistiedot ja aukioloajat täältä</a></p>
            <p>Mediamajan palvelut</p>
            <ul class="list-bullets">
                <li>Digiopastusta tietokoneen, tablettien ja älypuhelimien käytössä sekä apua asiakkaiden jokapäiväisten digitaalisten palvelujen kanssa.</li>
                <li>Laitteita videon, kuvan ja äänen editointiin. Henkilökunta opastaa laitteiden ja ohjelmien käyttöön.</li>
                <li>Tapahtumia, luentoja, konsertteja, mediakasvatuksellisia työpajoja oppilaitoksille ja ryhmille.</li>
            </ul>
            <p>Mediamaja sijaitsee Kouvolan pääkirjaston (Salpausselänkatu 33) alakerrassa. Ota yhteyttä <a href="tel:+358206151333">020 615 1333</a> tai <a href="mailto:mediamaja@kouvola.fi">mediamaja@kouvola.fi</a>.</p>
            <p><a href="<?=$this->url('content-page',  ['page' => 'mediamaja'])?>">Lue lisää Mediamajan toiminnasta</a></p>
            <p><a href="https://www.kouvola.fi/kouvolankaupunki/asiointi/digituki/" target="blank">Kattavammat tiedot digituesta Kouvolan alueella</a></p>
            <br>

            <h3>Kotka</h3>
            <h4>Digiopastajat auttavat kaikissa digiasioissa</h4>
            <p>Digiopastajat eli vapaaehtoiset digineuvojat opastavat torstaisin klo 16-18 Kotkan pääkirjastossa. Digiopastajat auttavat asiakkaita kaikenlaisissa digiongelmissa,
            koskevat ne sitten älypuhelinten, tietokoneiden, tablettien tai sovellusten käyttöä.</p>
            <h4>Opastusta 3D-tulostamiseen ja digitointiin</h4>
            <p>Pääkirjastosta voit varata myös opastuksia 3D-tulostamiseen ja digitointiin. Kirjaston laitteilla voit digitoida VHS-kasetteja, valokuvia, negatiiveja, dioja, 
            C-kasetteja ja LP-levyjä. Voit myös editoida videoita, valokuvia ja ääntä.</p>
            <p>Digitointitila ja opastukset varataan pääkirjaston tietopalvelusta:</p>
            <ul class="list-bullets">
                <li>Puhelin: <a href="tel:+358406883754">040 688 3754</a></li>
                <li>Sähköposti: <a href="mailto:kirjasto@kotka.fi">kirjasto@kotka.fi</a></li>
            </ul>
            <br>

            <h3>Hamina</h3>
            <h4>Digineuvontaa kirjaston asiakaspalvelusta</h4>
            <p>Kirjaston asiakaspalvelusta saat neuvontaa:</p>
            <ul class="list-bullets">
                <li>Kirjaston verkkopalveluiden käyttämiseen</li>
                <li>Tiedonhakuun</li>
                <li>E-aineistojen käyttämiseen</li>
                <li>Kirjaston laitteiden käyttämiseen</li>
            </ul>
            
            <h4>Digiopastukset vaativampiin digipulmiin</h4>
            <p>Haminan pääkirjastossa järjestetään joka tiistai kello 12-14 digiopastusta. Digiopastuksissa autamme kännykän ja tietokoneen käyttämisessä, 
            sovellusten lataamisessa, laitteiden päivittämisessä, verkkoasioinnnissa ja muissa digiongelmissa.</p>
            <p>Opastukset ovat maksuttomia, eikä niihin tarvitse varata aikaa. Opastajina toimivat Ekamin tieto- ja viestintätekniikan opiskelijat.
            Opastukset järjestetään pääkirjaston Aladin-tilassa, joka sijaitsee kirjaston takaosassa lehtisalin takana.</p>
            <br>

            <h3>Iitti</h3>
            <p>Kirjaston henkilökunta opastaa asiakastietokoneiden sekä asiakkaiden mobiililaitteiden käytössä mahdollisuuksien mukaan. 
            Vapaaehtoiset digitutorit opastavat laajemmin laitteiden ja digipalveluiden käytössä ja muissa digipulmissa.</p>
            <p>Iitin kunnankirjasto on osa valtakunnallista digitukiverkostoa.</p>
            <br>
            
            <h3>Pyhtää</h3>
            <p>Kirjaston henkilökunta opastaa asiakastietokoneiden sekä asiakkaiden mobiililaitteiden käytössä mahdollisuuksien mukaan.</p>
            <br>
        
            <h3>Virolahti ja Miehikkälä</h3>
            <p>Kirjaston henkilökunta opastaa asiakastietokoneiden sekä asiakkaiden mobiililaitteiden käytössä mahdollisuuksien mukaan.</p>
        </div>
        
        <div id="digitukea_verkossa" class="content-section">
            <h2>Digituki verkossa</h2>
            <h3>Opiskele digitaitoja</h3>
            <strong><a href="https://yle.fi/aihe/digitreenit" target="_blank">Ylen Digitreenit</a></strong>
            <p>Ylen Digitreenit neuvoo ja opastaa arjen digitaidoissa.</p>
            <strong><a href="https://yle.fi/aihe/artikkeli/2019/03/25/mita-ovat-selain-kayttis-ja-wifi-laaja-digisanasto-selittaa-sanat-selvalla" target="_blank">Ylen digisanasto</a></strong>
            <p>Ylen digisanasto avaa digitermit ymmärrettävästi.</p>
            <strong><a href="https://snellmanedu.fi/digiosaamisen-perusteet/" target="_blank">DiKaTan Digiosaamisen perusteet -verkkokurssi</a></strong>
            <p>DiKaTa-hankkeen verkkokoulutukset auttavat arjen ja työn digitaitojen opettelussa.</p>
            <strong><a href="https://www.entersenior.fi/opiskele-itse/" target="_blank">Enter ry:n itseopiskelumateriaalit</a></strong>
            <p>Itseopiskelumateriaaleja senioreiden digiopintoihin.</p>
            <strong><a href="https://www.makupalat.fi/fi/kokoelma/digiopastusta" target="_blank">Makupalojen digiopastussivut</a></strong>
            <p>Makupalat-linkkikirjaston digiaiheiset linkit.</p> 
            <strong><a href="https://sites.google.com/view/nettivinkkaus/etusivu" target="_blank">Tampereen kaupunginkirjaston digivinkit</a></strong>
            <p>Tampereen kaupunginkirjaston digivinkkausten materiaalit. Tietoa esimerkiksi digipalveluista, laitteista ja tietoturvasta.</p>
            
            <h3>Sähköisen asioinnin oppaat</h3>
            <strong><a href="https://yle.fi/aihe/artikkeli/2018/04/18/digitreenit-asiakirjat-sahkoisiksi-nailla-vinkeilla-toimitat-vaaditut-liitteet" target="_blank">Digitreenit: asiakirjat sähköisiksi</a></strong>
            <p>Näin skannaat paperiasiakirjoja sähköiseen muotoon ja lähetät ne viranomaiselle.</p>
            <strong><a href="https://www.kanta.fi/omakanta-verkkokoulu/#/?_k=6qvpb4" target="_blank">Omakannan verkkokoulu</a></strong>
            <p>Omien terveystietojen tutkiminen Omakanta-palvelussa.</p>
            <strong><a href="https://www.youtube.com/channel/UCVGeKHwTsAKYnksI5RArrWg" target="_blank">OmaVeron opasvideot</a></strong>
            <p>Kuinka käytät verohallinnon OmaVero-palvelua.</p>
                
            <h3>Tietoturvaohjeita</h3>
            <strong><a href="https://www.kuluttajaliitto.fi/hankkeet/huijarit-kuriin/" target="_blank">Kuluttajaliiton huijausohje</a></strong>
            <p>Epäiletkö tulleesi huijatuksi verkossa? Oletko huolissasi läheisesi puolesta? Lue Kuluttajaliiton ohjeet digihuijausten ehkäisyyn ja jälkihoitoon.</p>
            <strong><a href="https://www.kyberturvallisuuskeskus.fi/fi/ajankohtaista/ohjeet-ja-oppaat/ohjeet-ja-oppaat-yksityishenkiloille" target="_blank">Kybertuvallisuuskeskuksen tietoturvaoppaat</a></strong>
            <p>Tietoturvaoppaat avaavat kyberturvallisuuden perussanastoa ja ohjeistavat oman tietoturvan parantamiseen kotona ja työpaikalla.</p>            

            <h3>Opastuspalvelut verkossa</h3>
            
            <strong><a href="https://www.kansalaisneuvonta.fi/fi-FI" target="_blank">Kansalaisneuvonta</a></strong>
            <p>Kansalaisneuvonta auttaa kansalaista löytämään oikean viranomaisen tai viranomaisen sähköisen palvelun asiansa hoitamiseen. 
            Kansalaisneuvonta auttaa myös sähköisessä asioinnissa ja vastaa yleisluontoisiin kysymyksiin julkisista palveluista.</p>
        </div>
    </div>
</div>

<!-- END of: Content/digituki.fi.tpl -->