<!-- START of: Content/e-aineistojen_ohjeet.fi.phtml -->
    
<? $this->headTitle('Näin käytät e-aineistoja'); $this->content()->setHeading('Näin käytät e-aineistoja'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>

    <div class="col-sm-9">
        <div class="e-kuvat">
            <div id="e-kirjat" class="content-section">
                <h2>E-kirjat, äänikirjat ja kotimaiset aikakauslehdet (E-kirjasto)</h2>
                <p>Voit lukea e-kirjoja ja kotimaisia aikakauslehtiä sekä kuunnella äänikirjoja Kansalliskirjaston E-kirjastossa.</p>
                <p class="kyyti-badge-container">
                    E-kirjasto-sovelluksen voit ladata Googlen Play-kaupasta tai Applen App Storesta:
                    <br>
                    <a href="https://play.google.com/store/apps/details?id=fi.kansalliskirjasto.ekirjasto">
                    <img class="kyyti-badge" src="<?=$this->imageSrc('sovellukset/google-play-badge_fi.png')?>" alt="Lataa Googlen Play-kaupasta"></a>
                    <a href="https://apps.apple.com/fi/app/e-kirjasto/id6471490203?l=fi">
                    <img class="kyyti-badge" src="<?=$this->imageSrc('sovellukset/app-store-badge-black_fi.svg')?>" alt="Lataa Applen App Storesta"></a>
                </p>
                <br>
                <p><a href="https://www.kansalliskirjasto.fi/fi/e-kirjasto/e-kirjasto-sovelluksen-kayttoohjeet" target="blank">Tarkemmat ohjeet E-kirjasto-sovelluksen käyttöönottoon (kansalliskirjasto.fi)</a></p>
            </div>
        
            <div id="ulkomaiset_sanomalehdet" class="content-section">
                <h2>Ulkomaiset sanoma- ja aikakauslehdet (Pressreader)</h2>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/pressreader_logo.png')?>" width="300" alt="PressReaderin logo"></p>
                
                <p>Pressreader-lehtipalvelussa on yli 7 000 sanoma- ja aikakauslehteä 120 maasta yli 60 kielellä.
                Lehdet ovat luettavissa kahden kuukauden ajan ilmestymispäivästä.</p>
    
                <p>Voit käyttää palvelua kirjaston tietokoneilla tai kirjaston ulkopuolella omalla tietokoneella ja mobiililaitteilla. 
                Lehtiä voi lukea joko selaimella tai mobiililaitteissa erillisellä sovelluksella.
                Etäkäytössä tarvitset sekä selaimella että sovelluksessa kirjautumiseen kirjastokortin numeron ja korttiin liitetyn nelinumeroisen tunnusluvun.</p>
    
                <h3>Internet-selaimella lukeminen</h3>
                <h4>Kirjautuminen</h4>
                <p><a href="https://www.pressreader.com" target="blank">Voit siirtyä Pressreader-palveluun tästä</a>.</p>
                <p>Kirjaston tietokoneilla tai kirjaston langattomassa vierailijaverkossa lehdet toimivat kirjautumatta. 
                Jos käytät palvelua etänä, kirjaudu pressreaderin sivulla ennen käyttöä palveluun seuraavasti: 
                <ol class="list-numbers">
                    <li>Napauta oikeasta yläkulmasta ”Sign in”-painiketta.</li>
                    <li>Napauta kirjautumisikkunassa “Library or Group”-painiketta.</li>
                    <li>Hae ja valitse "Library – Kyyti Libraries (Kymenlaakso, Finland)".</li>
                    <li>Kirjoita kenttiin kirjastokortin numerosi ja korttiin liitetty nelinumeroinen tunnusluku.</li>
                </ol>
    
                <h4>Lehtien hakeminen</h4>
                <p>PressReaderin etusivulle on koottu suosituimpia sanoma- ja aikakauslehtiä sekä lehtisuosituksia aihealueittain. Jos haluat selata koko lehtivalikoimaa,
                napauta joko osiossa "Newspapers" (sanomalehdet) tai "Magazines" (aikakauslehdet) "See All"-painiketta.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/selaa.jpg')?>" width="1200" alt="See All -painike valikossa PressReaderissa"></p>
                
                <p>Kun olet avannut kaikkien lehtien näkymän, voit rajata oikean yläkulman rajausvalikoista näkyviin vain tietyssä maassa julkaistut ("All countries") tai tietynkieliset ("All languages") lehdet.
                <br>
                <img src="<?=$this->imageSrc('elehtiohjeet/rajauspainikkeet.jpg')?>" width="300" alt="Rajauspainikkeet"></p>
    
                <p>Voit esimerkiksi valita vain englanninkieliset lehdet napauttamalla "All languages"-painiketta, valitsemalla avautuvasta valikosta "English" ja napauttamalla "Done"-painiketta.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/englanti.jpg')?>" width="200" alt="kielen englanti painikkeen valinta"></p>
    
                <p>Jos haluat poistaa rajauksen, napauta rajauspainiketta ja valitse joko julkaisumaan valinnassa "All countries" tai kielen valinnassa "All languages"</p>  
                
                <p>Voit myös hakea lehtiä. Aloita haku napauttamalla oikeassa yläkulmassa suurennuslasi-kuvaketta
                (<img src="<?=$this->imageSrc('elehtiohjeet/suurennuslasi.jpg')?>" width="20" alt="Hakupainike">). Kirjoita hakukenttään lehden nimi, aihe tai muu lehteä kuvaava hakusana, niin
                haku listaa lehdet hakukentän alle.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/haku.jpg')?>" width="700" alt="Hakutuloslista"></p>
                <p>Pääset selaamaan lehden numeroita napauttamalla lehden nimeä tai kansikuvaa.</p>
    
                <p>Kun olet etsinyt lehden selaamalla tai hakemalla, pääset lukemaan lehden uusinta numeroa napauttamalla "Read now"-painiketta</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/lue.jpg')?>" width="400" alt="Lehden avauspainike"></p>
                <p>Jos haluat lukea lehden vanhempia numeroita, siirry sivulla alemmas kohtaan "Latest issues", napauta haluamaasi lehteä ja sen jälkeen "Read now"-painiketta.</p>
                <p>Kun olet avannut lehden, voit selata lehteä eteen- tai taaksepäin viemällä kursorin ruudun oikean tai vasemman reunan päälle ja napauttamalla nuoli-painiketta.</p>
                <img src="<?=$this->imageSrc('elehtiohjeet/selauspainike.jpg')?>" width="800" alt="Sivunvaihtopainike">
                <p>Voit avata artikkelin lukutilaan napauttamalla artikkelin otsikkoa. Jos haluat palata selaamaan lehden sisältöä, napauta "Page View"-painiketta.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/lukutila.jpg')?>" width="200" alt="Luku- ja selaustilan vaihtopainike"></p>
    
                <h3>Mobiilisovelluksella lukeminen</h3>
                <h4>Sovelluksen asentaminen</h4>
                <p>Voit asentaa Pressreader-sovelluksen Android-laitteisiin <a href="https://play.google.com/store/apps/details?id=com.newspaperdirect.pressreader.android&hl=fi&gl=US" target="blank">Play-kaupasta</a> 
                ja Applen laitteille <a href="https://apps.apple.com/us/app/pressreader-news-magazines/id313904711" target="blank">App Storesta</a>.</p>
        
                <h4>Kirjautuminen</h4>
                <p>Näin kirjaudut sovellukseen:</p>
                <ol class="list-numbers">
                    <li>Avaa sovellus ja napauta "Sign in"-painiketta.</li>
                    <li>Napauta "Libraries & Groups"-painiketta.</li>
                    <li>Avaa "Select Library of Group -valikko", kirjoita hakukenttään "kyyti" ja valitse "Kyyti-kirjastot - Kyyti Libraries".</li>
                    <li>Kirjoita "Library card number"-kenttään kirjastokortin numerosi ja "PIN"-kenttään kirjastokorttiin liitetty nelinumeroinen tunnusluku.</li>
                    <li>Napauta "Sign in".</li>
                </ol>
                <p>Laitteen pitäisi muistaa kirjautumisesi, kun avaat sovelluksen uudestaan. 
                Jos lehdet eivät kuitenkaan avaudu normaalisti, voit tarkastaa "Browse"-välilehdeltä, että kirjautumisesi on varmasti voimassa. Olet kirjautunut palveluun, jos kahvikupin kuvake on vihreä.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/kuppi.jpg')?>" width="300" alt="Kirjautumisesta kertova kahvikupin kuvake"></p>
                <p>Jos kahvikuppi on harmaa, kirjaudu uudelleen "Sign in"-painikkeesta.</p>
                
                <h4>Lehtien hakeminen</h4>
                <p>Voit selata lehtivalikoimaa napauttamalla "Browse"-painiketta.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/browse.jpg')?>" width="300" alt="Selaus-välilehden painike"></p>
                <p>Browse-välilehdellä on useita Pressreaderin valmiiksi koostamia kokoelmia, kuten suositukset (Recommended), luetuimmat (Top Newspapers) ja uusimmat ilmestyneet numerot (Recently added).</p>
                <p>Jos haluat selata vain tietyssä maassa julkaistuja tai tietyn kielisiä lehtiä, napauta "Countries"- tai "Languages"-painiketta</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/rajaukset.jpg')?>" width="300" alt="Maan tai kielen rajausvalikot"></p>
                <p>ja valitse maa tai kieli.</p>
                <p>Voit myös hakea lehtiä. Napauta hakukenttää sovelluksen ylälaidassa ja kirjoita esimerkiksi lehden nimi tai aihealue. 
                Alla esimerkissä on haettu sanalla "newsweek".</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/lehtihaku.jpg')?>" width="300" alt="Hakukenttä ja hakutulokset"></p>
    
                <p>Pääset selaamaan lehden numeroita napauttamalla lehden kansikuvaa. 
                Numeroiden selausnäkymässä on ylimpänä lehden uusin numero ja alempana kohdassa "Latest issues" aiemmin ilmestyneet numerot.</p>
                <p>Lehti avautuu napauttamalla halutun numeron kansikuvaa. Jos et ole langattomassa verkossa, sovellus saattaa pyytää vielä ennen lehden avaamista vahvistamaan lataamisen.</p>
                
                <h4>Lehden selaaminen ja artikkelien lukeminen</h4>
                <p>Lehden sivuja vaihdetaan pyyhkäisemällä vasemmalle tai oikealle.</p>
                <p>Kun haluat lukea artikkelin, napauta sen otsikkoa, niin artikkeli aukeaa koko ruudun lukunäkymään, jossa tekstiä on helpompaa lukea. 
                Pääset takaisin selausnäkymään napauttamalla vasemman yläkulman nuolipainiketta.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/lukunäkymä.jpg')?>" width="300" alt="Lukunäkymä"></p>
                <p>Voit selata lehteä nopeammin selauspalkin avulla. Selauspalkki ilmestyy näkyviin, kun napautat lehteä.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/selauspalkki.jpg')?>" width="300" alt="Selauspalkki"></p>
                <p>Sivuja selataan selauspalkissa pyyhkäisemällä vasemmalle tai oikealle ja sivu avautuu napauttamalla sen esikatselukuvaa.</p>
                <p>Napauttamalla lehteä, saat näkyviin selauspalkin lisäksi myös muita hyödyllisiä toimintoja.</p>
                <p><img src="<?=$this->imageSrc('elehtiohjeet/toiminnot.jpg')?>" width="300" alt="Lukunäkymän toimintopainikkeet"></p>
                <p>Voit esimerkiksi:</p>
                <ol class="list-bullets">
                    <li>Kuunnella lehden koneluettuna napauttamalla kuulokkeiden kuvaketta.</li>
                    <li>Avata lehden sisällysluettelon napauttamalla oikean yläkulman lista-kuvaketta.</li>
                    <li>Siirtyä tiettyyn artikkeliin oikean alalaidan lista-kuvakkeesta.</li>
                    <li>Merkitä lehden suosikiksi napauttamalla sydämen-kuvaketta. Suosikeiksi merkityt lehdet ilmestyvät "Browse"-välilehdelle kohtaan "My Publications".</li>
                </ol>
            </div>
            
            <div id="kuuntele_musiikkia_netissa" class="content-section">
                <h2>Musiikin suoratoisto (Naxos)</h2>
                <p class="ex">
                    <a target="_blank" href="https://kouvola.naxosmusiclibrary.com/page.library_cardno.asp"><img src="<?=$this->imageLink('naxmusic.jpg')?>" alt="Naxos Classic -musiikkipalvelu"></a>
                    <a target="_blank" href="http://kouvola.naxosmusiclibrary.com/Jazz"><img src="<?=$this->imageLink('naxjazz.jpg')?>" class="centered" alt="Naxos Jazz -musiikkipalvelu"></a>
                    <a target="_blank" href="http://kouvola.naxosmusiclibrary.com/World"><img src="<?=$this->imageLink('naxworld.jpg')?>" alt="Naxos World -musiikkipalvelu"></a>
                </p>
                
                <p class="ex">Naxoksen kolmessa kuuntelupalvelussa voit kuunnella musiikkia suoratoistona maksutta. Valikoimassa on tuhansia levyjä klassista musiikkia, maailmanmusiikkia, jazzia ja vanhempaa popmusiikkia.</p>
                
                <p class="ex">Naxos Music Libraryssä on myös tietoa klassisen musiikin säveltäjistä ja esittäjistä, musiikkisanasto, oopperoiden librettoja ja juonikuvauksia, valmiita soittolistoja sekä materiaalia musiikkikasvatukseen.</p>
                
                <h3>Näin aloitat kuuntelun</h3>
                
                <p class="ex">Aloittaaksesi kuuntelun, avaa ensin haluamasi Naxoksen musiikkipalvelu</p>
                <ul class="list-bullets">
                    <li><a href="https://kouvola.naxosmusiclibrary.com/" target="blank">Naxos Music Library (klassinen musiikki)</a></li>
                    <li><a href="http://kouvola.naxosmusiclibrary.com/Jazz" target="_blank">Naxos Jazz</a></li>
                    <li><a href="http://kouvola.naxosmusiclibrary.com/World" target="_blank">Naxos World</a></li>
                </ul>
                <p>Syötä sitten kirjastokortin numerosi "Enter your Library Card Number"-kenttään ja napauta Login-painiketta.</p>
                
                
                <p class="ex">Palvelu toimii kaksi tuntia kerrallaan. Jos haluat jatkaa kuuntelua kahden tunnin jälkeen, kirjaudu uudestaan sisään. 
                Kun lopetat kuuntelun, kirjaudu ulos "Log out"-painikkeella. Palvelussa on rajattu määrä kuunteluoikeuksia ja kirjautumalla ulos vapautat oikeuden toiselle käyttäjälle.</p>
                
                <h3>Rekisteröitymällä voit luoda soittolistoja ja käyttää mobiilisovellusta</h3>
                <p>Jos haluat tallentaa kappaleita henkilökohtaisille soittolistoille tai käyttää mobiilisovellusta, sinun pitää rekisteröityä Naxoksen palveluihin.</p>
                
                <ol class="list-numbers">
                    <li>Avaa <a href="https://kouvola.naxosmusiclibrary.com/" target="blank">Naxos Music Library</a>, <a href="http://kouvola.naxosmusiclibrary.com/Jazz" target="blank">Naxos Jazz</a> tai <a href="http://kouvola.naxosmusiclibrary.com/World" target="blank">Naxos World</a>. 
                    Kuhunkin Naxoksen palveluun pitää rekisteröityä erikseen.</li>
                    <li>Kirjoita Enter your Library Card Number -kenttään Kyyti-kirjastokorttisi numero ja valitse Login.</li>
                    <li>Valitse Playlists-välilehti. Mobiililaitteilla playlists on menu-valikossa (kolmen viivan kuvake).</li>
                    <li>Klikkaa kohdasta Student/member Account linkkiä Sign up.</li> 
                    <li>Täytä lomake ja valitse Register New Account Now.</li>
                    <li>Sähköpostiisi lähetetään viesti, jossa on vahvistuslinkki rekisteröitymiselle. Napauta linkkiä, niin tilisi otetaan käyttöön.</li>
                </ol>
                
                <p>Rekisteröitymisen jälkeen voit kirjautua haluamaasi palveluun antamallasi sähköpostiosoitteella ja salasanalla alla olevista osoitteista</p>
                <ul class="list-bullets">   
                    <li><a href="https://www.nml3.naxosmusiclibrary.com/login" target="blank">Naxos Music Library</a></li>
                    <li><a href="https://www.naxosmusiclibrary.com/jazz/login?rurl=%2FJazz" target="blank">Naxos Jazz</a></li>
                    <li><a href="https://www.naxosmusiclibrary.com/world/login" target="blank">Naxos World</a></li>
                </ul>
                    
                <p>Kirjautuneena voit tallentaa henkilökohtaisia soittolistoja ja selata niitä Playlists-välilehdeltä.</p>
                <p>Rekisteröitymisen jälkeen voit myös kuunnella musiikkia mobiilisovelluksella. Voit ladata sovelluksen Applen laitteille App Storesta tai Android-laitteille Googlen Play-kaupasta. 
                Jokaiselle Naxoksen palvelulle (Music Library, Jazz, World) on oma sovelluksensa.</p>
                <p>Mobiilisovellukseen kirjaudutaan rekisteröityessä antamallasi sähköpostiosoitteella ja salasanalla.</p>
            </div>
        </div>
    </div>
 </div>

<!-- END of: Content/e-aineistojen_ohjeet.fi.tpl -->