<!-- START of: Content/e-lehdet_ohje_fi.phtml -->
    
<? $this->headTitle('Näin luet ulkomaisia sanoma- ja aikakauslehtiä'); $this->content()->setHeading('Näin luet ulkomaisia sanoma- ja aikakauslehtiä'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>
    <div class="col-sm-9">
        <div id="esittely" class="content-section">
            <h2>Esittely</h2>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/pressreader_logo.png')?>" width="300" alt="PressReaderin logo"></p>
            
            <p>Pressreader-lehtipalvelussa on yli 7 000 sanoma- ja aikakauslehteä 120 maasta yli 60 kielellä.
            Lehdet ovat luettavissa kahden kuukauden ajan ilmestymispäivästä.</p>

            <p>Voit käyttää palvelua kirjaston tietokoneilla tai kirjaston ulkopuolella omalla tietokoneella ja mobiililaitteilla. 
            Lehtiä voi lukea joko selaimella tai mobiililaitteissa erillisellä sovelluksella.
            Etäkäytössä tarvitset sekä selaimella että sovelluksessa kirjautumiseen kirjastokortin numeron ja korttiin liitetyn nelinumeroisen tunnusluvun.</p>
        </div>

        <div id="selaimella" class="content-section">
            <h2>Internet-selaimella lukeminen</h2>
            <h3>Kirjautuminen</h3>
            <p>Kirjaston tietokoneilla tai kirjaston langattomassa vierailijaverkossa lehdet toimivat kirjautumatta. 
            Siirry vain osoitteeseen <a href="https://www.pressreader.com" target="blank">pressreader.com</a> ja aloita lukeminen.</p> 
            <p>Jos käytät palvelua etänä, kirjaudu Pressreaderiin näin:</p> 
            <ol class="list-numbers">
                <li><a href="https://www.pressreader.com" target="blank">Siirry pressreader.com-sivustolle</a>.</li>
                <li>Napauta oikeasta yläkulmasta ”Sign in”-painiketta.</li>
                <li>Napauta kirjautumisikkunassa “Library or Group”-painiketta.</li>
                <li>Hae ja valitse "Kyyti-libraries (Kouvola, Kotka, Iitti, Hamina)".</li>
                <li>Kirjoita kenttiin kirjastokortin numerosi ja korttiin liitetty nelinumeroinen tunnusluku.</li>
                <li>Hyväksy kirjautumistietojen välittäminen valitsemalla "I agree to allowing PressReader to verify and exchange my registration with my public library" ja napauta "Log In"-painiketta.</li>
            </ol>

            <h3>Lehtien hakeminen</h3>
            <p>PressReaderin etusivulle on koottu suosituimpia sanoma- ja aikakauslehtiä sekä lehtisuosituksia aihealueittain. Jos haluat selata koko lehtivalikoimaa,
            napauta joko osiossa "Newspapers" (sanomalehdet) tai "Magazines" (aikakauslehdet) "See All"-painiketta.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/selaa.jpg')?>" width="1200" alt="See All -painike valikossa PressReaderissa"></p>
            
            <p>Kun olet avannut kaikkien lehtien näkymän, voit rajata oikean yläkulman rajausvalikoista näkyviin vain tietyssä maassa julkaistut ("All countries") tai tietynkieliset ("All languages") lehdet.
            <br>
            <img src="<?=$this->imageSrc('elehtiohjeet/rajauspainikkeet.jpg')?>" width="300" alt="Rajauspainikkeet"></p>

            <p>Voit esimerkiksi valita vain englanninkieliset lehdet napauttamalla "All languages"-painiketta, valitsemalla avautuvasta valikosta "English" ja napauttamalla "Done"-painiketta.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/englanti.jpg')?>" width="200" alt="kielen englanti painikkeen valinta"></p>

            <p>Jos haluat poistaa rajauksen, napauta rajauspainiketta ja valitse joko julkaisumaan valinnassa "All countries" tai kielen valinnassa "All languages"</p>  
            
            <p>Voit myös hakea lehtiä. Aloita haku napauttamalla oikeassa yläkulmassa suurennuslasi-kuvaketta
            (<img src="<?=$this->imageSrc('elehtiohjeet/suurennuslasi.jpg')?>" width="20" alt="Hakupainike">). Kirjoita hakukenttään lehden nimi, aihe tai muu lehteä kuvaava hakusana, niin
            haku listaa lehdet hakukentän alle.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/haku.jpg')?>" width="700" alt="Hakutuloslista"></p>
            <p>Pääset selaamaan lehden numeroita napauttamalla lehden nimeä tai kansikuvaa.</p>
        </div>
        
        <div>
            <h3>Lehden lukeminen</h3>
            <p>Kun olet etsinyt lehden selaamalla tai hakemalla, pääset lukemaan lehden uusinta numeroa napauttamalla "Read now"-painiketta
            <img src="<?=$this->imageSrc('elehtiohjeet/lue.jpg')?>" width="400" alt="Lehden avauspainike"></p>
            <p>Jos haluat lukea lehden vanhempia numeroita, siirry sivulla alemmas kohtaan "Latest issues", napauta haluamaasi lehteä ja sen jälkeen "Read now"-painiketta.</p>
            <p>Kun olet avannut lehden, voit selata lehteä eteen- tai taaksepäin viemällä kursorin ruudun oikean tai vasemman reunan päälle ja napauttamalla nuoli-painiketta.</p>
            <img src="<?=$this->imageSrc('elehtiohjeet/selauspainike.jpg')?>" width="800" alt="Sivunvaihtopainike">
            <p>Voit avata artikkelin lukutilaan napauttamalla artikkelin otsikkoa. Jos haluat palata selaamaan lehden sisältöä, napauta "Page View"-painiketta.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/lukutila.jpg')?>" width="200" alt="Luku- ja selaustilan vaihtopainike"></p>
        </div>
        
        <div id="mobiilissa" class="content-section">
            <h2>Mobiilisovelluksella lukeminen</h2>
            <h3>Sovelluksen asentaminen</h3>
            <p>
            Voit asentaa Pressreader-sovelluksen Android-laitteisiin <a href="https://play.google.com/store/apps/details?id=com.newspaperdirect.pressreader.android&hl=fi&gl=US" target="blank">Play-kaupasta</a> 
            ja Applen laitteille <a href="https://apps.apple.com/us/app/pressreader-news-magazines/id313904711" target="blank">App Storesta</a>.</p>
    
            <h3>Kirjautuminen</h3>
            <p>Näin kirjaudut sovellukseen:</p>
            <ol class="list-numbers">
                <li>Avaa sovellus ja napauta "Sign in"-painiketta.</li>
                <li>Napauta "Libraries & Groups"-painiketta.</li>
                <li>Avaa "Select Library or Group" -valikko, kirjoita hakukenttään "kyyti" ja valitse "Kyyti-libraries (Kouvola, Kotka, Iitti, Hamina)".</li>
                <li>Kirjoita "Library card number"-kenttään kirjastokortin numerosi ja "PIN"-kenttään kirjastokorttiin liitetty nelinumeroinen tunnusluku.</li>
                <li>Napauta "Sign in".</li>
                <li>Pressreader ehdottaa vielä oman tilin luomista. Ohita luominen napauttamalla rastia vasemmassa yläkulmassa.</li>
            </ol>
            <p>Laitteen pitäisi muistaa kirjautumisesi, kun avaat sovelluksen uudestaan. 
            Jos lehdet eivät kuitenkaan avaudu normaalisti, voit tarkastaa "Browse"-välilehdeltä, että kirjautumisesi on varmasti voimassa. Olet kirjautunut palveluun, jos kahvikupin kuvake on vihreä.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/kuppi.jpg')?>" width="300" alt="Kirjautumisesta kertova kahvikupin kuvake"></p>
            <p>Jos kahvikuppi on harmaa, kirjaudu uudelleen "Sign in"-painikkeesta.</p>
            
            <h3>Lehtien hakeminen</h3>
            <p>Voit selata lehtivalikoimaa napauttamalla "Browse"-painiketta.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/browse.jpg')?>" width="300" alt="Selaus-välilehden painike"></p>
            <p>Browse-välilehdellä on useita Pressreaderin valmiiksi koostamia kokoelmia, kuten suositukset (Recommended) ja luetuimmat sanomalehdet/aikakauslehdet (Top Newspapers/Magazines).</p>
            <p>Jos haluat selata vain tietyssä maassa julkaistuja tai tietyn kielisiä lehtiä, napauta sivun ylälaidassa "Countries"- tai "Languages"-painiketta</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/rajaukset.jpg')?>" width="300" alt="Maan tai kielen rajausvalikot"></p>
            <p>ja valitse maa tai kieli.</p>
            <p>Voit myös hakea lehtiä. Napauta hakukenttää sovelluksen ylälaidassa ja kirjoita esimerkiksi lehden nimi tai aihealue. 
            Alla esimerkissä on haettu sanalla "newsweek".</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/lehtihaku.jpg')?>" width="300" alt="Hakukenttä ja hakutulokset"></p>

            <p>Pääset selaamaan lehden numeroita napauttamalla lehden kansikuvaa, jolloin aukeaa lehden oma sivu.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/lehtisivu.jpg')?>" width="300" alt="Hakukenttä ja hakutulokset"></p>
            <p>Voit avata lehden napauttamalla kansikuvaa. Jos et ole langattomassa verkossa, sovellus saattaa pyytää vielä ennen lehden avaamista vahvistamaan lataamisen.</p>
            <p>Lehden aiemmat numerot ovat sivulla alempana "Latest Issues"-otsikon alla.</p>
            
            <h3>Lehden selaaminen ja artikkelien lukeminen</h3>
            <p>Lehden sivuja vaihdetaan pyyhkäisemällä vasemmalle tai oikealle.</p>
            <p>Kun haluat lukea artikkelin, napauta sen otsikkoa, niin artikkeli aukeaa koko ruudun lukunäkymään, jossa tekstiä on helpompaa lukea. 
            Pääset takaisin selausnäkymään napauttamalla vasemman yläkulman nuolipainiketta.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/lukunäkymä.jpg')?>" width="300" alt="Lukunäkymä"></p>
            <p>Voit selata lehteä nopeammin selauspalkin avulla. Jos selauspalkki ei näy, voit avata sen napauttamalla lehden sivua.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/selauspalkki.jpg')?>" width="300" alt="Selauspalkki"></p>
            <p>Sivuja selataan selauspalkissa pyyhkäisemällä vasemmalle tai oikealle ja sivu avautuu napauttamalla sen esikatselukuvaa.</p>
            <p>Napauttamalla lehteä, saat näkyviin selauspalkin lisäksi myös muita hyödyllisiä toimintoja.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/toiminnot.jpg')?>" width="300" alt="Lukunäkymän toimintopainikkeet"></p>
            <p>Voit esimerkiksi:</p>
            <ol class="list-bullets">
                <li>Kuunnella lehden koneluettuna napauttamalla kuulokkeiden kuvaketta.</li>
                <li>Avata lehden sisällysluettelon napauttamalla oikean yläkulman lista-kuvaketta.</li>
                <li>Siirtyä tiettyyn artikkeliin oikean alalaidan lista-kuvakkeesta.</li>
                <li>Merkitä lehden suosikiksi napauttamalla sydämen-kuvaketta. Suosikeiksi merkityt lehdet ilmestyvät "Browse"-välilehdelle kohtaan "My Publications".</li>
            </ol>            
        </div>
        
        <div id="profiilin_aktivointi" class="content-section">        
            <h2>Vanhojen Pressreader-profiilien aktivointi uudelleen</h2>
            <p>Jos olet aiemmin rekisteröitynyt Pressreader-palveluun sähköpostiosoitteella, sinun pitää aktivoida profiilisi uudelleen kirjautumistavan muuttumisen takia.</p>
            
            <p>Näin aktivoit profiilin uudelleen</p>
            
            <ol class="list-numbers">
                <li>Mene osoitteeseen <a href="https://www.pressreader.com" target="blank">pressreader.com</a>.</li>
                <li>Napauta "Sign in"-painiketta, syötä "email address"- ja "password"-kenttiin profiilisi sähköpostiosoite ja salasana ja napauta "Sign in"-painiketta.</li>
                <li>Napauta oikeasta yläkulmasta oman tilin -kuvaketta (harmaa ympyrä) ja valitse valikosta My Account.</li>
                <li>Napauta kirjaston nimen kohdalta "Manage"-painiketta ja valitse avautuvassa valikossa "Unlink Account".</li>
                <li>Napauta oman tilin -kuvaketta ja valitse "Sign out".</li>
                <li>Napauta ”Sign in”-painiketta.</li>
                <li>Napauta kirjautumisikkunassa “Library or Group”-painiketta.</li>
                <li>Hae ja valitse ”Kyyti-libraries (Kouvola, Kotka, Iitti, Hamina)”.</li>
                <li>Kirjoita kenttiin kirjastokortin numerosi ja korttiin liitetty nelinumeroinen tunnusluku.</li>
                <li>Hyväksy kirjautumistietojen välittäminen valitsemalla ”I agree to allowing PressReader to verify and exchange my registration with my public library”
                ja napauta ”Log In”-painiketta.</li>
            </ol>            
        </div>
    </div>
 </div>
    
<!-- END of: Content/e-lehdet_ohje_fi.phtml -->