<!-- START of: Content/e-lehdet_ohje_en-gb.phtml -->
    
<? $this->headTitle('Foreign newspapers and magazines'); $this->content()->setHeading('Reading foreign newspapers and magazines'); ?>

<div class="row">
    <div class="col-sm-12">
        <div>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/pressreader_logo.png')?>" width="300" alt="PressReader logo"></p>
            <p>Pressreader is a newspaper service that includes over 7 000 newspapers and magazines from 120 countries in 60+ languages. 
            Newspapers and magazines are available for reading for 2 months after the date of publication.</p>
        </div>
    
        <div>
            <h2>You can read newspapers and magazines both at the library or remotely</h2>
            <p>You can access the service by using library computers or your own computer or device away from the library. 
            You need your library card number and the four-number PIN code to use the service remotely.</p>
            <p><a href="https://www.pressreader.com" target="blank">Click here to use Pressreader</a></p>
        </div>
        
        <div>
            <h2>Browsing the newspaper and magazine collection</h2>
            <p>When you open Pressreader, you will be able to browse newspapers and magazines by clicking the “See All” button.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/selaa.jpg')?>" width="1200" alt="browse-button"></p>
            
            <p>You can filter the results to show only certain countries or languages.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/rajauspainikkeet.jpg')?>" width="300" alt="filtering buttons"></p>

            <p>For example, the below picture shows filter options that show all magazines that are available in English.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/englanti.jpg')?>" width="200" alt="language filtering menu"></p>

            <p>You can also search for newspapers and magazines by clicking the search button (<img src="<?=$this->imageSrc('elehtiohjeet/suurennuslasi.jpg')?>" width="20" alt="Hakupainike">) 
            located in the top right corner.</p>
        </div>
        
        <div>
            <h2>Reading newspapers and magazines</h2>
            <p>Open the next page by clicking the arrow key on the side of the screen, or by swiping left on a mobile device.</p>
            <p><img src="<?=$this->imageSrc('elehtiohjeet/selauspainike.jpg')?>" width="800" alt="Sivunvaihtopainike"></p>
            <p>Some newspapers and magazines allow you to zoom in on a story and view it in full screen mode by clicking on the headline.</p>
            <p>If you want to read older issues, navigate to the front page of the newspaper/magazine, click the calendar icon, and choose the publication date.</p>
        </div>
    </div>
 </div>
    
<!-- END of: Content/e-lehdet_ohje_en-gb.phtml -->