<!-- START of: Content/e-musiikki.fi.phtml -->

<? $this->headTitle('Musiikki'); $this->content()->setHeading('Musiikin suoratoistopalvelu Naxos'); ?>

<div class="col-sm-12">
<div id="kuuntele_musiikkia_netissa" class="content-section">


<h2>Musiikkia moneen makuun</h2>
<p class="ex">
<a target="_blank" href="https://kouvola.naxosmusiclibrary.com/page.library_cardno.asp"><img src="<?=$this->imageLink('naxmusic.jpg')?>" alt="Naxos Classic -musiikkipalvelu"/></a>
<a target="_blank" href="http://kouvola.naxosmusiclibrary.com/Jazz"><img src="<?=$this->imageLink('naxjazz.jpg')?>" class="centered" alt="Naxos Jazz -musiikkipalvelu" /></a>
<a target="_blank" href="http://kouvola.naxosmusiclibrary.com/World"><img src="<?=$this->imageLink('naxworld.jpg')?>" alt="Naxos World -musiikkipalvelu" /></a>
<!-- <a href="https://kouvola.naxosmusiclibrary.com/"  target="blank">
<img src="<?=$this->imageSrc('NML_logo.gif')?>" alt="Naxos-logo" />
</a> -->
</p>

<p class="ex">Naxoksen kolmessa kuuntelupalvelussa voit kuunnella musiikkia suoratoistona maksutta. Valikoimassa on tuhansia levyjä klassista musiikkia, maailmanmusiikkia, jazzia ja vanhempaa popmusiikkia. </p>

<p class="ex">Naxos Music Libraryssä on myös tietoa klassisen musiikin säveltäjistä ja esittäjistä, musiikkisanasto, oopperoiden librettoja ja juonikuvauksia, valmiita soittolistoja sekä materiaalia musiikkikasvatukseen.</p>

<h2>Näin aloitat kuuntelun</h2>

<p class="ex">Aloittaaksesi kuuntelun, avaa ensin haluamasi Naxoksen musiikkipalvelu</p>
<ul class="list-bullets">
    <li><a href="https://kouvola.naxosmusiclibrary.com/" target="blank">Naxos Music Library (klassinen musiikki)</a></li>
    <li><a href="http://kouvola.naxosmusiclibrary.com/Jazz" target="_blank">Naxos Jazz</a></li>
    <li><a href="http://kouvola.naxosmusiclibrary.com/World" target="_blank">Naxos World</a></li>
</ul>
<p>Syötä sitten kirjastokortin numerosi "Enter your Library Card Number"-kenttään ja napauta Login-painiketta.</p>


<p class="ex">Palvelu toimii kaksi tuntia kerrallaan. Jos haluat jatkaa kuuntelua kahden tunnin jälkeen, kirjaudu uudestaan sisään. 
Kun lopetat kuuntelun, kirjaudu ulos "Log out"-painikkeella. Palvelussa on rajattu määrä kuunteluoikeuksia ja kirjautumalla ulos vapautat oikeuden toiselle käyttäjälle.

<h2>Rekisteröitymällä voit luoda soittolistoja ja käyttää mobiilisovellusta</h2>
<p>Jos haluat tallentaa kappaleita henkilökohtaisille soittolistoille tai käyttää mobiilisovellusta, sinun pitää rekisteröityä Naxoksen palveluihin.</p>

<ol class="list-numbers">
    <li>Avaa <a href="https://kouvola.naxosmusiclibrary.com/" target="blank">Naxos Music Library</a>, <a href="http://kouvola.naxosmusiclibrary.com/Jazz" target="blank">Naxos Jazz</a> tai <a href="http://kouvola.naxosmusiclibrary.com/World" target="blank">Naxos World</a>. 
    Kuhunkin Naxoksen palveluun pitää rekisteröityä erikseen.</li>
    <li>Kirjoita Enter your Library Card Number -kenttään Kyyti-kirjastokorttisi numero ja valitse Login.</li>
    <li>Valitse Playlists-välilehti. Mobiililaitteilla playlists on menu-valikossa (kolmen viivan kuvake).</li>
    <li>Klikkaa kohdasta Student/member Account linkkiä Sign up.</li> 
    <li>Täytä lomake ja valitse Register New Account Now.</li>
    <li>Sähköpostiisi lähetetään viesti, jossa on vahvistuslinkki rekisteröitymiselle. Napauta linkkiä, niin tilisi otetaan käyttöön.</li>
</ol>

<p>Rekisteröitymisen jälkeen voit kirjautua haluamaasi palveluun antamallasi sähköpostiosoitteella ja salasanalla alla olevista osoitteista</p>
<ul class="list-bullets">   
    <li><a href="https://www.nml3.naxosmusiclibrary.com/login" target="blank">Naxos Music Library</a></li>
    <li><a href="https://www.naxosmusiclibrary.com/jazz/login?rurl=%2FJazz" target="blank">Naxos Jazz</a></li>
    <li><a href="https://www.naxosmusiclibrary.com/world/login" target="blank">Naxos World</a></li>
</ul>
    
<p>Kirjautuneena voit tallentaa henkilökohtaisia soittolistoja ja selata niitä Playlists-välilehdeltä.</p>
<p>Rekisteröitymisen jälkeen voit myös kuunnella musiikkia mobiilisovelluksella. Voit ladata sovelluksen Applen laitteille App Storesta tai Android-laitteille Googlen Play-kaupasta. 
Jokaiselle Naxoksen palvelulle (Music Library, Jazz, World) on oma sovelluksensa.</p>
<p>Mobiilisovellukseen kirjaudutaan rekisteröityessä antamallasi sähköpostiosoitteella ja salasanalla.</p>

</div>
</div>
</div>
   
<!-- END of: Content/e-musiikki.fi.phtml -->