<? $this->headTitle('E-aineistot'); $this->content()->setHeading('E-aineistot'); ?>

<div class="row">
    <div class="col-sm-4">
        <div class="infobox">
           <p><img src="<?=$this->imageSrc('/eaineistot/ekirjat2.jpg')?>" alt="Ekirjan lukeminen tabletilla"></p> 
           <div class="w2-small">
                <h2>E-kirjat ja e-äänikirjat</h2>
            </div>

            <p>Kirjaston kokoelmissa on monipuolinen valikoima e-kirjoja ja e-äänikirjoja kaikenikäisille.</p>

            <p class="kyyti-badge-container">
                Voit lukea ja kuunnella kirjoja lataamalla E-kirjasto-sovelluksen mobiililaitteellesi Googlen tai Applen sovelluskaupasta:
                <br>
                <a href="https://play.google.com/store/apps/details?id=fi.kansalliskirjasto.ekirjasto">
                <img class="kyyti-badge" src="<?=$this->imageSrc('sovellukset/google-play-badge_fi.png')?>" alt="Lataa Googlen Play-kaupasta"></a>
                <a href="https://apps.apple.com/fi/app/e-kirjasto/id6471490203?l=fi">
                <img class="kyyti-badge" src="<?=$this->imageSrc('sovellukset/app-store-badge-black_fi.svg')?>" alt="Lataa Applen App Storesta"></a>
            </p>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="infobox">
            <p><img src="<?=$this->imageSrc('/eaineistot/kotimaiset_aikakauslehdet3.jpg')?>" alt=""></p>
            <div class="w2-small">
                <h2>Etäkäyttöiset kotimaiset aikakauslehdet</h2>
            </div>
            <p>Yli 80 kotimaisen aikakauslehden numerot viimeisen vuoden ajalta. Etäkäyttöisiä lehtiä voit lukea missä tahansa omalla mobiililaitteella.</p>
            <p class="kyyti-badge-container">
                Lehtien lukemiseen tarvitset E-kirjasto-sovelluksen, jonka voit ladata Googlen tai Applen sovelluskaupasta:
                <br>
                <a href="https://play.google.com/store/apps/details?id=fi.kansalliskirjasto.ekirjasto">
                <img class="kyyti-badge" src="<?=$this->imageSrc('sovellukset/google-play-badge_fi.png')?>" alt="Lataa Googlen Play-kaupasta"></a>
                <a href="https://apps.apple.com/fi/app/e-kirjasto/id6471490203?l=fi">
                <img class="kyyti-badge" src="<?=$this->imageSrc('sovellukset/app-store-badge-black_fi.svg')?>" alt="Lataa Applen App Storesta"></a>
            </p>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="infobox">
            <p><img src="<?=$this->imageSrc('/eaineistot/kotimaiset_aikakauslehdet_lahi.jpg')?>" alt=""></p>
            <div class="w2-small">
                <h2>Kirjastossa luettavat kotimaiset aikakauslehdet</h2>
            </div>
            <p>Noin 20 kotimaisen aikakauslehden numerot viimeisen vuoden ajalta.</p>
            <p>Voit lukea lehtiä kirjaston tietokoneilla tai kirjautumalla kirjaston langattomaan verkkoon.</p>
            <br>
            <div class="elinkit">
                <a class="btn-primary" href="https://kyyti.emagz.fi"><i aria-hidden="true" class="fa fa-arrow-circle-right" style="padding-right: 10px;"></i><span>EMAGZ-LEHTIPALVELU</span></a>
            </div>
        </div>
    </div>
</div>
    
<div class="row">
    <div class="col-sm-4">
        <div class="infobox">
            <p><img src="<?=$this->imageSrc('/eaineistot/kotimaiset_sanomalehdet3.jpg')?>" alt=""></p>
         
            <div class="w2-small">        
                <h2>Kotimaiset sanomalehdet</h2>
            </div>
                
            <p>Yli 200 kotimaisen sanomalehden numerot viimeisen vuoden ajalta.</p>
            <p>Voit lukea lehtiä kirjaston tietokoneilla tai kirjautumalla kirjaston langattomaan verkkoon.</p>
            <br>
        
            <div class="elinkit">
                <a class="btn-primary" href="https://www.epress.fi"><i aria-hidden="true" class="fa fa-arrow-circle-right" style="padding-right: 10px;"></i><span>EPRESS-LEHTIPALVELU</span></a>
            </div>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="infobox">
          <p><img src="<?=$this->imageSrc('/eaineistot/ulkomaiset_sanomalehdet2.jpg')?>" alt=""></p>   
           
           <div class="w2-small">
                <h2>Ulkomaiset sanoma- ja aikakauslehdet</h2>  
           </div>
           
           <p>7 000 sanoma- ja aikakauslehteä 120 maasta 60 kielellä.</p>
           
           <p>Voit lukea lehtiä joko etänä tai kirjastossa. Etäkäyttöön tarvitset kirjastokortin numeron ja tunnusluvun.</p>
    
           <a href="<?=$this->url('content-page',  ['page' => 'e-lehdet_ohje'])?>"><b style="color: #007091;">Käyttöohjeet</b></a>
           <br>
           <br>
           <div class="elinkit">
                <a class="btn-primary" href="https://www.pressreader.com"><i aria-hidden="true" class="fa fa-arrow-circle-right" style="padding-right: 10px;"></i><span>PRESSREADER-LEHTIPALVELU</span></a>
            </div>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="infobox">
            <p><img src="<?=$this->imageSrc('/eaineistot/cineast.jpg')?>" alt=""></p>   
            <div class="w2-small">
                <h2>Elokuvien suoratoisto</h2>  
            </div>
           
            <p>Cineast-elokuvapalvelussa voit katsoa ilmaiseksi kuusi elokuvaa kuukaudessa.</p>
            
            <p>Elokuvavalikoima päivittyy koko ajan.</p>
    
            <p>Katsomiseen tarvitset kirjastokortin numeron ja tunnusluvun.</p>
    
            <br>
            <div class="elinkit">
                <a class="btn-primary" href="https://www.cineast.fi"><i aria-hidden="true" class="fa fa-arrow-circle-right" style="padding-right: 10px;"></i><span>CINEAST-ELOKUVAPALVELU</span></a>
            </div>
        </div>
    </div>
</div>

<div class="row"> 
    <div class="col-sm-4">
        <div class="infobox">
            <p><img src="<?=$this->imageSrc('/eaineistot/musiikin_suoratoisto4.jpg')?>" alt=""></p>   
            <div class="w2-small">
                <h2>Musiikin suoratoisto</h2>
            </div>
            <p>Klassista, jazzia ja maailmanmusiikkia.</p> 
            <p>Kuunteluun tarvitset kirjastokortin numeron.</p>
            <a href="<?=$this->url('content-page',  ['page' => 'e-musiikki'])?>"><b style="color: #007091;">Käyttöohjeet</b></a>
            <br>
            <br>
            <div class="elinkit">
                <a class="btn-primary" href="https://kouvola.naxosmusiclibrary.com"><i aria-hidden="true" class="fa fa-arrow-circle-right" style="padding-right: 10px;"></i><span>NAXOS (KLASSINEN)</span></a>
                <br>
                <a class="btn-primary" href="https://kouvola.naxosmusiclibrary.com/jazz"><i aria-hidden="true" class="fa fa-arrow-circle-right" style="padding-right: 10px;"></i><span>NAXOS (JAZZ)</span></a>
                <br>
                <a class="btn-primary" href="https://kouvola.naxosmusiclibrary.com/world"><i aria-hidden="true" class="fa fa-arrow-circle-right" style="padding-right: 10px;"></i><span>NAXOS (WORLD)</span></a>
            </div>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="infobox">
            <p><img src="<?=$this->imageSrc('/eaineistot/celia.jpg')?>" alt=""></p>   
            <div class="w2-small">
                <h2>Äänikirjat lukemisesteisille</h2>
            </div>
            <p>Celian äänikirjoja voivat käyttää kaikki, joille tavallisen kirjan lukeminen on lukivaikeuden, sairauden, vamman tai vastaavan syyn vuoksi vaikeaa.</p> 
            
            <p>Celian käyttäjäksi voit liittyä kirjastossa.</p> 
            <br>
            <strong><a href="https://www.celia.fi/tietoa-celiasta/" target="_blank" style="color: #007091;">Tietoa äänikirjoista Celian verkkosivuilla</a></strong>
            <br>
            <br>
            <strong><a href="https://kyyti.finna.fi/Content/esteeton_kirjasto#celia" style="color: #007091;">Celiaan liittyminen Kyyti-kirjastoissa</a></strong>
            <br>
            <br>
        </div>
    </div>
</div>

<div class="row">
 <div class="col-xs-12">
        <div class="infobox">
            <div class="infobox_b">
            <h2>Aineistoja verkossa</h2>
             
            <div class="row">
                    <!--Taulukon ensimmäinen sarake--> 
                    <div class="col-md-4">
                      <strong><a href="https://www.kirjavinkit.fi/" target="_blank">Kirjavinkit</a></strong>
                      <p>Yli 6 000 laadukasta kirja-arvostelua.</p>
                      <br>
                      <strong><a href="http://kirjasampo.fi" target="_blank">Kirjasampo</a></strong>
                      <p>Kiinnostavia kirjailijoita, kirjoja ja uusia lukukokemuksia.</p>
                      <br>
                      <strong><a href="https://www.kirjastokaista.fi/kirjailijahaastattelut-ja-lukuvinkit/" target="_blank">Kirjastokaistan kirjallisuusohjelmat</a></strong>
                      <p>Videoituja kirjailijahaastatteluita ja kirjavinkkejä.</p>
                      <br>
                      <strong><a href="https://klassikkokirjasto.kansalliskirjasto.fi/" target="_blank">Klassikkokirjasto</a></strong>
                      <p>Kotimaisia klassikoita e-kirjoina.</p>
                      <br>
                      <strong><a href="https://librivox.org/" target="_blank">Librivox</a></strong>
                      <p>Yli 30 000 vapaaehtoisten lukemaa tekijänoikeusvapaata e-äänikirjaa. Suurin osa kirjoista englanninkielisiä.</p>
                      <br>
                      <strong><a href="https://www.gutenberg.org/" target="_blank">Project Gutenberg</a></strong>
                      <p>Yli 60 000 vanhempaa kirjaa e-kirjoina. Myös kotimaisia klassikoita.</p>
                    </div>
                    
                    <!--Taulukon toinen sarake-->                    
                    <div class="col-md-4">
                      <strong><a href="https://areena.yle.fi/audio/ohjelmat/30-272" target="_blank">Yle Areenan äänikirjat</a></strong>
                      <p>Ammattilaisten suomeksi lukemia äänikirjoja.</p>
                      <br>
                      <strong><a href="https://elonet.finna.fi/" target="_blank">Elonet</a></strong>
                      <p>Suomalainen elokuvatietokanta, jossa on katsottavissa yli 200 kotimaista elokuvaa ja lähes kaksituhatta muuta filmiä.</p>
                      <br>
                      <strong><a href="https://www.finna.fi/" target="_blank">Finna.fi</a></strong>
                      <p>Suomen arkistojen, kirjastojen ja museoiden aarteet samalla haulla.</p>
                      <br>
                      <strong><a href="https://digi.kansalliskirjasto.fi/serial-publications?generalTypes=NEWSPAPER&generalTypes=JOURNAL" target="_blank">Kansalliskirjaston digitoidut sanoma- ja aikakauslehdet</a></strong>
                      <p>Suomessa julkaistuja sanoma- ja aikakauslehtiä 1700-luvulta vuoteen 1939. Myös Käkisalmen ja Laatokan alueen sanomalehtiä.</p>
                      <br>
                      <strong><a href="https://yle.fi/aihe/oppiminen/kielet" target="_blank">Ylen kielikurssit</a></strong>
                      <p>Videokielikursseja erityisesti kielen opiskelua aloittaville.</p> 
                    </div>
                    
                    <!--Taulukon kolmas sarake-->                     
                    <div class="col-md-4">
                      <strong><a href="https://www.sotasampo.fi/fi/" target="_blank">Sotasampo</a></strong>
                      <p>Etsi talvi- ja jatkosotaan osallistuneiden sukulaistesi tietoja ja seuraa heidän sotataivaltaan kartalla.</p> 
                    <br>
                      <strong><a href="https://astia.narc.fi/uusiastia/" target="_blank">Kansallisarkiston digitoidut asiakirjat</a></strong>
                      <p>Astia-palvelussa voit hakea Kansallisarkiston digitoituja aineistoja, kuten kirkonkirjoja ja sotien asiakirjoja.</p>
                    <br>
                      <strong><a href="https://digihakemisto.net/" target="_blank">Digihakemisto</a></strong>
                      <p>Hakemisto Kansallisarkiston digitoituihin sukututkimusaiheisiin asiakirjoihin.</p> 
                    </div>
        </div>
    </div>
</div>
</div>
</div>
