<!-- START of: finna - content/help_en-gb.phtml -->
<? $this->headTitle('Search Help'); $this->content()->setHeading('Search Help'); ?>

<div class="row">
  <div class="col-sm-3 sidebar">
    <div class="content-navigation-menu">
    </div>
  </div>
  <div class="col-sm-9">
    <? if ($this->resolver('Content/Additions/helpBegin_en-gb.phtml')): ?>
    <?=$this->render('Content/Additions/helpBegin_en-gb.phtml')?>
    <? endif; ?>
    <div id="basicsearch" class="content-section">
      <h2 title="Basic Search"><i class="fa fa-search"></i> Basic search</h2>
      <p>If search words are separated only by spaces, the search results are the same as when using the AND operator, i.e., the search results contain all the search words you have entered. </p>
      <p>For example, <em>mannerheim carl</em> produces the same search results as <em>mannerheim AND carl. </em></p>
          </div>
    <div id="narrowsearch" class="content-section">
      <h2>Narrowing the search</h2>
      <p>You can use the <strong>Narrow Search</strong> menu to narrow your search 
      according to format (e.g., image), organisation (e.g., National Archives) 
      or language. You can specify the year(s) of production by entering a range 
      of years or using the visual timeline tool. Search results can be narrowed 
      by selecting several criteria at the same time. By clicking on the arrow, 
      you can display the locations or formats (e.g., compilation, archive series, DVD) 
      of a lower hierarchical level. By default, the menu displays the most relevant 
      search results at the top.</p>
     
      <p>You can see and delete criteria under the <strong>Narrow Search</strong> menu.</p>   
      <p>If you wish to carry out a new search applying the same criteria, 
      enable the function "Retain filters". </p>
    </div>
    <div id="advancedsearch" class="content-section">
      <h2><i class="fa fa-search-adv"></i> Advanced search</h2>
      <h4>Search fields</h4>
      <p>The Advanced Search page has several search fields in which you can enter search terms and phrases, and use various search operators. </p>
      <p>Adjacent to each search field is a drop-down menu, from which you can select the field of the relevant record (all fields, title, author, etc.). If necessary, you can target a search to several fields by using several search terms. </p>
      <h4>Match drop-down</h4>
      <p>he match dropdown defines how to handle a query with several search fields: </p>
            <ul class="list-bullets">
        <li><strong>ALL Terms (AND)</strong> – Searches for records that match the content of all search fields. 
        </li>
        <li><strong>ANY Terms (OR)</strong> – Searches for records that match the content of one or more search fields. </li>
        <li><strong>NO Terms (NOT)</strong> – Searches for records which do not feature the content of any of the search fields.</li>
      </ul>
      <p><strong>Add Search Field</strong> allows you to add a new search field to the form.</p>
     <h4>Search Groups</h4>
            <ul class="list-bullets">
        <li><strong>Add Search Group</strong> allows you to add search fields for a new group.</li>
        <li><strong>Remove Search Group</strong> allows you to delete groups.</li>
      <li>To define the relationships between search groups, use the <strong>ALL Groups (AND)</strong> and <strong>ANY Groups (OR)</strong> search operators. </li>
      </ul>
      
      <h4>Example</h4>
      <p>If you wish to search information about the history of India and China, you 
      can use search groups as follows: 
            <ul class="list-bullets">
        <li>Add the terms “India” and “China” to the search fields of the first search group</li>
        <li>Define the relationship between the search fields by selecting <strong>ANY Terms (OR)</strong> from the <strong>Match</strong> drop-down menu.</li>
        <li>Create a new search group and add the term “history” to its search field. </li>
        <li>Define the relationship between search groups as <strong>ALL Groups (AND).</strong></li>
      </ul>
    </div>

    <div id="booleanoperators" class="content-section"><h2>Logical search operators</h2>
      <p>You can combine terms into complex queries with Boolean operators. The following operators can be used: <strong>AND</strong>, <strong>+</strong>, <strong>OR</strong>,<strong> NOT</strong>, and <strong>-</strong>. </p>
      <p><strong>NB!</strong> Boolean operators must be typed in CAPITAL LETTERS.</p>
      <h4 title="AND">AND</h4>
      <p><strong>AND</strong>, the conjunction operator, is the system’s default operator for multi-term queries that do not include an operator. When using the <strong>AND</strong> operator, the records included in the search results feature each of the terms in the search fields. </p>
      <p>For example, to search for records that include “economics” and “Keynes”: </p>
      <pre class="code">economics Keynes</pre>
      <p>or</p>
      <pre class="code">economics AND Keynes</pre>
      <h4 title="+">+</h4>
      <p><strong>AND</strong>, the conjunction operator, is the system’s default operator for multi-term queries that do not include an operator. When using the <strong>AND</strong> operator, the records included in the search results feature each of the terms in the search fields. </p>
      <p>For example, to search for records that include “economics” and “Keynes”: </p>
      <pre class="code">+economics Keynes</pre>
      <h4 title="OR">OR</h4>
      <p>The + sign can be used to indicate that the term must appear in each search result.  </p>
      <p>For example, to search for records that must include “economics” and may include “Keynes”: </p>
      <pre class="code">"economics Keynes" OR Keynes</pre>
      <h3 title="!-">!-</h3>
      <p>The "!-" operator excludes records that contain the following term.</p>
      <p>To search for documents that contain "economics" but not "Keynes" use the query:</p>
      <pre class="code">economics !-Keynes</pre>
      <p>Note: The operator cannot be used with just one term. For example, the following search will return no results:</p>
      <pre class="code">!-economics</pre>
      <p>Note: If the term begins with the operator, it can be included by using the backslash (\). For example: to search for <i>!-merkki hakuehtona</i> (in Finnish) use the query:</p>
      <pre class="code">\!-merkki hakuehtona</pre>
      <p>Note: The <strong>NOT</strong> operator can be used similarly with this operator. However, the <strong>NOT</strong> operator returns more results, some of which may contain the term following <strong>NOT</strong>.</p>
      <h3 title="Phrase searches">Phrase searches</h3>
      <p>You can search for an exact phrase by writing your search terms within quotation marks.</p>
      <p> For example, to search only for records which include the phrase “mediaeval history”, not “mediaeval cultural history” or similar phrases: </p>
      <pre class="code">"keskiajan historia"</pre>
      <p>Phrase search can also be used for single word. Search is then exact match of a search word without any other conjugations.</p>
    </div>
      
    <div id="wildcardsearches" class="content-section"><h2>Wildcard characters</h2>
      <p><strong class="helpTerm">?</strong> korvaa yhden merkin hakutermistä.</p>
      <p>For example, the terms “text” and “test” can be searched for using the same query:</p>
      <pre class="code">te?t</pre>
      <p><strong class="helpTerm">*</strong> replaces one character in a search term.</p>
      <p>For example, the terms “test”, “tests” and “tester” can be searched for using the query:</p>
      <pre class="code">test*</pre>
      <p>Jokerimerkkejä voi käyttää myös hakutermin keskellä:</p>
      <pre class="code">te*t</pre>
      <p>NB! The wildcards ? and * cannot replace the first character in a search term. </p>
    </div>   
    <div id="fuzzysearches"  class="content-section"><h2>Fuzzy searches</h2>
      <p>A fuzzy search generates results in which words similar to the actual search word also appear. </p>
      <p>~ carries out a fuzzy search when used as the last character in a single-term search. </p>
      <p>For example, a fuzzy search for the term “roam”:</p>
      <pre class="code">roam~</pre>
      <p>This search finds such terms as “foam” and “roams”. The similarity of the search to the original term can be regulated with a parameter between zero and one. </p>
      <p>The closer the value is to one, the more similar the term will be to the original term.  roam~0.8</p>
      <pre class="code">roam~0.8</pre>
      <p>The default value of the parameter is 0.5 if it is not separately defined for a fuzzy search. </p>
    </div>
  
    <div id="proxitimitysearches" class="content-section"><h2>Proximity searches</h2>
      <p>Proximity searches look for documents in which the search terms are within a specified distance, but not necessarily one after the other.  </p>
      <p>~ performs a proximity search at the end of a multi-term search phrase when combined with a proximity value.  </p>
      <p>For example, to search for the terms “economics” and “Keynes” when they appear within a distance of no more than ten terms from each other: </p>   
      <pre class="code">"economics Keynes"~10</pre>
    </div>
    
    <div id="rangesearches"class="content-section"><h2>Range searches</h2>
      <p>Range searches can be conducted using either curvy brackets { } or square brackets [ ]. When using curvy brackets, the search takes into account only the values between the terms entered, excluding the terms itself. Square brackets, in contrast, also include the terms entered in the range searched for.  </p>
      <p>For example, to search for a term that begins with the letter B or C using the query: </p>
      <pre class="code">{A TO D}</pre>
      <p>For example, to search for the values 2002–2003: </p>
      <pre class="code">[2002 TO 2003]</pre>
      <p>NB! The word TO between the values must be typed in CAPITAL LETTERS.</p>
    </div>
  
    <div id="boostingaterm" class="content-section"><h2>Weighted search terms</h2>
      <p>^ assigns a weight to the search term in a query.</p>
      <p>For example, to assign added weight to the search term “Keynes”:</p>
      <pre class="code">economics Keynes^5</pre>
    </div>
    <? if ($this->resolver('Content/Additions/helpEnd_en-gb.phtml')): ?>
      <?=$this->render('Content/Additions/helpEnd_en-gb.phtml')?>
    <? endif; ?>
  </div>
</div>
<!-- END of: finna - content/help_en-gb.phtml -->
