<!-- START of: finna - content/help_fi.phtml -->
<? $this->headTitle('Tiedonhaun ohjeita'); $this->content()->setHeading('Tiedonhaun ohjeita'); ?>

<div class="row">
  <div class="col-sm-3 sidebar">
    <div class="content-navigation-menu">
    </div>
  </div>
  <div class="col-sm-9">
    <? if ($this->resolver('Content/Additions/helpBegin.phtml')): ?>
      <?=$this->render('Content/Additions/helpBegin.phtml')?>
    <? endif; ?>
    <div id="basicsearch" class="content-section">
      <h2><i class="fa fa-search"></i> Perushaku</h2>
      <p>Pelkällä välilyönnillä erotetut hakusanat käyttäytyvät AND-hakulogiikalla eli hakutuloksien tulee sisältää kaikki antamasi hakusanat.</p><p>Esimerkiksi <i>mannerheim carl</i> on sama haku kuin <i>mannerheim AND carl</i>.</p>
    </div>
    <div id="narrowsearch" class="content-section">
      <h2>Haun rajaaminen</h2>
      <p>Haun jälkeen voit rajata hakutuloksia aineistotyypin (esim. video), kirjaston 
      (esim. Haminan pääkirjasto) tai vaikka kielen mukaan. 
      Voit rajata julkaisuvuosia joko kirjoittamalla tietyt vuosivälit, joille haku 
      kohdistuu, tai käyttämällä aikajanatyökalua. Voit myös käyttää useita rajauksia.
      Nuolta klikkaamalla saat näkyville alemman hierarkiatason rajauksia. 
      (esim. CD, äänilevy). Eniten hakutuloksia keränneet hakuarvot näkyvät ylimmäisinä.</p>
      <p>Tekemäsi rajaukset näkyvät Rajaa hakua -otsikon alla ja voit poistaa ne klikkaamalla 
      rajauksen nimeä tai rastia. </p>
      
      <p>Jos haluat tehdä uuden haun ja säilyttää aiemmat rajaukset, rastita hakulaatikon alta "Säilytä käytössä oleva rajaus".</p>
    </div>
    <div id="advancedsearch" class="content-section">
      <h2><i class="fa fa-search-adv"></i> Tarkennettu haku</h2>
      <h4>Hakukentät</h4>
      <p>Tarkennetun haun sivulla on useita hakukenttiä, joihin voi kirjoittaa hakutermejä ja –lausekkeita sekä hakuoperaattoreita.</p>
      <p>Jokaisen hakukentän vieressä on alasvetovalikko, josta voi valita, mihin tietueen kenttään haku kohdistetaan (kaikki kentät, otsikko, tekijä, ym.). Useita termejä yhdistelevän haun voi tarvittaessa kohdistaa useampaan kenttään.</p>
      <h4>Hae-valikko</h4>
      <p>Hae-valikko määrittelee, miten useita hakukenttiä sisältävä kysely käsitellään: </p>
      <ul class="list-bullets">
        <li>
        <strong>Kaikilla termeillä (AND)</strong> — Tuottaa tulokseksi tietueet, jotka täsmäävät kaikkien hakukenttien sisältöön.
        </li>
        <li>
        <strong>Millä tahansa termillä (OR)</strong> — Tuottaa tulokseksi tietueet, jotka täsmäävät yhden tai useamman hakukentän sisältöön. 
        </li>
        <li>
        <strong>Ei millään termeistä (NOT)</strong> — Tuottaa tulokseksi tietueet, joissa ei esiinny yhdenkään hakukentän sisältöä. 
        </li>
      </ul>
      <h4>Hakuryhmät</h4>
      <ul class="list-bullets">
        <li><strong>Lisää hakuryhmä</strong> –painike lisää uuden ryhmän hakukenttiä.</li>
        <li><strong>Poista hakuryhmä</strong> –painikkeella ryhmiä voidaan poistaa.</li>
      <li>Hakuryhmien välisiä suhteita määritellään käyttäen <strong>Kaikki ryhmät (AND)</strong> ja <strong>Mikä tahansa ryhmä (OR)</strong> –hakuoperaattoreita. </li>
      </ul>
      
      <h4>Esimerkki tarkennetusta hausta</h4>
    <p>Jos haluaa hakea teoksia Intian tai Kiinan historiasta, voi haun toteuttaa 
    hakuryhmien avulla seuraavasti:</p>
        <ul class="list-bullets">
        <li>Ensimmäisen hakuryhmän hakukenttiin lisätään termit "Intia" ja "Kiina".</li>
        <li>Määritellään hakukenttien välinen suhde <strong>Hae</strong>-alasvetovalikosta <strong>Millä tahansa termillä (OR).</strong></li>
        <li>Luodaan uusi hakuryhmä ja lisätään sen hakukenttään termi "historia".</li>
        <li>Hakuryhmien väliseksi suhteeksi määritellään <strong>Kaikki ryhmät (AND).</strong></li>
      </ul>
    </div>
    <div id="booleanoperators" class="content-section"><h2>Loogiset hakuoperaattorit</h2>
      <p>Termejä voi yhdistellä monimutkaisemmiksi kyselyiksi Boolen hakuoperaattoreilla. Seuraavat operaattorit ovat käytettävissä: <strong>AND</strong>, <strong>+</strong>, <strong>OR</strong>, <strong>NOT</strong> ja <strong>-</strong>.</p>
      <p><strong>Huomio!</strong> Boolen hakuoperaattorit hauissa kirjoitetaan ISOIN KIRJAIMIN.</p>
      <h4 title="AND">AND</h4>
      <p><strong>AND</strong> eli konjunktio-operaattori on järjestelmän oletusarvoinen operaattori monitermisille kyselyille, joihin ei ole sisällytetty mitään operaattoria. <strong>AND</strong>-operaattoria käytettäessä kyselyn tuloksena saadaan tietueet, joissa esiintyy kukin hakukentissä esiintyvistä termeistä.</p>
      <p>Esimerkki: etsitään tietueita, joissa esiintyy sekä "economics" että "Keynes":</p>
      <pre class="code">economics Keynes</pre>
      <p>tai</p>
      <pre class="code">economics AND Keynes</pre>
      <h4 title="+">+</h4>
      <p>Merkillä <strong>+</strong> voidaan ilmaista vaatimusta siitä, että termin on esiinnyttävä jokaisessa hakutuloksessa.</p>
      <p>Esimerkki: etsitään tietueita, joissa esiintyy ehdottomasti "economics" ja joissa voi lisäksi esiintyä "Keynes":</p>
      <pre class="code">+economics Keynes</pre>
      <h4 title="OR">OR</h4>
      <p><strong>OR</strong>-operaattorin käyttö haussa tuottaa tulokseksi tietueita, joissa esiintyy yksi tai useampi operaattorin yhdistämistä termeistä.</p>
      <p>Esimerkki: etsitään tietueita, joissa esiintyy joko "economics Keynes" tai ainoastaan "Keynes":</p>
      <pre class="code">"economics Keynes" OR Keynes</pre>
      <h4 title="!-">!-</h4>
      <p>Merkkiyhdistelmällä <strong>!-</strong> voidaan poistaa hakutuloksista tietueet, joissa esiintyy kyselyssä merkkiä seuraava termi.</p>
      <p>Esimerkki: etsitään tietueita, joissa on termi "economics" mutta ei termiä "Keynes":</p>
      <pre class="code">economics !-Keynes</pre>
      <p>Huomio! Merkkiyhdistelmää ei voi käyttää yksitermisissä kyselyissä.</p>
      <p>Esimerkki: seuraava kysely ei tuota lainkaan tuloksia:</p>
      <pre class="code">!-economics</pre>
      <p>Huomio! Jos jokin hakutermeistä alkaa tällä merkkiyhdistelmällä, saadaan se otettua mukaan kyselyyn käyttämällä kenoviivaa (\).</p>
      <p>Esimerkki: etsitään hakusanoilla <i>!-merkki hakuehtona</i>:</p><p>
      </p><pre class="code">\!-merkki hakuehtona</pre>
      <p>Huomio! <strong>NOT</strong>-operaattoria voidaan käyttää samaan tapaan tämän merkkiyhdistelmän kanssa. <strong>NOT</strong>-operaattori antaa kuitenkin yhdysmerkkiä enemmän hakutuloksia, joissa osassa saattaa esiintyä pois suljettava hakutermi.
      </p>
      <h4 title="Phrase searches">Fraasihaut</h4>
      <p>Tarkan fraasihaun voi tehdä kirjoittamalla hakusanat lainausmerkkeihin.</p>
      <p>Esimerkki: etsitään vain tietueita, joissa on termi "keskiajan historia", ei esimerkiksi "keskiajan kulttuurihistoria":
      </p>
      <pre class="code">"keskiajan historia"</pre>
      <p>Fraasihakua voi käyttää myös yksittäisen hakusanan kohdalla, jolloin haku kohdistuu vain annettuun hakusanaan, eikä esimerkiksi muihin taivutusmuotoihin.</p>
    </div>
      
    <div id="wildcardsearches" class="content-section"><h2>Jokerimerkit</h2>
      <p><strong class="helpTerm">?</strong> korvaa yhden merkin hakutermistä.</p>
      <p>Esimerkki: termejä "text" ja "test" voidaan hakea samalla kyselyllä:</p>
      <pre class="code">te?t</pre>
      <p><strong class="helpTerm">*</strong> korvaa 0, 1 tai useampia merkkejä hakutermistä.</p>
      <p>Esimerkki: termejä "test", "tests" ja "tester" voidaan hakea kyselyllä:</p>
      <pre class="code">test*</pre>
      <p>Jokerimerkkejä voi käyttää myös hakutermin keskellä:</p>
      <pre class="code">te*t</pre>
      <p>Huomio! Jokerimerkkejä <strong>?</strong> ja <strong>*</strong> ei voi käyttää hakutermin ensimmäisenä merkkinä.</p>
    </div>  
    <div id="fuzzysearches"  class="content-section"><h2>Sumeat haut</h2>
      <p>Sumea haku hakee myös sellaisia tuloksia, joissa on mainittu hakusanan kaltainen sana.</p>
      <p><strong class="helpTerm">~</strong> toteuttaa sumean haun yksisanaisen haun viimeisenä merkkinä.</p>
      <p>Esimerkki: sumea haku termille "roam":</p>
      <pre class="code">roam~</pre>
      <p>Tämä haku löytää esimerkiksi termit "foam" ja "roams".</p>
      <p>Haun samankaltaisuutta kantatermiin voidaan säädellä parametrilla, jonka arvo on välillä 0 ja 1. Mitä lähempänä annettu arvo on lukua 1, sen samankaltaisempi termin on oltava kantatermin kanssa.</p>
      <pre class="code">roam~0.8</pre>
      <p>Oletusarvona parametrille on 0.5, jos arvoa ei sumeassa haussa erikseen määritetä.</p>
    </div>
  
    <div id="proxitimitysearches" class="content-section"><h2>Etäisyyshaut</h2>
      <p>Etäisyyshaulla saadaan tuloksia, joissa hakusanat ovat lähekkäin mutta niiden ei tarvitse olla välttämättä peräkkäin.</p>
      <p><strong class="helpTerm">~</strong> toteuttaa etäisyyshaun monitermisen hakulausekkeen lopussa etäisyysarvon kanssa.</p>
      <p>Esimerkki: etsitään termejä "economics" ja "keynes" niiden esiintyessä korkeintaan 10 termin etäisyydellä toisistaan:</p>   
      <pre class="code">"economics Keynes"~10</pre>
    </div>
    <div id="rangesearches" class="content-section"><h2>Arvovälihaut</h2>
      <p>Arvovälihaut tehdään käyttämällä joko aaltosulkeita <strong>{ }</strong> tai hakasulkeita <strong>[ ]</strong>. Aaltosulkeita käytettäessä huomioidaan vain arvot annettujen termien välillä pois lukien kyseiset termit. Hakasulkeet puolestaan sisällyttävät myös annetut termit etsittävälle arvovälille.</p>
      <p>Esimerkki: etsittäessä termiä, joka alkaa kirjaimella B tai C, voidaan käyttää kyselyä:</p>
      <pre class="code">{A TO D}</pre>
      <p>Esimerkki: etsittäessä arvoja 2002—2003 voidaan haku tehdä seuraavasti:</p>
      <pre class="code">[2002 TO 2003]</pre>
      <p>Huomio! Sana TO arvojen välillä kirjoitetaan ISOIN KIRJAIMIN.</p>
    </div>
  
    <div id="boostingaterm" class="content-section"><h2>Termin painottaminen</h2>
      <p><strong class="helpTerm">^</strong> nostaa termin painoarvoa kyselyssä.</p>
      <p>Esimerkki: haussa termin "Keynes" painoarvoa on nostettu:</p>
      <pre class="code">economics Keynes^5</pre>
    </div>
    <? if ($this->resolver('Content/Additions/helpEnd.phtml')): ?>
      <?=$this->render('Content/Additions/helpEnd.phtml')?>
    <? endif; ?>
  </div>
</div>
<!-- END of: finna - content/help_fi.phtml -->
