<!-- START of: Content/kaukolainat_fi.phtml -->

<? $this->headTitle('Kaukolainat'); $this->content()->setHeading('Kaukolainat'); ?>

<div class="row">
    <div class="col-sm-12">
        <p><img src="<?=$this->imageSrc('palvelut/kaukolainat_banneri.jpg')?>" alt="Kirjoja kirjaston hyllyssä" /></p>
        <h2>Tilaa kaukolaina</h2>
        <p>Jos etsimääsi teosta ei ole saatavana Kyyti-kirjastoista, voit tilata sen kaukolainaksi muista Suomen kirjastoista tai ulkomailta. </p>
        
        <p><a href="https://kyyti.finna.fi/Feedback/Form/Kaukolainatilaukset" target="_blank">Tilaa kaukolaina</a></p>
        <p>Voit tilata kaukolainan myös sähköpostilla, puhelimitse tai kirjastossa.</p>
        <p>Kaukolainat ovat maksullisia. <a href="<?=$this->url('content-page',  ['page' => 'maksut'])?>">Tarkasta kuntasi tilausmaksut hinnastosta</a>.</p>
        <p>Kun kaukolaina on noudettavissa, saat ilmoituksen sähköpostilla tai tekstiviestillä. Palauta kaukolainat samaan kirjastoon, josta noudit ne.</p>
        <p>Kaukolainojen tiedot eivät näy Kyyti-verkkokirjaston lainoissa, eikä niitä voi uusia itse. 
        Voit pyytää kaukolainan uusintaa sähköpostilla tai puhelimella siitä kirjastosta, josta tilasit kaukolainan.</p>

        <h2>Varastokirjastosta tilaaminen</h2>
        <p>Voit myös hakea ja tilata kaukolainaksi Varastokirjaston aineistoja suoraan Kyytin verkkokirjastosta. 
        <a href="https://kyyti.finna.fi/Content/ohje#varastokirjastotilaus" target="_blank">Lue tarkemmat ohjeet Varastokirjastosta tilaamiseen</a>.</p>

        <h2>Kaukopalvelu kirjastoille</h2>
        <p>Kyyti-kirjastot lähettävät muille kirjastoille kaukolainoja. Kaukolaina tilataan siitä kirjastosta, 
        jossa aineisto on.</p>
        
        <p>Yhteystiedot:</p>
        <ul class="list-bullets">
            <li>Elimäki: <a href="mailto:kirjasto.elimaki@kouvola.fi">kirjasto.elimaki@kouvola.fi</a></li>
            <li>Haanoja: <a href="mailto:kirjasto.haanoja@kouvola.fi">kirjasto.haanoja@kouvola.fi</a></li>
            <li>Hamina (pääkirjasto, Ruissalon lähikirjasto, kirjastoauto): <a href="mailto:kirjasto@hamina.fi">kirjasto@hamina.fi</a></li>
            <li>Iitti (pääkirjasto, kirjastoauto): <a href="mailto:kirjasto@iitti.fi">kirjasto@iitti.fi</a></li>
            <li>Inkeroinen: <a href="mailto:kirjasto.inkeroinen@kouvola.fi">kirjasto.inkeroinen@kouvola.fi</a></li>
            <li>Jaala: <a href="mailto:kirjasto.jaala@kouvola.fi">kirjasto.jaala@kouvola.fi</a></li>
            <li>Koria: <a href="mailto:kirjasto.koria@kouvola.fi">kirjasto.koria@kouvola.fi</a></li>
            <li>Kotka (pääkirjasto, Karhulan ja Karhuvuoren lähikirjastot, kirjastoauto): <a href="mailto:kaukopalvelu@kotka.fi">kaukopalvelu@kotka.fi</a></li>
            <li>Kouvolan pääkirjasto: <a href="mailto:kaukopalvelu@kouvola.fi">kaukopalvelu@kouvola.fi</a></li>
            <li>Kuusankoski: <a href="mailto:kirjasto.kuusankoski@kouvola.fi">kirjasto.kuusankoski@kouvola.fi</a></li>
            <li>Miehikkälä: <a href="mailto:kirjasto.miehikkala@miehikkala.fi">kirjasto.miehikkala@miehikkala.fi</a></li>  
            <li>Myllykoski: <a href="mailto:kirjasto.myllykoski@kouvola.fi">kirjasto.myllykoski@kouvola.fi</a></li>
            <li>Pyhtää: <a href="mailto:kirjasto@pyhtaa.fi">kirjasto@pyhtaa.fi</a></li>
            <li>Valkeala: <a href="mailto:kirjasto.valkeala@kouvola.fi">kirjasto.valkeala@kouvola.fi</a></li>
            <li>Virolahti: <a href="mailto:kirjasto.virolahti@virolahti.fi">kirjasto.virolahti@virolahti.fi</a></li>
        </ul>
        
        <p><a href="<?=$this->url('content-page',  ['page' => 'maksut'])?>">Kuntakohtaiset tilaushinnat</a></p>
    </div>
</div>

<!-- END of: Content/kaukolainat_fi.tpl -->