<!-- START of: Content/kaukolainat_fi.phtml -->
<?php $this->headTitle($this->translate('interlibrary loans'));  ?>

<div class="row">
    <div class="col-sm-12">
        <p><img src="<?=$this->imageSrc('palvelut/kaukolainat_banneri_eng.jpg')?>" alt="Kirjoja kirjaston hyllyssä" /></p>
        
        <h2>Request an interlibrary loan</h2>
        <p>If the material you are looking for is not available in Kyyti libraries, it can be requested as an interlibrary loan from another library in Finland or from abroad. Please note that interlibrary loans are chargeable. 
        <a href="https://kyyti.finna.fi/Content/asiakkaana#payments">Check the fees for your municipality here.</a></p>
         <p><a href="https://kyyti.finna.fi/Feedback/Form/Kaukolainatilaukset" target="_blank">Place a request</a></p>
        <p>You can also order an interlibrary loan by email, phone, or in the library.</p>

        <p>Once the interlibrary loan is ready for pick-up, you will receive a notification by email or text message. 
        Please return interlibrary loans to the same library from which you borrowed them.</p>
        <p>Interlibrary loans do not appear on your library account, and they cannot be renewed online. 
        You can request a renewal of an interlibrary loan by email or phone from the library where you ordered it.</p>


    </div>
</div>

<!-- END of: Content/kaukolainat_fi.tpl -->