<!-- START of: Content/kayttosaannot.fi.phtml -->

<? $this->headTitle('Käyttösäännöt'); $this->content()->setHeading('Käyttösäännöt'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>
    <div class="col-sm-9">
        <h2>Kyyti-kirjastojen käyttösäännöt</h2>
      
        <p>1.9.2019 alkaen</p>

        <p>Käyttösäännöt ovat voimassa Kouvolan, Kotkan, Haminan, Iitin, Pyhtään, Miehikkälän ja Virolahden kirjastoissa. 
        Kunnan oikeus laatia käyttösäännöt perustuu lakiin yleisistä kirjastoista 1492/2016. 
        Olet sitoutunut noudattamaan näitä käyttösääntöjä ja niihin tehtäviä muutoksia asioidessasi kirjastossa, saadessasi kirjastokortin tai suostuessasi vastuuhenkilöksi. 
        Kirjastojärjestelmään rekisteröityminen on kunnan kappale solmitusta sopimuksesta. Asiakkaan kappale sopimuksesta on kirjastokortti.</p>

        <p>Kirjaston tilat, aineistot ja palvelut ovat kaikkien käytettävissä.</p>

    <div id="libcard" class="content-section">
        <h2>Kirjastokortti</h2>

        <p>Kyyti-kirjastoilla on yhteinen kirjastojärjestelmä, johon asiakkaalla on yksi kirjastokortti. 
        Kirjastokortin ja tunnusluvun saa esittämällä valokuvalla ja henkilötunnuksella varustetun henkilötodistuksen ja ilmoittamalla osoitteensa Suomessa. 
        Tunnusluku tarvitaan automaateilla lainaamiseen, aineiston varaamiseen ja uusimiseen verkkokirjastossa, 
        omatoimikirjastojen sisäänpääsyyn sekä tunnistauduttaessa kirjastojen asiakkaille hankkimiin verkkopalveluihin.</p>

        <p>Jos asiakkaalla ei ole suomalaista henkilötunnusta, kirjastokortti on voimassa vuoden kerrallaan.</p>

        <p>Alle 15-vuotias saa kirjastokortin huoltajan tai muun täysi-ikäisen vastuuhenkilön kirjallisella suostumuksella. 
        Päiväkoti, koulu, muu laitos tai yhteisö voi saada yhteisön kirjastokortin. Kortin saaminen edellyttää yhteyshenkilön nimeämisen. 
        Yhteyshenkilö pitää huolta siitä, että korttia käytetään tarkoituksenmukaisella tavalla.</p>

        <p>Asiakas sitoutuu noudattamaan käyttösääntöjä allekirjoittaessaan kirjastokortin. 
        Kirjastokortti on henkilökohtainen ja se on esitettävä aina aineistoa lainattaessa sekä tarvittaessa muulloinkin kirjaston palveluja käytettäessä. 
        Asiakas on vastuussa kirjastokortillaan lainatusta aineistosta sekä lainojensa uusimisesta ja palauttamisesta. 
        Huoltaja tai vastuuhenkilö on vastuussa alle 15-vuotiaan lainoista.</p>

        <p>Asiakkaan tulee ilmoittaa nimen ja yhteystietojen muutoksesta kirjastoon. Myös kortin katoamisesta on heti ilmoitettava kirjastoon. 
        Kortin omistaja tai vastuuhenkilö on vastuussa ennen katoamisilmoitusta lainatusta aineistosta. 
        Kirjasto asettaa kadonneeksi ilmoitetun kortin käyttökieltoon.</p>
    </div>
    
    <div id="borrowing" class="content-section">     
        <h2>Lainaaminen, varaaminen, palauttaminen ja palauttamisen määräajat</h2>
      
        <p>Aineiston laina-aika on aineistosta riippuen 28, 14 tai 7 vuorokautta. 
        Laina-aika päättyy eräpäivänä kirjaston palveluajan päättyessä ja verkkokirjastossa vuorokauden vaihtuessa. 
        Aineiston voi palauttaa mihin tahansa Kyyti-kirjastoon. Palautuksesta saa halutessaan kuitin.</p>

        <p>Jos kirjastossa on palautusluukku, luukkuun jätetty aineisto käsitellään palautuneeksi vasta silloin, kun kirjastossa on seuraavan kerran palveluaika. 
        Myöhästymismaksut kertyvät normaalisti palautusten kirjautumiseen saakka.</p>

        <p>Asiakkaalla voi olla samanaikaisesti enintään 100 lainaa ja 100 varausta. 
        Aineistokohtaiset rajoitukset koskevat DVD- ja Blu-ray-levyjä (10 lainaa) ja konsolipelejä (5 lainaa). 
        Kirjastokohtaisia rajoituksia voidaan asettaa.</p>

        <p>Kuvatallenteiden ja konsolipelien lainauksessa noudatetaan virallisia ikärajoja.</p>

        <p>Lainan voi uusia viisi kertaa, jollei siitä ole varauksia tai erääntyneet maksut eivät ylitä kirjaston määräämää summaa. 
        Uusiminen on mahdollista asioimalla kirjastossa, puhelimitse ja verkkokirjaston kautta.</p> 

        <p>Aineistoa, jota ei ole Kyyti-kirjastoissa, voidaan tilata kaukolainaksi muista kirjastoista.</p>

        <p>Kirjasto ei vastaa lainatun aineiston tai käytetyn välineistön asiakkaalle aiheuttamista vahingoista.</p>
    </div>
  
    <div id="reservation" class="content-section">
        <h2>Kirjastopalveluiden maksuttomuus</h2>
		
		<p>Kirjaston maksuttomia palveluja ovat lain edellyttämällä tavalla:</p>
		<ul class="list-bullets">
		    <li>kirjaston omien aineistojen käyttö, lainaaminen ja varaaminen sekä</li>
		    <li>kirjaston käyttäjille annettava ohjaus ja neuvonta (tietopalvelu).</li>
		</ul>
	</div>	 
        
      
  
    <div id="fees" class="content-section">
        <h2>Maksut</h2>

        <p>Kirjaston palveluihin liittyvistä maksuista päättää kunkin kunnan lautakunta tai toimivaltainen viranhaltija.
        Lainaussuhteesta aiheutuvat erimielisyydet ja maksuvelvollisuudet käsitellään käräjäoikeudessa.</p>
        
        <p>Eräpäivän jälkeen palautetusta tai uusitusta aineistosta peritään myöhästymismaksu ja palautuskehotuksista sekä perintätoimenpiteistä aiheutuvat kulut.
        Myöhästymismaksu peritään myös siinä tapauksessa, että lainojen uusiminen ei ole onnistunut verkkokirjastossa tai eräpäivämuistutus ei ole mennyt perille käyttökatkoksen tai muun teknisen häiriön takia.</p>

        <p>Lasten ja nuorten aineistosta ei peritä myöhästymismaksuja. Palautuskehotuksista ja perimisestä aiheutuneet kulut veloitetaan kuitenkin asiakkaalta.</p>

        <p>Noutamattomasta varauksesta peritään maksu lukuun ottamatta lasten ja nuorten aineistoa.</p>

        <p>Muita kirjastoissa perittäviä kunkin kunnan päätösten mukaisia maksuja ovat esimerkiksi:</p>
        <ul class="list-bullets">
            <li>kirjastokortin uusiminen</li>
            <li>kaukolainat</li>
            <li>kopiot ja tulosteet</li>
        </ul>

		<p>Osa kirjastojen tarjoamista kokoontumis- ja näyttelytiloista on maksullisia. Tilojen vuokrat löytyvät kunkin kunnan palveluhinnastoista. </p>
	</div>
           
    <div id="reimbursements" class="content-section">  
        <h2>Kirjaston käyttäjän velvollisuudet</h2>
        <p>Kirjasto on järjestyslaissa tarkoitettu yleinen paikka ja siksi kirjaston toiminnan häiritsemiseen ja turvallisuuden vaarantamiseen sovelletaan järjestyslakia (612/2003). Kirjaston käyttäjä ei saa kirjastossa asioidessaan aiheuttaa häiriötä kirjaston muille käyttäjille eikä henkilökunnalle, eikä vaarantaa kirjaston viihtyisyyttä eikä turvallisuutta esimerkiksi metelöimällä, uhkaavilla eleillä tai hyökkäävillä liikkeillä.</p>

        <p>Kirjaston käyttäjän on käsiteltävä kirjaston aineistoa ja muuta omaisuutta huolellisesti. Kirjasto soveltaa vahingonkorvauslain (412/1974) säännöksiä tilanteessa, jossa kirjaston käyttäjä aiheuttaa kirjaston henkilökunnalle, aineistolle tai omaisuudelle vahinkoa.</p>

        <p>Kadonnut tai vahingoittunut aineisto on korvattava vastaavalla aineistolla tai maksamalla siitä kirjaston määrittelemä hinta. Videotallennetta, DVD- ja Blu-ray-levyä ei voi kappalekohtaisen tekijänoikeusmaksun vuoksi korvata vastaavalla tallenteella. Korvattu aineisto jää asiakkaan omaisuudeksi, eikä kirjasto lunasta sitä takaisin.</p>
    </div>
 
    <div id="borrowingright" class="content-section">     
        <h2>Lainausoikeuden menettäminen</h2>
      
        <p>Maksamattomat maksut jäävät asiakkaalle velaksi. 10 € ylittävät velat aiheuttavat automaattisesti lainauskiellon. Asiakas saa lainausoikeuden takaisin palauttaessaan myöhässä olevan aineiston ja maksaessaan kertyneet maksut.</p>
    </div>    
		
    <div id="acces_rights" class="content-section">
	    <h2>Käyttöoikeuden menettäminen</h2>
	
        <p>Kunta voi asettaa kirjaston käyttäjän määräaikaiseen kirjastokohtaiseen käyttökieltoon, 
        jos käyttäjä toistuvasti ja olennaisesti aiheuttaa häiriötä kirjaston toiminnalle, vaarantaa sen turvallisuutta tai vahingoittaa kirjaston omaisuutta. 
        Kestoltaan kielto voi olla enintään 30 päivää. Ennen käyttökieltoa asiakasta kuullaan ja käyttökiellosta tehdään viranhaltijapäätös, 
        johon asiakas voi vaatia oikaisua kuntalain (410/2015) mukaisesti.</p>
    </div>

    <div id="confidentiality" class="content-section">
        <h2>Tietosuoja</h2>
        <p>Kirjastolla on oikeus käyttää henkilötunnusta asiakasrekisterissään (Tietosuojalautakunnan päätös 56/1993). 
        Henkilötietoja käytetään ainoastaan kirjastopalveluiden tarkoituksiin. 
        Asiakkaalla on EU:n yleinen tietosuoja-asetuksen (2016/679) mukainen oikeus tarkistaa, mitä häntä koskevia tietoja rekisteriin on tallennettu. 
        Tietosuojaseloste ja tietopyyntölomake ovat nähtävillä Kyyti-kirjastojen verkkosivuilla sekä kirjastojen toimitiloissa.</p>
    </div>
    
    <div id="miscellaneous" class="content-section">
        <h2>Muuta</h2>
        <p>Käyttösääntöjen soveltamisesta päättää tarvittaessa kunkin kunnan kirjastopalveluja johtava henkilö.</p>
    </div>
    
    <div id="web_service" class="content-section">
        <br>
        
        <h2>Kyyti-verkkopalvelun käyttösäännöt</h2>
       
        <p>1. Noudata hyviä tapoja:</p>
      
        <ul class="list-bullets">
            <li>Kirjoita kohteliaasti toisia kunnioittaen.</li>
            <li>Harkitse ja kirjoita vasta sitten.</li>
            <li>Asioista saa kirjoittaa kriittisesti, mutta selkeät asiattomuudet ja henkilökohtaiset loukkaukset ovat kiellettyjä. Poistamme välittömästi kaikki herjaavat tai asiattomat viestit koskien ketä tahansa henkilöä. Lisäksi poistamme harkintamme mukaan kaikki asiattomat viestit.</li>
        </ul>
            
        <p>2. Jokainen keskustelija on vastuussa omista kirjoituksistaan ja niiden sisällöstä. Vaikka kirjoitat nimettömänä, voidaan lähettäjä tarvittaessa selvittää poliisitutkinnan avulla.</p>

        <p>3. Noudata voimassaolevaa lainsäädäntöä:</p>    
      
        <ul class="list-bullets">
            <li>Älä kerro kirjoituksissa omia tai muiden henkilötietoja, mukaan lukien sähköpostiosoitteita. Harkitse myös, mitä henkilökohtaisia asioita kirjoitat julkisesti. Älä kopioi kirjoituksiin henkilökohtaisia sähköpostiviestejä ilman lähettäjän lupaa. (Henkilötietolaki)</li>
            <li>Keskusteluissa ei saa levittää laitonta tai säädytöntä materiaalia. Myös rasismi ja siihen rinnastettava jonkin ihmisryhmän halventaminen on kielletty. (Rikoslaki)</li>    
            <li>Ilmoita lähde selvästi, jos lainaat tekstiä tai kuvaa artikkelista, kirjasta, blogista tms. (Tekijänoikeuslaki)</li>  
        </ul>

        <p>4. Mainostaminen on kirjoituksissa kielletty. Myös poliittinen ja uskonnollinen vaikuttaminen/mainostaminen on kielletty.</p>         

        <p>5. Käytä kirjoittaessasi tehosteita hillitysti. Vältä HUUTAMISTA, ja hillitse kuvien liittämistä viesteihin.</p>
    </div>
 
    <div id="moderointi" class="content-section">
        <br>
        <h2>Valvonta- ja moderointisäännöt</h2>
      
        <p>Valvonnasta ja moderoinnista vastaavat</p>
      
        <ul class="list-bullets">
            <li>Vinkin tai suosittelun (lukuvinkit, musiikkivinkit, elokuvavinkit, lastenvinkit, nuortenvinkit, vinkkivideot) kirjoittaja vastaa sopimattomien kommenttien poistamisesta</li>
            </ul>
        </div>  
    
    <div id="tekijänoikeus" class="content-section">
        <br>
        <h2>Tekijänoikeus</h2>
    
        <p>Muista, että tekijänoikeuslaki koskee myös verkossa julkaistavaa aineistoa. Tekijänoikeuslain alaisten aineistojen julkaiseminen tietoverkossa edellyttää aina luvan hankkimista tekijältä tai oikeudenhaltijalta. Verkkosivulle on kiellettyä liittää esimerkiksi jonkun muun ottama skannattu kuva tai verkosta löytynyt kuva, ilman kuvan omistajan lupaa. </p>
    </div>    
    
    <div id="Omatoimikirjastottekijänoikeus" class="content-section">
        <br>
        <h2>Omatoimikirjastojen käyttösäännöt</h2>
        <ul class="list-bullets">
            <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_kouvola.pdf')?>">Kouvola (pdf)</a></li>
            <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_kotka.pdf')?>">Kotka (pdf)</a></li>
            <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_hamina.pdf')?>">Hamina (pdf)</a></li>
            <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_iitti.pdf')?>">Iitti (pdf)</a></li>
            <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_pyhtaa.pdf')?>">Pyhtää (pdf)</a></li>
            <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_virolahti.pdf')?>">Virolahti (pdf)</a></li>
        </ul>
<!-- END of: Content/kayttosaannot.fi.tpl -->