<!-- START of: Content/kayttosaannot.en.phtml -->

<? $this->headTitle('User regulations'); $this->content()->setHeading('User regulations'); ?>



<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>

    <div class="col-sm-9">
        <h2>Welcome to using our library services!</h2>

        <h2>RULES OF USE OF KYYTI LIBRARIES</h2>

        <p>VALID FROM 1 JANUARY 2025</p>

        <p>
            These rules of use apply to Kouvola, Kotka, Hamina, Iitti, Pyhtää, Miehikkälä, and Virolahti libraries.
            The right of municipalities to prepare rules of use is based on the Public Libraries Act (1492/2016).
            Users must comply with these rules of use and any later amendments made to them when they use library
            services,
            receive a library card, or agree to become responsible for another person. The customer’s registration in
            the
            library system is the municipality’s copy of the agreement between the customer and the municipality.
            The library card represents the customer’s copy of the agreement.
        </p>

        <p>Library premises, materials, and services are available to all.</p>

        <div id="libcard" class="content-section">
            <h2>Library card</h2>
            <p>
                Kyyti libraries have a shared library system that enables customers to use the services of all the
                libraries in the network with one card.
                To be granted a library card and a PIN code for it, customers must present a photo ID with a personal
                identity code, and provide their address in Finland.
                A PIN code is needed for borrowing materials at self-service points, reserving materials, renewing loans
                online,
                and accessing self-service libraries and the library’s online resources.
            </p>

            <p>
                A person under 15 years of age can be granted a library card subject to the written consent of their
                parent or guardian,
                or some other responsible per-son who must be at least 18 years of age. Daycare centres, schools and
                other institutions or
                communities can get a library card by appointing a contact person who will responsible for the
                appropriate use of the card.
            </p>

            <p>
                The customer commits to following these rules of use when he or she signs a library card.
                The library card is personal and must always be presented when borrowing materials and upon request also
                when using other library services.
                The customer is responsible for all materials that have been borrowed using his or her library card, and
                for renewing and returning his or her loans.
                If the owner of the library card is under 15 years of age, their guardian or other responsible person
                will be responsible for any materials borrowed using the library card.
            </p>

            <p>
                The customer must notify the library of any changes in their name or contact details.
                The library must also be notified immediately if the library card is lost.
                The owner of the card or the guardian/responsible person is responsible for any materials borrowed with
                the card before the library is notified of the loss of the card.
                The library will block the use of cards that have been reported as being lost.
            </p>

            <h3>Library Card Validity</h3>

            <p>
                A library card for individuals, children, and home service customers is valid for 10 years. However, if
                the card has not been used for 3 years, the membership may be terminated.
            </p>

            <p>
                If the customer does not have a Finnish personal identity code, the library card is valid for one year
                at a time. Similarly, the card for organizational customers is valid for one year at a time.
            </p>

            <p>
                When the validity of the library card expires, the customer should contact the library. After verifying
                the customer’s information, the validity of the library card can be extended.
            </p>
        </div>

        <div id="borrowing" class="content-section">
            <h2>Borrowing, reserving, and returning materials, and due dates</h2>
            <p>
                Depending on the material, the loan time is 28, 14 or 7 days. The loan time ends when the library closes
                on the due date. At the online library, the loan time ends at 24.00 on the due date. Library materials
                can be returned to any Kyyti library. Customers can get a receipt of the return if they wish.
            </p>

            <p>
                If the library has a drop box for returning materials when the library is closed, any materials left in
                the drop box will be processed and considered
                as returned only when the library is next open. Any fees charged for late return will continue to
                accumulate as normal until the material has been registered as returned.
            </p>

            <p>
                Each customer can have a maximum of 100 loans and 100 reservations at any given time.
                Material-specific restrictions apply to DVDs and Blu-ray discs (10 loans) and to console games (5
                loans). Library-specific restrictions can also be set.
            </p>

            <p>Official age limits apply to audiovisual programmes.</p>

            <p>
                Each loan can be renewed five times unless a reservation is made for the material and provided that the
                total of unpaid
                fees does not exceed the maximum sum specified by the library. Loans can be renewed by visiting the
                library in person, or by phone or online.
            </p>

            <p>
                Materials not included in the collection of Kyyti libraries can be ordered from other libraries as
                interlibrary loans.
            </p>

            <p>
                The library is not responsible for any losses or any other harm that may be caused to the customer by a
                circumstance directly relating to the materials borrowed or equipment used.
            </p>
        </div>

        <div id="reservation" class="content-section">
            <h2>Free library services</h2>

            <p>Based on legislation, free library services include:</p>
            <ul class="list-bullets">
                <li>Using, borrowing, and reserving materials included in the library’s own collection</li>
                <li>Instructing and advising the users of the library (information services)</li>
            </ul>
        </div>

        <div id="fees" class="content-section">
            <h2>Fees</h2>
            <p>The relevant committee or competent official of each municipality will specify the fees charged for
                library services.
                Any disputes and payment liabilities arising from or in connection to these rules of use will be
                resolved at the district court.
            </p>

            <p>
                For unreturned materials, the library sends two return reminders. If the customer fails to return the
                materials despite these reminders, an invoice will be issued. The library is not obligated to accept
                materials that have been invoiced. Unpaid invoices will be forwarded to a collection agency for
                processing.
            </p>

            <p>
                A fee is charged for loans that are returned or renewed after the due date. In addition, expenses
                relating to the sending of return notices
                and to recovery measures will be charged to the customer. A penalty fee will also be charged for overdue
                loans if renewing the loans online
                has failed, or if a due date reminder has not been received due to a service disruption or some other
                technical problem.<br>
                No penalty fees are charged for materials for children or young adults.
            </p>

            <p>
                A billing surcharge is applied to materials that have been invoiced. The collection agency will charge
                any costs incurred from the collection process.
            </p>

            <p>
                A fee will be charged for any reservations that are not collected, except for materials for children and
                young adults
            </p>

            <p>Other library fees charged subject to the decision of each municipality include:</p>

            <ul class="list-bullets">
                <li>Library card renewal</li>
                <li>Interlibrary loans</li>
                <li>Photocopies and printouts</li>
            </ul>

            <p>
                Some of the assembly and exhibition premises offered by the libraries are subject to a fee. Rents of the
                premises can be found in the service pricelist of each municipality.
            </p>
        </div>

        <div id="reimbursements" class="content-section">
            <h2>Liabilities of library users</h2>
            <p>
                Libraries are public places as referred to in the Public Order Act (612/2003), and so this Act applies
                to
                disturbing the operations of or endangering the safety of libraries.
                Library users must not cause disturbance to other library users or library personnel when visiting the
                library, and must not lessen the pleasantness
                or safety of the library, for example by making noise or behaving in a threatening or aggressive way.
            </p>

            <p>
                Library users must handle library materials and other library property with care. Provisions of the Tort
                Liability Act (412/1974) will be applied
                in a situation where the user causes damage to the library personnel or to materials or other property
                of the library.
            </p>

            <p>
                Lost or damaged material must be replaced with corresponding material, or by paying the price specified
                by the library.
                Due to the item-specific copy-right fee, video recordings, DVDs, and Blu-ray discs cannot be replaced
                with a corresponding recording.
                The library will not redeem any materials that have been damaged or lost once the customer has replaced
                or paid for the materials in
                question (that is, the customer can keep any such material).
            </p>
        </div>

        <div id="borrowingright" class="content-section">
            <h2>Loss of borrowing rights</h2>
            <p>
                Unpaid fees will constitute a debt owed to the library. An outstanding debt of €10 or more will
                automatically result in the loss of borrowing rights.
                Borrowing rights will be restored once the fees are paid and any overdue items returned.
            </p>
        </div>

        <div id="acces_rights" class="content-section">
            <h2>Loss of the right to use library services</h2>
            <p>
                The municipality can remove the right of a user to use the services of a certain library for a fixed
                period if the user has repeatedly and
                significantly disturbed the activities of the library, endangered its safety, or damaged the property of
                the library.
                The maximum duration of such a ban is 30 days. Before such a ban can be imposed on a user, the customer
                must be heard on the matter and an
                official decision must be made on it so that the customer will have the statutory right to appeal
                against the decision in accordance with the Local Government Act (410/2015).
            </p>
        </div>

        <div id="confidentiality" class="content-section">
            <h2>Data protection</h2>
            <p>
                The library has the right to use the personal identity code of its users in its customer register
                (Decision of the Finnish Data Protection Board 56/1993).
                Personal data is used only for the purpose of library services. Under the EU General Data Protection
                Regulation (GDPR) (2016/679),
                the customer has the right to inspect his or her personal data that has been saved in the register.
                The data protection record and an information request form can be viewed on the website of Kyyti
                libraries and on the library premises.
            </p>
        </div>

        <div id="miscellaneous" class="content-section">
            <h2>Miscellaneous</h2>

            <p>
                Where required, the person responsible for library services in each municipality will make decisions
                relating to the application of these rules of use.
            </p>
            
        </div>
        
        <p>
            <i>These are an unofficial translation of the Finnish terms of use. If the Finnish and English rules of use differ, 
            the Finnish rules of use prevail.</i>
        </p>
    </div>

    <!-- END of: Content/kayttosaannot.en-gb.tpl -->
