<!-- START of: Content/laitteet_fi.phtml -->

<? $this->headTitle('Laitteet'); $this->content()->setHeading('Laitteet'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>
  
    <div class="col-sm-9">
        <div id="Kouvola" class="content-section">
            <img src="<?=$this->imageSrc('palvelut/laitteet_banneri.jpg')?>" alt="3D-tulostimella tulostettuja satuhahmoja 3D-tulostimen edessä" />
            
            <br>
            <br>

            <h2>Kouvola</h2>
            <p>Voit tutustua Kouvolan kirjastojen laitteisiin ja tehdä varauksia Varaamo-palvelussa.</p>
            <p><a href="https://varaamo.kouvola.fi/" target="_blank">Siirry Varaamoon (varaamo.kouvola.fi)</a></p>
            <br>
            <p>Kouvolan kirjastojen laitteet löytyvät kirjastokohtaisesti <a href="https://kyyti.finna.fi/OrganisationInfo/" target="_blank">palvelupisteet sivulta.</a> </p>
            <br>
            <h3>Tulostus ja kopiointi Kouvolan kirjastoissa</h3>
            
            <p>Kaikissa Kouvolan kirjastoissa on käytössä tulostuspalvelu, joka mahdollistaa esim. etätulostuksen kotikoneelta ja työn vapauttamisen tulostimelta missä tahansa Kouvolan kirjastossa. </p>
            <p><b>Rekisteröidy</b> ennen ensimmäistä kirjastotulostusta, kopiointia tai skannausta vetämällä kirjastokorttisi tulostimen lukijalaitteessa ja antamalla kirjastokorttisi tunnusluku.</p>
            <p><b>Tulostaminen ja kopiointi</b> ovat maksullisia. Katso hinnat <a href="https://kyyti.finna.fi/Content/maksut-kouvola" target="_blank">Kouvolan maksut -sivulta.</a> Voit tulostaa kirjaston asiakaskoneelta tai omalta laitteeltasi mistä tahansa. 
            Lähetä omasta sähköpostistasi haluamasi tiedostot osoitteeseen kirjastotulostus[at]kouvola.fi. Tulostustyö vapautetaan kirjastokortillasi ja tunnusluvulla kirjaston tulostimelta.</p>
            <p><b>Kopioinnissa</b> tarvitset kirjastokorttia ja siihen liitettyä tunnuslukua.</p>
            <p><b>Skannaus</b> on maksutonta. Lähetä laitteelta skannattu työ omaan sähköpostiisi.
                Tulostaminen ja skannaus edellyttävät, että sinulla on kirjastokorttiisi liitetty tunnusluku ja että sähköpostiosoitteesi on lisätty kirjastojärjestelmään.
                Kirjaston aukioloaikoina voit ladata kirjaston asiakaspalvelussa kirjastokortillesi arvoa tulostamista ja kopiointia varten.
                Lisää tietoa kirjastostasi.
            </p>
            <p><a href="https://kyyti.finna.fi/themes/custom/files/Kirjastotulostus_Kouvola.pdf">Ohjeet tulostamiseen, kopioimiseen ja skannaamiseen</a> </p>
        </div>
     
        <div id="Kotka" class="content-section">
            <h2>Kotka</h2>
            <h3>Laitteiden varaaminen ja opastukset</h3>
            <p>3D-tulostin, digitointilaitteet, mikrofilminlukulaite ja ompelukone pitää varata etukäteen.</p>
            <ul class="list-bullets">
                <li>sähköposti: <a href="mailto:kirjasto@kotka.fi">kirjasto@kotka.fi</a></li>
                <li>puhelin: <a href="tel:+358406883754">040 688 3754</a>.</li>
            </ul>
            <p>Jos et ole aiemmin käyttänyt 3D-tulostinta, digitointilaitteita tai mikrofilminlukulaitteita, pyydä varausta tehdessä myös opastus laitteen käyttöön. 
            Ompelukoneen käyttöön emme anna opastusta.</p>
    
            <h3>Tietokoneet, tulostimet ja skannerit</h3>
            <p>Kaikissa Kotkan kirjastoissa on vapaasti ilman ajanvarausta käytettäviä tietokoneita. Voit myös lainata kannettavan tietokoneen ja käyttää sitä kirjaston tiloissa.</p> 
            <p>Kaikissa kirjastoissa voi kopioida ja tulostaa.</p>
            
            <p><a href="https://kyyti.finna.fi/themes/custom/files/kirjastotulostus_kotka.pdf">Ohjeet tulostamiseen, kopioimiseen ja skannaamiseen</a></p>
            
            <h3>Tabletit</h3>
            <p>Pääkirjastolla on asiakkaiden käytössä Hublet-tabletteja. Voit napata Hubletin käyttöösi kahdeksi tunniksi 2. kerroksen lehtisalista 
            kirjastokortilla ja nelinumeroisella tunnusluvulla. Laitteet toimivat kirjaston tiloissa ja niillä voit esimerkiksi lukea sähköposteja, 
            surffata netissä, somettaa, pelata, kuunnella musiikkia, katsella videoita, lukea e-lehtiä ja käyttää muita kirjaston sähköisiä aineistoja ja palveluita.</p>
            <p>Hublettien käyttö on turvallista, koska kaikki selaustietosi ja laitteelle tallentamasi tiedot poistuvat automaattisesti, kun palautat laitteen latausasemaan.</p>
            <p>Karhulan ja Karhuvuoren kirjastoissa voit lainata asiakaspalvelusta kirjastossa käytettäväksi iPad-tabletteja.</p>
            
            <h3>Langaton verkko</h3>
            <p>Kaikissa Kotkan kirjastoissa on ilmainen langaton verkko.</p>
            <ul class="list-bullets">
                <li>verkon nimi: kirjasto-vierailija</li>
                <li>salasana: kirjasto</li>
            </ul>
    
            <h3>3D-tulostimet</h3>
            <p>Pääkirjaston 3D-tulostimilla voit valmistaa fyysisiä esineitä myrkyttömästä ja biohajoavasta PLA-muovista. Tulostaminen on ilmaista.</p>
            <p>Jos 3D-tulostaminen on sinulle uutta, henkilökunta opastaa mallin valinnassa, tulostamisessa ja kertoo lisää tulostamisen mahdollisuuksista. 
            Ensimmäisellä kerralla voit tulostaa vaikkapa avaimenperän, pienen satuhahmon, nimikyltin tai etsiä henkilökunnan kanssa sinua kiinnostavan mallin internetistä.</p>
            
            <p>Voit myös tulostaa omia malleja. Mallitiedoston tulee olla joko STL- tai OBJ-muodossa.
            Ennen tulostamista mallitiedosto muunnetaan 3D-tulostimen ymmärtämään muotoon kirjaston tietokoneella.</p>
            <p>Laitteet: kaksi Prenta Duo XL SE -tulostinta ja Simplify3D-viipalointiohjelma.</p>
            
            <h3>Pelikoneet</h3>
            <p>Kirjastossa voit pelata videopelejä tietokoneilla ja pelikonsoleilla. Varaa peliajat lasten- ja nuortenosaston asiakaspalvelusta.</p>
            
            <p>Laitteet</p>
            <ul class="list-bullets">
                <li>Pääkirjasto: kaksi kannettavaa tietokonetta ja Playstation 4.</li>
            </ul>
    
            <h3>Ompelukone</h3>
            <p>Pääkirjaston ompelukoneella voit ommella kirjaston tiloissa maksutta.
            Ompelukoneella on kirjaston puolesta sakset.</p>
            <p>Laitteet: Singer Fashion Mate 3333 -ompelukone.</p>  
    
            <h3>VHS-kasettien digitointi ja editointi</h3>
            <p>Videoiden digitointilaitteilla voit tallentaa VHS-kasetit tietokoneella katseltavaksi tiedostoksi tai DVD:lle.</p>
            <p>Laitteet: LG-videonauhuri ja Adobe Premiere Pro CC -videoeditointiohjelma.</p>
    
            <h3>Valokuvien digitointi ja editointi</h3>
            <p>Digitointipisteellä voi skannata valokuvia, dioja ja negatiiveja digitaaliseen muotoon.</p>
            <p>Laitteet: Epson Perfection V500 Photo -tasoskanneri ja Photoshop Elements 12 -kuvankäsittelyohjelma.</p>
            
            <h3>Mikrofilmien- ja korttienlukulaite</h3>
            <p>Mikrofilminlukulaitteella voi lukea mikrofilmille tai mikrokorteille tallennettuja asiakirjoja, kirjoja ja lehtiä.</p>
            <p>Laitteet: ScanPro 2200+ -mikrofilmiskanneri ja tulostin kopioiden tulostamiseen.</p>
        </div>
        
        <div id="Hamina" class="content-section">
            <h2>Hamina</h2>
            <h3>Tietokoneet, tulostimet ja skannerit</h3>
            <p>Voit käyttää asiakastietokoneita Haminan pääkirjastossa ja Ruissalon kirjastossa. Tietokoneilta voi tulostaa.</p>
            <p>Voit kopioida ja skannata asiakirjoja Haminan pääkirjastossa ja Ruissalon kirjastossa.</p>
            <p>Haminan pääkirjastossa on käytössä monitoimilaite (Konica Minolta bizhub C250i), jossa on väritulostus-, kopiointi- ja skannaustoiminnot.</p>
            
            <h3>Langaton verkko</h3>
            <p>Haminan pääkirjastossa ja Ruissalon kirjastossa on ilmainen langaton verkko.</p>
            
            <h3>Pelikoneet</h3>
            <p>Haminan pääkirjastossa voit pelata videopelejä PlayStation 5 -pelipisteellä. Peliajat varataan asiakaspalvelusta.</p>

            <h3>Mikrofilmien- ja korttienlukulaite</h3>
            <p>Haminan pääkirjaston mikrofilminlukulaitteella voi lukea mikrofilmille tai mikrokorteille tallennettuja asiakirjoja.</p>
            <p>Laitteet: ScanPro 2200+ -mikrofilmiskanneri ja tulostin kopioiden tulostamiseen.</p>
            <p>Varaa aika mikrofilminlukulaitteelle, p. <a href="tel:+358401991310">040 1991 310</a>, sähköposti: <a href="mailto:kirjasto@hamina.fi">kirjasto@hamina.fi</a>.</p>
        </div>
        
        <div id="Iitti" class="content-section">
            <h2>Iitti</h2>
            <h3>Tietokoneet, tulostimet ja skannerit</h3>
            <p>Kirjastossa on asiakastietokoneita (viivakoodinlukijalla) sekä monitoimilaite, jossa on väritulostus-, kopiointi- ja skannaustoiminnot.</p>
            
            <h3>Langaton verkko</h3>
            <p>Asiakkaiden käytössä on ilmainen langaton verkko.</p>
            
            <h3>Mikrofilmien- ja korttienlukulaite</h3>
            <p>Mikrofilminlukulaitteella voi lukea mikrofilmille tai mikrokorteille tallennettuja asiakirjoja.</p>

            <ul class="list-bullets">
                <li>Kortinlukulaite: MAP RPP-3/4</li>
                <li>Filminlukulaite: Canon universal reader 320</li>
            </ul>

            <h3>Pelikoneet</h3>
            <p>Kirjastossa voit pelata tietokoneilla ja PS4-pelikonsolilla. Varaa peliajat asiakaspalvelusta.</p>
        </div>
    
        <div id="Pyhtää" class="content-section">
            <h2>Pyhtää</h2>
            <h3>Tietokoneet, tulostimet ja skannerit</h3>
            <p>Kirjastossa on asiakaskäytössä neljä tietokonetta ja tulostin, jolla on mahdollista tulostaa musta-valkoisia ja väritulosteita. 
            Skannausmahdollisuus on vain kirjaston palveluaikana.</p>
            
            <h3>Langaton verkko</h3>
            <p>Asiakkaiden käytössä on ilmainen langaton verkko.</p>
            
        </div> 
    
        <div id="Virolahti" class="content-section">
            <h2>Virolahti</h2>
            <h3>Tietokoneet, tulostimet ja skannerit</h3>
            <p>Kirjastossa on kaksi asiakastietokonetta, mustavalkotulostin sekä monitoimilaite, jossa on väritulostus-, kopiointi- ja skannaustoiminnot. 
            Monitoimilaite on käytössä vain palveluaikana.</p>
            <h3>Langaton verkko</h3>
            <p>Asiakkaiden käytössä on ilmainen langaton verkko.</p>
        </div> 
    
        <div id="Miehikkälä" class="content-section">
            <h2>Miehikkälä</h2>
            <h3>Tietokoneet, tulostimet ja skannerit</h3>
            <p>Kirjastossa on kaksi asiakastietokonetta, mustavalkotulostin sekä monitoimilaite, jossa on väritulostus-, kopiointi- ja skannaustoiminnot.</p>
            <h3>Langaton verkko</h3>
            <p>Asiakkaiden käytössä on ilmainen langaton verkko.</p>
        </div>
    </div>
</div>

<!-- END of: Content/laitteet_fi.tpl -->