<!-- START of: Content/lanupoiminta_helmeri_ja_tuovi.tml -->

<? $this->headTitle('Haminan kirjaston maskottien tarina'); $this->content()->setHeading('Haminan kirjaston maskottien tarina'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Haminan kirjaston maskottien Helmeri-pöllön ja Tuovi-toukan alkuperää selviteltiin alle 13-vuotiaille haminalaisille suunnatussa Maskotit tutuiksi -kirjoituskilpailuissa ajalla 6.2.-28.4.2023.</p>
        <p>Henkilökunta valitsi maskottien tarinaksi kirjoituksen, jossa oli elävästi kuvailtu maskottien ilmestymistä kirjastoon ja kerrottu niiden 
        ominaispiirteistä. Voitokkaan tekstin on kirjoittanut 10-vuotias Kerttu Kurki.</p>
        <br>
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/helmeri_ja_tuovi2.jpg')?>" width="400" alt="Helmeri-pöllö kirjaston keinukalusteessa"></p>

        <h2>Helmeri ja Tuovi</h2>
        <p>Moi eräänä päivänä olin Haminan pääkirjastossa ja näin siellä munan joka alkoi hehkua ja poksahdella sitten sieltä tupsahti pöllö ja toukka. 
        He sanoivat näin:</p>
        <p> - Olemme tulleet Myrkkymäen kaupungista.</p>
        <p>Seuraavaksi pöllö ja toukka kävivät puhumaan toisistaan ja pöllö kertoi toukasta näin:</p>
        <p> - Tässä minun vieressäni on Tuovi- toukka. Tuovi on hauska ja rohkea hän tykkää lukea kirjoja mutta hän ei pidä tanssimisesta. 
        Tuovi herkuttelee mieluiten suolakurkuilla.</p>
        <p>Sitten Tuovi kertoi pöllöstä näin:</p>
        <p> - Minun vieressäni on Helmeri-pöllö. Helmeri on ujo, mukava ja päättäväinen hän tykkää lukea kirjoja ja hän ei pidä videopeleistä. 
        Helmeri herkuttelee mieluiten ranskalaisilla.</p>
        <p>Sitten he hihkaisevat yhteen ääneen:</p>
        <p> - Olemme olleet parhaita ystäviä jo kahdeksan-vuotta!</p>
        <p>Pöllö kertoi:</p>
        <p> - Me emme halua lähteä täältä ikinä pois täällä on niin kotoisaa.</p>
        <p>Silloin äitini soitti ja sanoi:</p>
        <p> - Tuleppas syömään.</p>
        <p>Minä sanoin Tuoville ja Helmerille:</p>
        <p> - Minun pitää lähteä oli kiva tavata teidät.</p>
        <p>He huusivat:</p>
        <p> - Hei hei!</p>
    </div>
</div>
   
<!-- END of: Content/lanupoiminta_helmeri_ja_tuovi.tml -->