<!-- START of: Content/lanupoiminta_lukubingo_kouvola.phtml -->

<? $this->headTitle('Kesän lukubingo Kouvolassa'); $this->content()->setHeading('Kesän lukubingo Kouvolassa'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Pelaa lukubingoa ja voita kutkuttavia palkintoja! Hae bingolomake kirjastosta tai <a href="<?=$this->fileSrc('lukubingo.pdf')?>">tulosta se tästä</a>.</p>
        <p>Yksi bingorivi eli neljän suora on neljä luettua kirjaa. 
        Kirjoita lukemiesi kirjojen nimet bingon kääntöpuolelle ja palauta bingo mihin tahansa Kouvolan kirjastoon tai kirjastoauto Tesaurukseen 31.8.2021 mennessä.</p>
        <p>Kaikkien vähintään yhden bingorivin saaneiden kesken arvotaan kivoja palkintoja. Mukavaa lukukesää!</p>
        
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/lukujanis2.png')?>" width="200" alt="piirretty lukeva jänis"></p>
    </div>
</div>

<!-- END of: Content/lanupoiminta_lukubingo_kouvola.tml -->