<!-- START of: Content/karhujen-tarina_fi.phtml -->

<? $this->headTitle('Kotkan kirjaston karhujen tarina'); $this->content()->setHeading('Kotkan kirjaston karhujen tarina'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Nuori kymiläinen karhu - nykyinen Kyminmamma - rakastui ammoisina aikoina komeaan karhuherraan ja he saivat pian kaksi rohkeaa karhunpentua, Laurin ja Valtterin.</p>
        
        <p>Karhuherran lähdettyä seitsemän meren taakse onneaan onkimaan karhuemo tarjosi pojille ruuaksi Karhulan pitsaa ja leipuri Hiivan pullaa, mutta pojat eivät oikein kasvaneet. 
        Onneksi emo keksi soutaa Kymijokea pitkin merelle laskeakseen hailiverkot. Suuren saaliin saatuaan emo huuteli pojilleen: ”Hailii happamii, Kyminmamman tappamii.”</p>
        
        <p>Pojista kasvoi oivat karhuherrat. Valtteri, joka seuraa innokkaasti formuloita, pääsi hommiin Kotkan kirjastoauto Ilonaan ja ajelee nyt pitkin poikin Kotkan hiekkateitä. 
        Urheilullinen Lauri otettiin Karhuvuoren kirjastoon, aivan koripallohallin viereen. </p>
        
        <p>Kyminmamman karhuherra asettui eläkepäiviksi Kotkansaarelle pääkirjastoon Saaren Vaariksi muistelemaan menneitä ja tuumimaan tulevia. 
        Kyminmamman voi tavata Karhulan kirjastosta ainakin lukemasta satuja ja pitämästä urheilukoulua.</p>
        
        <br>
        <br>
        
        <img src="<?=$this->imageSrc('lanu/karhujen-tarina.jpg')?>" alt="Kotkan karhupehmolelut lastenosastolla" width="400">
        <p>Valokuvassa vasemmalta oikealle: (Kirjastoauto Ilonan) Valtteri, (Karhulan kirjaston) Kyminmamma, (Pääkirjaston) Saaren Vaari, (Karhuvuoren kirjaston) Lauri</p>
    </div>
</div>
   
<!-- END of: Content/karhujen-tarina_fi.phtml -->