<!-- START of: Content/lukukoirat.phtml -->

<? $this->headTitle('Kyytin lukukoirat'); $this->content()->setHeading('Kyytin lukukoirat'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Tiesitkö, että kirjastoissa työskentelee välillä myös koirakavereita? Nämä seitsemän lukukoirakaverusta voi löytää Kotkan ja Kouvolan kirjastoista.</p>

        <h2>Kotkan lukukoirat</h2>
    </div>
</div>

<div class="row infobox"> 
    <div class="col-sm-4">
        <img class="marginauto img-responsive" src="<?=$this->imageSrc('lanu/lukukoira_ruuti_2024.jpg')?>" alt="Ruuti"/>
    </div>
    <div class="col-sm-8">
        <b>Ruuti</b>
        <p>Ruuti on 2017 keväällä syntynyt lyhytkarvainen mäyräkoiranarttu. Ruutin perheeseen kuuluu myös tytär Lili (syntynyt 2020). 
        Ruutin on toisen polven lukukoira ja peri työnsä kirjastolla äidiltään Judolta syksyllä 2021. Ruutin voi tavata Karhulan kirjastolla ja lukukoirien yhteisissä tapahtumissa.
        Ruuti vierailee satunnaisesti myös Haminan puolella.</p>
        <p>Perusluonteeltaan Ruuti on hyvin hellyydenkipeä ja herkkä pikkukoira, joka osaa kohdata lapset ja aikuiset lempeästi ja varovaisesti. 
        Kuuntelijana se on utelias ja kiinnostunut, mutta rauhoittuu nopeasti lukijan jalkoihin nukkumaan.</p>
        <p>Ruutin mielestä parasta maailmassa on hellä huomio, jutteleminen ja silittely, ja jos silittelet sitä leuan alta niin saat siitä ikuisen ystävän kerrasta! 
        Lukukoirailun lisäksi Ruuti harrastaa monipuolisesti kaikkea näyttelyistä agilityyn ja metsästyslajeihin.</p>
    </div>
</div>

<div class="row infobox">    
    <div class="col-sm-4">
        <img class="marginauto img-responsive" src="<?=$this->imageSrc('lanu/lukukoira_ira_2024.jpg')?>" alt="Ira"/>
    </div>

    <div class="col-sm-8">
        <b>Ira</b>
        <p>Ira (Tanzara Xirana) tuli mukaan Kotkan Lukukoiriin toukokuussa 2022. Se paikkasi sairaslomalla olevan Lukukoira Manun kuunteluhetken 4.5.2022 ja on ollut mukana siitä lähtien. 
        Ira on vuonna 2019 syntynyt bedlingtoninterrierinarttu. Luonnonlahjakkuus jota kummipoikani poika harjoitutti Lukukoiran vaativaan tehtävään.</p>
        <p>Ira nauttii ihmisten seurasta. Lenkillä kaikki ohikulkijat on tervehdittävä. Karitsamainen ulkonäkö saakin useimmat hymyillen kumartumaan ja silittämään pientä silkkiturkkia. 
        Vaikka energiaa riittää, huivi kaulassa keskitytään ja kuunnellaan lukijaa kauniisti joko vieressä istuen tai syliin käpertyen.</p>
        <p>Ira kuuntelee pääasiassa Kotkan pääkirjastolla mutta tarvittaessa lähdetään toisiin toimipisteisiin ja tapahtumiin.</p>
    </div>
</div>

<div class="row infobox"> 
    <div class="col-sm-4">
        <img class="marginauto img-responsive" src="<?=$this->imageSrc('lanu/lukukoira_wiiru_2024.jpg')?>" alt="Wiiru"/>
    </div>
    <div class="col-sm-8">
        <b>Wiiru</b>
        <p>Hei, olen Kotkan Lukukoira Wiiru. Rodultani olen shetlanninlammaskoira. Olen 3,5 vuotias (syntynyt 2018). Aloitin Lukukoirana kesällä 2021. 
        Pääpaikkana minulla on Karhulan kirjasto. Harrastan agilityä, lenkkeilyä ja veljen kanssa kirmailua.
        Pidän lukukeikoista. Juoksen autolta juoksujalkaa kirjastoon. Minua saa tulla kirjastossa aina rapsuttelemaan, jos ei uskaltaudu lukemaan :)
        </p>
    </div>
</div>

<div class="row infobox">    
    <div class="col-sm-4">
        <img class="marginauto img-responsive" src="<?=$this->imageSrc('lanu/lukukoira_sulo_2024.jpg')?>" alt="Sulo"/>
    </div>

    <div class="col-sm-8">
        <b>Sulo</b>
        <p>Sulo on perinyt pestin saman perheen edeltäjiltä. Griffon belge Piki aloitti lukukoirailun Kotkan kirjastolla vuonna 2012
        toimien lukukoirana kahdeksan vuotta. Pikin tassunjäljissä jatkoi griffon bruxellois Nasse. Ja nyt Nassen jäätyä ”eläkkeelle”, pestin
        peri petit brabancon Sulo.
        </p>
        
        <p>Sulo on syntynyt toukokuussa 2017. Sulo on rauhallinen ja seurallinen kaveri. Mielellään köllähtää kuuntelemaan tarinoita
        Ja nauttii samalla rapsutuksista.
        </p>
    </div>
</div>

<div class="row infobox">    
    <div class="col-sm-4">
        <img class="marginauto img-responsive" src="<?=$this->imageSrc('lanu/lukukoira_teri_pysty_2024.jpg')?>" alt="Teri"/>
    </div>

    <div class="col-sm-8">
        <b>Teri</b>
        <p>Teri on 8-vuotias belgianpaimenkoira.
        Teri on eläkkeelle jäänyt harrastuskoira. Teri on harrastanut  mm. agilitya, tokoa ja palveluskoiralajeja. Teri tykkää hirmuisesti lähellä olosta ja rapsutuksista, siksi tullaan
        mieluusti kuuntelemaan kun luet meille.
        </p>
        <p>Terkuin, Teri ja Mari.</p>
    </div>
</div>

<h2>Kouvolan lukukoirat</h2>

<div class="row infobox">    
    <div class="col-sm-4">
        <img class="marginauto img-responsive" src="<?=$this->imageSrc('lanu/taimi.jpg')?>" alt="Taimi"/>
        <p style="text-align:center;">Kuvaaja: Susanna Piibemann</p>
    </div>

    <div class="col-sm-8">
        <b>Taimi</b>
        <p>Taimi, Suomenlapinkoira, 5 vuotta. Taimi on käynyt Kennelliiton lukukoira- ja kaverikoirakoulutuksen ja toiminut pian vuoden lukukoirana 
        Kouvolan pääkirjastossa ja reilut kaksi vuotta kaverikoirana vanhusten, kuntoutujien ja lasten parissa.</p>
        
        <p>Taimi rakastaa kaikkia ihmisiä ja heiltä saamaansa huomiota ja rapsutuksia. Taimi tulee myös hyvin juttuun muiden koirien kanssa. 
        Taimi asustaa omakotitalossa Oili-äitinsä, Itu-poikansa ja parhaan ystävänsä Bea-beaglen kanssa, toki Taimin perheeseen kuuluu myös kolme vähemmän karvaista perheenjäsentä.</p>
        
        <p>Taimi tykkää lenkkeillä kavereiden kanssa, saunoa ja maata sohvalla kainalossa. Taimi kuuntelee mielellään kaiken ikäisiä lukijoita ja kaikenlaisia kirjoja.</p>
    </div>
</div>
    
<div class="row">
    <h2>Lukukoirat esittäytyvät</h2>
    <div class="col-sm-6">
        <h3>Taimi</h3>
        <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/XbZ-qFO-p3E" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <p>Kuvaaja: Tommi Yläoutinen</p>
    </div>
 </div>    
</div>

<!-- END of: Content/lukukoirat.phtml -->