<!-- START of: Content/mediamaja_pelittaa.phtml -->

<? $this->headTitle('Mediamaja pelittää'); $this->content()->setHeading('Mediamaja pelittää'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Kouvolan pääkirjaston alakerrasta löytyy paikka nimeltä Mediamaja!</p>
        
        <p>Mediamajassa pääset pelaamaan pleikkarilla, xboxilla sekä tietysti monenlaisilla retrokonsoleilla aina kasibittisestä Nintendosta Sega Mega Driveen saakka. Perinteisempiäkin pelejä löytyy: hylly notkuu erilaisia lautapelejä, ja pöytätilaa on runsaasti niiden pelaamiseen. Haasta kaverit vaikka Huojuvassa tornissa tai Kimblessä. Takahuoneessa pääset paukuttamaan sähkörumpuja ja kokeilemaan kitaransoittoa - monenlaista tekemistä on siis tarjolla!</p>

        <figure>
            <img class="img-responsive" src="<?=$this->imageSrc('lanu/pelit.jpg')?>" alt="Super Mario 3 -videopelikasetti" width="600">
            <figcaption style="font-size: 0.8em;">Klassikoita pelivalikoimasta</figcaption>
        </figure>
        
        <br>
        <p>Mediamajan seiniltä löydät vaihtuvan taidenäyttelyn. Alle 30-vuotiaana sinullakin on mahdollisuus järjestää Mediamajassa oma näyttely!</p>
        
        <figure>
            <img class="img-responsive" src="<?=$this->imageSrc('lanu/366_kuvaa.jpg')?>" alt="Mediamajan valokuvaseinä" width="600">
            <figcaption style="font-size: 0.8em;">Mediamajan valokuvaseinä</figcaption>
        </figure>

        <br>
        <p>Lisäksi voit kaiken muun hauskan ohessa digitoida vaikka iskän vanhat VHS-kasetit isänpäivälahjaksi.</p>
        
        <p>Tuu käymään!</p>
        
        <p>Aukioloajat:
        <br>
        ma-to 12-18
        <br>
        pe 10-16
        </p>
        
        <p>Puh. 020 615 1333
        <br>
        Salpausselänkatu 33, 45100 Kouvola
        </p>
    </div>
</div>
   
<!-- END of: Content/mediamaja_pelittaa.phtml -->