<!-- START of: Content/pehmolelut.phtml -->

<? $this->headTitle('Kotkan pehmot'); $this->content()->setHeading('Kotkan pehmot'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Kotkan pääkirjaston lastenosastolla voi tavata jättiläispehmoja, ainakin pandan, yksisarvisen ja flamingon. 
        Kotkalaisen Hovinsaaren koulun oppilaat ovat keksineet pehmoille nimet. Panda on Boris, yksisarvinen Hattara ja flamingo Lila.</p>
        <br>
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/panda.jpg')?>" width="400" alt="Pandapehmolelu lastenosastolla"></p>
        <p>Moikka!</p> 
        <p>Olen Boris. Olen kotoisin naapurikaupungista Kouvolasta. 
        Kotkaan perheeni muutti jalkapallon vuoksi. Oikeastaan koko perheeni joko harrastaa tai työskentelee jalkapallon parissa. 
        Jalkapallo on minun rakkain ja tärkein harrastus. Toki voin sanoa, että olen urheiluhullu, sillä laji kuin laji sopii minulle. 
        Urheilun lisäksi teen vapaaehtoistyötä. Käyn äitini kanssa siivoamassa eläinsuojeluyhdistyksellä kissojen häkkejä ja ruokin niitä. 
        Meillä on myös kotona kotihoidossa väliaikaisesti kaksi yhdistyksen kissaa, jotka etsivät omaa kotia. Kissojen nimet ovat Pilli ja Pulla. 
        Luen paljon sarjakuvia. Minut tapaa usein kirjaston sarjakuvahyllyn luona. Arvatkaa, jääkö läksyt joskus tekemättä, kun harrastuksilta ei ehdi?
        </p>
        <br>
        <br>
        
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/yksisarvinen.jpg')?>" width="400" alt="Yksisarvispehmolelu lastenosastolla"></p>
        <p>Heippa!</p>
        <p>Minun nimi on Hattara. Minun elämänohjeeni on: ajattele aina positiivisesti. 
        Jos mehulasi kaatuu pöydälle, niin ajattelen, että saanpahan ainakin opetella siivoamaan. Se on tärkeä taito elämässä. 
        Jos kaverilla on uusi vaate, sanon siitä aina jotakin positiivista. Ihmiset ilahtuvat positiivisista sanoista ja minulle tulee hyvä mieli, kun näen jonkun olevan iloinen sanoistani. 
        Harrastan lukemista. Nyt kun olen oppinut itse lukemaan, lukemisen harrastaminen on helpompaa. Tosin voihan sitä aina kuunnella äänikirjoja.
        </p>
        <br>
        <br>

        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/flamingo.jpg')?>" width="800" alt="Flamingopehmolelu lastenosastolla"></p>
        <p>Moi!</p>
        <p>Olen Lila. Olen syntynyt Afrikassa Tansaniassa, mutta olen lentänyt jo melko pienenä Suomeen ja Kotkaan. 
        Olen innostunut koodaamisesta. Tulevaisuudessa minusta tuleekin varmasti pelikoodari. Vietän aikaani kavereiden kanssa ulkona esim. pyöräilemässä. 
        Käyn myös kirjastossa: luen kirjoja ja lehtiä sekä joskus pelaan. Olen innostunut alamäkipyöräilystä, mutta harrastuspaikkoja sille on harvassa.
        </p>
    </div>
</div>
   
<!-- END of: Content/pehmolelut.tml -->