<!-- START of: https://kyyti.finna.fi/Content/lanupoiminta_kesan_lukubingo_kouvola -->

<? $this->headTitle('Kesän lukubingo Kouvolassa'); $this->content()->setHeading('Kesän lukubingo Kouvolassa'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Pelaa lukubingoa ja voita kutkuttavia palkintoja!</p>
        <p>Hae bingolomake kirjastosta tai <a href="<?=$this->fileSrc('bingo_lomake_kouvola.pdf')?>">tulosta se tästä</a>.</p>
        <p>Yksi bingorivi eli neljän suora on neljä luettua kirjaa. Bingorivi voi muodostua vaakaan, pystyyn tai vinoon.</p>
        <p>Kirjoita lukemiesi kirjojen nimet bingon kääntöpuolelle ja palauta bingo mihin tahansa Kouvolan kirjastoon tai kirjastoauto Tesaurukseen 31.8.2023 mennessä.</p>
        <p>Kaikkien vähintään yhden bingorivin saaneiden kesken arvotaan kivoja palkintoja.</p>
        <p>Mukavaa lukukesää!</p>
        
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/tytto_lukee.jpg')?>" width="400" alt="Tyttö lukee"></p>
    </div>
</div>

<!-- END of: https://kyyti.finna.fi/Content/lanupoiminta_kesan_lukubingo_kouvola -->