<!--START of: https://kyyti.finna.fi/Content/lanupoiminta_lue_itsesi_pitsalle-->

<? $this->headTitle('Lue itsesi pitsalle!'); $this->content()->setHeading('Lue itsesi pitsalle!'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Lue kesän aikana ainakin neljä kirjaa, kirjoita kirjojen nimet ja kirjailijat
        lomakkeelle ja osallistu pitsalahjakortin arvontaan.</p>
        
        <!--<p><a href="<?= $this->fileSrc('Lue_pitsalle_23.pdf')?>" target="blank">Tulosta osallistumislomake tästä</a></p>-->
        <p>Lomakkeen saat Kotkan kaupunginkirjastoista.</p>
        
        <p>Osallistumisaikaa on 30.8.2024 asti.</p>
        
        <p>Jos haluat osallistua arvontaan, kirjoita lomakkeeseen yhteystietosi ja palauta se kirjastoon.</p>
        
        <p>Pitsalahjakortin arvontaan voivat osallistua alle 18-vuotiaat lapset ja nuoret.</p>
 
        <p>Lukuiloa ja onnea arvontaan!</p> 
        
        <br>
        
        <img class="img-responsive" src="<?=$this->imageSrc('lanu/pitsa_insta_2024.jpg')?>" width="300" alt="Pitsaviipale">
    </div>
</div>

<!--END of: https://kyyti.finna.fi/Content/lanupoiminta_lue_itsesi_pitsalle-->