<!-- START of: Content/pitsahaaste.phtml -->

<? $this->headTitle('Lue itsesi pitsalle!'); $this->content()->setHeading('Lue itsesi pitsalle!'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Lue kesän aikana ainakin kolme kirjaa, kirjoita kirjojen nimet ja kirjailijat
        lomakkeelle ja osallistu pitsalahjakortin arvontaan.</p>
        
        <a href="<?= $this->fileSrc('pitsahaaste.pdf')?>" target="blank">Tulosta osallistumislomake tästä</a></p>
        
        <p>Pitsalahjakortin arvontaan voivat osallistua alle 18-vuotiaat lapset ja nuoret.</p>
 
        <p>Lukuiloa ja onnea arvontaan!</p> 
        
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/pitsaviipale.jpg')?>" width="300" alt="Kaksi pitsaviipaletta"></p>
    </div>
</div>

<!-- END of: Content/pitsahaaste.tml -->