<!-- START of: Content/lanu_lukukipina_1-2_lk.phtml -->
<? $this->headTitle('lanu_lukukipina_1-2_lk'); $this->content()->setHeading('Lukukipinä (1.-2.lk)'); ?>

<div class="row">
    <div class="haasteluokka">
    <div class="col-sm-12">
        <h2>Kirjalistat</h2>
        <p>Alla on lukudiplomin kirjasuosituslistat. Ne auttavat sinua löytämään lukemista. 
        Voit kuitenkin aina lukea lukudiplomia varten näiden kirjalistojen ulkopuolelta oman 
        valitsemasi kirjan. Listasta näet kirjojen tiedot ja saatavuuden. 
        Kirjautumalla sisään voit myös varata kirjan. 
        Voit kuitenkin aina lukea lukudiplomia varten näiden kirjalistojen ulkopuolelta oman valitsemasi kirjan.</p>



    <h3>(1.-2.lk) listat</h3>
<?= $this->feed('lanu_lukukipina'); ?>  

    

</div>
</div>
   
    
<div class="col-sm-12">
    <h2>Lukudiplomin voi suorittaa opettajan ohjeiden mukaan koulussa tai tehdä itse kotona</h2>
        
    <p>Kirjastosta saa neuvoja hyvän kirjan löytämiseksi. Myös kaverin suositukset ja erilaiset kirjablogit ja -vinkit kannattaa hyödyntää.
Lukudiplomin voi suorittaa myös kuuntelemalla äänikirjoja tai
lukemalla e-kirjoja. Ne, joilla on todettu lukemiseste, voivat suorittaa diplomin Celia-kirjastoa käyttäen.
Kulta-diplomin saa lukemalla 7 kirjaa.
Platina-diplomin saa lukemalla 11 kirjaa.
Kun tavoite on täynnä, lukijalle annetaan lukudiplomi.
Kotona suoritetusta lukudiplomista saat diplomin kirjastosta, kun palautat lukudiplomilomakkeen kirjastoon.
</p>
    

    <h2>Tulostettavat</h2>

    <ul class="list-bullets">
        
    <li><a href="<?=$this->fileSrc('alakoulu_kirjalista_LUKUKIPINA_1-2_2023.pdf')?>" target="_blank">Kirjasuosituslista (pdf)</a></li>
    
    <li><a href="<?=$this->fileSrc('lukudiplomilomake_alakoulu_2023.pdf')?>" target="_blank">Lukudiplomilomake (pdf)</a></li> 
    
    <li><a href="<?=$this->fileSrc('Lukudiplomitodistus_lukukipinä_2023.pdf')?>" target="_blank">Lukudiplomi (pdf)</a></li>
    
    </ul>  	
        	
</div>
</div>

<!-- END of: Content/lanu_lukukipina_1-2_lk.phtml -->