<!-- START of: Content/lukuiloa.phtml -->

<? $this->headTitle('Lukuiloa talvihaasteesta'); $this->content()->setHeading('Lukuiloa talvihaasteesta'); ?>

<div class="row">
    <div class="col-sm-12">
        <p>Talvella on mukava ulkoilla, mutta jos sää on huono ja tossut kuivumassa jo aamun pulkkamäestä, on kiva käpertyä sohvalle lueskelemaan, 
        katsomaan elokuvaa tai pelaamaan kavereiden kanssa. Kirjat, leffat, lautapelit ja konsolipelit löydät kätevästi kirjastosta.</p>
        <p>Voit myös osallistua kirjastojen yhteiseen kivaan talvihaasteeseen. Haasteessa luetaan aikuisen kanssa, askarrellaan, tehdään maistuvia välipaloja ja tutkitaan eläinten jälkiä. 
        Voit hakea haastelomakkeen kirjastosta ja suorittaa sen ihan omaksi iloksesi.</p>
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/talvihaaste.jpg')?>" width="600" alt="Talvihaasteen lomake"></p>
        <p>Maukkaita välipalavinkkejä löydät vaikkapa Inna Somersalon Makumetkuja murusille -kirjasta. Miltä kuulostaisi vaikkapa Niilo Pöllön pannukakku? 
        Välipalaa nauttiessa voi lukea vaikkapa alpakoista ja laamoista Maire Soiluvan kirjasta Avuliaat alpakat ja lempeät laamat luonnossa ja ihmisten apuna. 
        Varo, ettet tipauta hilloa kirjalle! Pannukakun jälkeen jaksaakin sitten heittäytyä luovaksi taiteilijaksi tai taitavaksi eläintutkijaksi. 
        Näihin puuhiin vinkkejä saa muun muassa Claudia Boldtin kirjasta Tutki ja tee taidetta sekä Tore Fonstadin Pienestä jälkikirjasta.</p>
        <p><img class="img-responsive" src="<?=$this->imageSrc('lanu/talvihaastekirjat.jpg')?>" width="600" alt="Talvihaasteen kirjoja pöydällä"></p>
        <p>Lisää kirjavinkkejä saat paitsi talvihaastelomakkeesta myös omasta kirjastostasi. Voit myös katsoa Kirjastokaistan vinkkivideon, 
        jolla Henriika Tulivirta ja lukukoira Astrid vinkkaavat parhaita talvikirjoja.</p>
        
        <p><div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://player.vimeo.com/video/511607794" allowfullscreen></iframe>
        </div></p>
        <p>Mukavia talvisia lukuhetkiä!</p>
    </div>
</div>

<!-- END of: Content/lukuiloa.tml -->