<!-- START of: Content/lukemalla_jaksaa.phtml -->
<? $this->headTitle('Lukemalla jaksaa');?>

    <div class="lukemallajaksaa">
        <div class="row">
            <div class="col-sm-2 col-xs-2">
                <img src="<?=$this->imageSrc('lukemalla_jaksaa/sivun_ylakulma.svg')?>" alt="Vinoja eri värisiä koristeviivoja" />
            </div>
            <div class="col-sm-8 col-xs-9">
                <div class="otsikko-logo">
                    <img src="<?=$this->imageSrc('lukemalla_jaksaa/lukemalla_jaksaa_yhdistelma_logo_rgb.png')?>" alt="Lukemalla jaksaa -hankkeen logo" />
                </div>
            </div>
        </div>
        <div class="row">
            <h1><div class="paaotsikko">Lukemalla jaksaa</div></h1>
            <h2><div class="alaotsikko">Lukuharrastuksen edistämistä</div></h2>
            <div class="col-sm-7">
                <div class="teksti-sisalto">
                    <p>Haluaisitko edistää yhteisösi lukuharrastusta ja kokea voimaannuttavia hetkiä? Nyt se on mahdollista Kouvolan pääkirjastossa. Ilmaiseksi. 
                    Tarjoamme aikuisryhmille parituntisia elämyksiä, jotka yhdistävät kirjallisuuden ja yhteisöllisyyden.
                    Valittavana on kaksi houkuttelevaa pakettia:  </p>
                    <ol>
                        <li>Lukuvinkkaus ja pakopeli: tämä paketti tarjoaa osallistujille mahdollisuuden uppoutua 
                            kirjallisuuden maailmaan lukuvinkkaajan johdolla. Sen jälkeen ratkotaan yhdessä haasteita pakopelissä.</li>
                        <li>Voimaannuttava kirjoittaminen ja pakopeli: ohjattu kirjoittaminen on matalan kynnyksen itsensä ilmaisua periaatteella 
                            kaikki osaa ja tämä on minulle itselleni. Lopuksi ryhmä testaa luovuuttaan pakopelissä.</li>
                    </ol>
                    <p>Kirjallisuusteemaiset pakopelit ovat pienehköjä, matkalaukkuun mahtuvia kokonaisuuksia, jotka on tarkoitettu pelattavaksi 7 – 15 hengen ryhmissä. 
                        Maksimi ryhmäkoko yhdelle tapahtumakerralle on 30 osallistujaa.</p>
                    <p>Uskomme, että aina on tilaa uusille lukuelämyksille ja voimaannuttaville hetkille yhdessä.</p>
                    
                    <div class="yhteystiedot">
                        <p>Raija Hasu 020 615 5786, raija.hasu(at)kouvola.fi</p>
                        <p>Sanna Olkkonen 020 615 6147, sanna.olkkonen(at)kouvola.fi</p>
                    </div>
                    <p><b>Huomioi</b></p>
                   <p>Kirjasto toteuttaa myös 1 – 3 hengen yrityksille suunnattuja yhteistilaisuuksia. Olemme keväälle varanneet seuraavat päivät:</p>
                   <div class="yhteystiedot">
                       <p>tiistaina 21.5.2024 klo 10 – 12.30</p>
                       <p>keskiviikko 22.5.2024 klo 17 – 19.30</p>
                   </div>
                   <p>Täytä ilmoittautumislomake, jos kiinnostuit.</p>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="image-stack">
                    <div class="image-stack__item--top">
                        <a href="https://kyyti.finna.fi/Feedback/Form/Lukemalla_jaksaa?lng=fi" alt="Linkki yhteydenottolomakkeeseen">
                        <div class="speech-bubble">
                            <img src="<?=$this->imageSrc('lukemalla_jaksaa/puhekupla.svg')?>" alt="Puhekuplakuvan klikkaaminen avaa linkin yhteydenottolomakkeeseen" />
                            <div class="overlay-text">
                                Yhteydenottolomakkeen saat täytettyä tästä.
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="image-stack__item--bottom">
                        <img src="<?=$this->imageSrc('lukemalla_jaksaa/lukemisen-voimalla-iloinen.png')?>" alt="tyytyväinen työntekijä pitelemässä kirjoja" />
                    </div>
                </div>
            </div>
        </div>
        
        
        <div class="row">
            <div class="teksti-sisalto">
                <div class="col-sm-12">
                    <p>
                        Kouvolan kaupunginkirjaston Lukemalla jaksaa -hankkeen mahdollistaa aluehallintoviraston myöntämä valtionavustus. 
                        Hankkeen tavoitteena on aikuisten työikäisten lukemisen ja hyvinvoinnin edistäminen. Kirjasto haluaa kokeilla uutena keinona tavoittaa työikäiset työaikanaan. 
                        Hankkeessa työikäiset pyritään tavoittamaan tarjoamalla yrityksille valmis tyhy-päivän toiminnallinen paketti. Työikäisistä on kaupungissamme myös paljon työttöminä 
                        ja erilaisina kuntoutujina. Heidät hanke pyrkii saamaan em. pakettien äärelle kolmannen sektorin toimijoiden avulla.
                    </p>
                </div>
            </div>
            <div class="teksti-sisalto">
                <div class="col-sm-12">
                    <p><b>Erinomaisia syitä lukemiselle:</b></p>
                    <div class="enemman-lukemisesta-linkit">
                        <ol>
                            <li><a href="https://kotiliesi.fi/ihmiset-ja-ilmiot/kulttuuri/lukemisen-terveyshyodyt/" alt="Linkki Kotilieden sivulle lukemisen hyödyistä">Kotiliesi: "Lukemisen terveyshyödyt: 7 syytä, miksi kannattaa lukea kirjoja"</a></li>
                            <li><a href="https://suomenkirjastoseura.fi/kirjastolehti/kirjavinkkari-lukemisesta-on-hyotya/" alt="Linkki Kirjastolehden sivulle lukemisen hyödyistä">Kirjastolehti: "Kirjavinkkari: Lukemisesta on hyötyä"</a></li>
                            <li><a href="https://suomenkuvalehti.fi/tiede-ja-teknologia/kirjastokortti-pidentaa-ikaa/?shared=1028471-e6f8616f-1" alt="Linkki Suomen Kuvalehden sivulle lukemisen hyödyistä">Suomen Kuvalehti: "Parnasso: Ei enää mutua vaan tutkittua tietoa: Mitä enemmän lukee kirjoja, sitä kauemmin elää – kirjastokorttikin lisää ikää"</a></li>
                            <li><a href="https://lukukeskus.fi/10-faktaa-lukemisesta-2020/#fakta-1" alt="Linkki Lukukeskuksen sivulle lukemisen hyödyistä">Lukukeskus: "10 faktaa lukemisesta 2020"</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="logo-section">
            <div class="leimasin-logo">
                <img src="<?=$this->imageSrc('lukemalla_jaksaa/lukemalla-jaksaa-leimasin-thin-40mm.png')?>" alt="Lukemalla jaksaa -hankkeen leimasin-logo"/>
            </div>
            <div class="kouvola-logo">
                <img src="<?=$this->imageSrc('lukemalla_jaksaa/Kouvola_logo_musta.png')?>" alt="Kouvolan kaupungin logo"/>
            </div>
            <div class="oikea-kulma-koristeviivat">
                <img src="<?=$this->imageSrc('lukemalla_jaksaa/sivun_alakulma.svg')?>" alt="Vinoja eri värisiä koristeviivoja"/>
            </div>
        </div>
    </div>



<!-- END of: Content/lukemalla_jaksaa.tpl -->