<!-- START of: Content/lukuhaaste_lukudiplomi_fi.phtml -->
<? $this->headTitle('Lukuhaaste-lukudiplomi'); $this->content()->setHeading('Lukuhaaste-lukudiplomi'); ?>

<div class="row">
    <div class="haasteluokka">
    <div class="col-sm-7">
        <h2>Vinkkilistat</h2>
        <p>Täältä löydät Lukuhaasteen vinkkilistat. Listoja on kuutta eri teemaa ja ne on jaoteltu kolmeen eri vaikeustasoon.
        Kirjojen kansikuvia naputtamalla näet paperikirjojen tiedot ja saatavuuden.</p>



    <h2>Timanttisia taitoja</h2>
    <h3>Vähemmän haastetta</h3>
  <?= $this->feed('lukudiplomi_timanttisia_taitoja_helppo'); ?>  
 


     <h3>Sopivasti haastetta</h3>
       <?= $this->feed('lukudiplomi_timanttisia_taitoja_keskitaso'); ?> 
    



    <h3>Enemmän haastetta</h3>
        <?= $this->feed('lukudiplomi_timanttisia_taitoja_haastava'); ?> 


<br>
<br>
<br>


    <h2>Eläimellistä menoa</h2>
    <h3>Vähemmän haastetta</h3>
        <?= $this->feed('lukudiplomi_elaimellista_menoa_helppo'); ?>




     <h3>Sopivasti haastetta</h3>
        <?= $this->feed('lukudiplomi_elaimellista_menoa_keskitaso'); ?>
    

    <h3>Enemmän haastetta</h3>
        <?= $this->feed('lukudiplomi_elaimellista_menoa_haastava'); ?>
 


<br>
<br>
<br>

<h2>Matkalla maailman ympäri</h2>
    <h3>Vähemmän haastetta</h3>
<?= $this->feed('lukudiplomit_matkalla_maailman_ympari_helppo'); ?> 
    



     <h3>Sopivasti haastetta</h3>
<?= $this->feed('lukudiplomit_matkalla_maailman_ympari_keskitaso'); ?> 



    <h3>Enemmän haastetta</h3>
<?= $this->feed('lukudiplomit_matkalla_maailman_ympari_haastava'); ?>



<br>
<br>
<br>


    <h2>Seikkailua etsimässä</h2>
    <h3>Vähemmän haastetta</h3>
<?= $this->feed('lukudiplomit_seikkailua_etsimassa_helppo'); ?>
    



     <h3>Sopivasti haastetta</h3>
<?= $this->feed('lukudiplomit_seikkailua_etsimassa_keskitaso'); ?> 
    



    <h3>Enemmän haastetta</h3>
<?= $this->feed('lukudiplomit_seikkailua_etsimassa_haastava'); ?> 
    


<br>
<br>
<br>


    <h2>Outoja juttuja</h2>
    <h3>Vähemmän haastetta</h3>
<?= $this->feed('lukudiplomit_totta_vai_tarua_helppo'); ?> 
    



     <h3>Sopivasti haastetta</h3>
<?= $this->feed('lukudiplomit_totta_vai_tarua_keskitaso'); ?> 
    



    <h3>Enemmän haastetta</h3>
<?= $this->feed('lukudiplomit_totta_vai_tarua_haastava'); ?>
    


<br>
<br>
<br>


    <h2>Ystävyyttä ja tunteita</h2>
    <h3>Vähemmän haastetta</h3>
<?= $this->feed('lukudiplomit_ystavyytta_ja_tunteita_helppo'); ?> 
    



     <h3>Sopivasti haastetta</h3>
<?= $this->feed('lukudiplomit_ystavyytta_ja_tunteita_keskitaso'); ?> 
    



     <h3>Enemmän haastetta</h3>
<?= $this->feed('lukudiplomit_ystavyytta_ja_tunteita_haastava'); ?> 
</div>
</div>

   
    
<div class="col-sm-5">
    <h2>Lukuhaaste innostaa lukemaan esi- ja alkuopetuksessa!</h2>
        
    <p>Esi- ja alkuopetuksessa on mahdollisuus halutessaan suorittaa Lukuhaastetta</p>
    
    <p>Lukuhaasteen suorittaminen on yksi lukemista lisäävä ja lukemaan innostava keino</p>
    
    <p>Lukuhaasteessa on <b>kolme osiota</b>; luemme ryhmässä, luemme yhdessä perheen kanssa ja luen itse.</p>
    
    <p><b>Luemme ryhmässä</b>- osiossa joko opettaja lukee lapsille tai lapset lukevat yhdessä vähintään neljä kirjaa. 
    <b>Luemme yhdessä</b> perheen kanssa- osiossa lapselle luetaan vähintään kaksi kirjaa kotona. <b>Luen itse- osiossa</b> lapsi lukee itse tai kertoo aikuiselle/toiselle lapselle vähintään kaksi kirjaa. Lukuhaasteessa suoritetaan lukuvuoden aikana vähintään kahdeksan kirjaa.</p>

    <p>Jokaiselle lapselle tulostetaan oma <b>Lukuhaaste-vihko</b>. Esiopetukseen, ensimmäiselle ja toiselle luokalle on oma Lukuhaaste-vihkonsa.</p>

    <p>Kirjasto on koonnut <b>kuusi erilaista kirjalistaa</b>, joista voi löytää kirjavinkkejä ja luettavaa. Kirjan voi valita myös oman tai ryhmän mielenkiinnon mukaan listan ulkopuolelta.</p>

    <p>Yhteisesti luetun kirjan jälkeen <b>opettajan tehtävälistalta</b> valitaan tehtävä. Tehtävät on jaoteltu oppimiskokonaisuuksien ja oppiaineiden mukaan. 
    <b>Kotiin</b> on tehty <b>pienempi</b> tehtävälista, josta lapsi tai perhe voi halutessaan valita tehtävän. Tämä lista löytyy Lukuhaaste-vihkosta. 
    Ryhmässä luettujen kirjojen jälkeen tehdään aina yhdessä tehtävä.</p>
    
    <p>Lukuhaaste-vihkossa on <b>värityskuva</b>, josta lapsi värittää osion kirjan lukemisen jälkeen.</p>
    
    <p>Jos lapsi on innokas lukemaan enemmän kirjoja, on värityskuvaan saatavilla lisäosia, <b>Jekku-hiiriä</b>. Jokaiselle luokka-asteelle on oma värityskuvansa, 
    johon liittyy myös <b>pieni tarina</b> motivoimaan lasta lukemisessa. Opettaja voi lukea tarinan ennen Lukuhaasteen aloittamista. Tarinaan voi palata myös Lukuhaasteen aikana.</p>
    
    <p>Kun Lukuhaaste on suoritettu, opettaja voi tulostaa lapselle <b>kirjanmerkin</b>. Ryhmä voi myös pitää Lukuhaaste-juhlat. 
    <b>Luetut kirjat</b> kirjataan ylös <b>lapsen omaan listaan</b>.</p>
    
    <p>Lukuhaasteen kuvat on kuvittanut Elina Niittynen ja tarinat on kirjoittanut Maija Niinimäki.</p>
    
    <p>Opettajille tarkoitetut tehtävälistat, kirjanmerkit ja lisätietoa lukuhaasteesta saat täältä: <a href="https://peda.net/kouvola/perusopetus/hankkeet/lukeva-kouvola/lukuhaaste">Lukeva Kouvola lukuhaaste peda.netissä</a></p>
    

    <h2>Linkit ja tulostettavat</h2>

    <ul class="list-bullets">
    <li><a href="https://peda.net/kouvola/perusopetus/hankkeet/lukeva-kouvola/lukuhaaste">Lukeva Kouvola lukuhaaste peda.netissä</a> </li>
        
    <li><a href="<?=$this->fileSrc('Lukeva_Kouvola_lukuhaaste_1_luokka_print.pdf')?>" target="_blank">Lukeva Kouvola lukuhaaste 1. luokka (pdf)</a></li>
    
    <li><a href="<?=$this->fileSrc('Lukeva_Kouvola_lukuhaaste_2_luokka_print.pdf')?>" target="_blank">Lukeva Kouvola lukuhaaste 2. luokka (pdf)</a></li> 
    
    <li><a href="<?=$this->fileSrc('Lukeva_Kouvola_lukuhaaste_eskarit_print.pdf')?>" target="_blank">Lukeva Kouvola lukuhaaste eskarit (pdf)</a></li> 
    
    </ul>  	
        	
</div>
</div>

<!-- END of: Content/lukuhaaste_lukudiplomi_fi.phtml -->