<!-- START of: Content/lukuliekki-peli.phtml -->
<? $this->headTitle('Lukuliekki-peli '); $this->content()->setHeading('Lukuliekki-peli '); ?>

<div class="row">
    <div class="haasteluokka">
    <div class="col-sm-12">
        <h2>Lukuliekki - lukemiseen innostava peli käynnistyy Kymenlaaksossa 1.9.2024</h2>
     
     
    <p><img src="<?=$this->imageSrc('lanu_lukuliekki/Hahmojanetti.png')?>" alt="Nuori nainen lukee kirjaa kirjastossa" /></p>    
    <p>Lukuliekissä kolmos- ja nelosluokat kisaavat keskenään lukemalla mahdollisimman monta kirjaa 1.9.2024 - 30.4.2025 klo 12 välisenä aikana. 
Suhteessa eniten lukenut luokka julistetaan Lukuliekin haltijoiksi ja heidät palkitaan VIP kirjastobileillä, jotka suunnitellaan yhdessä opettajan ja lähikirjaston kanssa.</p> 
 
<p>Mikä Lukuliekki on?</p>  
<p>Lukuliekki on innostava pelillinen ympäristö, jossa oppilaat saavat kirjavinkkejä 7 eri aihealueesta: runot, tarinat, sadut, tietokirjat, sarjakuvat, helppoa & nopeaa,
vapaavalintaiset & ylimääräiset. Luettavan kirjan voi poimia myös vinkkilistojen ulkopuolelta. Oppilaat lukevat kirjan ja
lisäävät sen nimen peliin. Lukusuorituksesta he saavat kolikoita, joilla voivat tuunata omaa pelihahmoaan. 
Kolikoita saa myös pelaamalla minipelejä, jotka liittyvät kirjastoon tai kirjallisuuteen. </p> 
 
<p>Mitä peli vaatii opettajalta?</p>  
<p>Opettaja saa peliin omat tunnukset, joiden kautta hän pääsee lisäämään oppilaat peliin. Peli luo oppilaille tunnukset, joilla he pääsevät pelaamaan.  
Tämän lisäksi opettaja käy pelissä tasaisin väliajoin hyväksymässä oppilaiden lukusuoritukset. Peliä on helppo käyttää, eikä se vie aikaa häiritsevästi.</p> 
 
<p>Miten pääsee mukaan?</p> 
<p>Ota yhteyttä omaan lähikirjastoosi, niin luomme sinulle tunnukset. Tarvittaessa autamme myös pääsemään pelissä alkuun.</p>  
 
<p>Pidetään yhdessä lukuliekki roihuamassa!</p>
 
<p><a href="https://kyyti.lukuliekki.fi" target="_blank">Lukuliekki-peli löytyy osoitteesta kyyti.lukuliekki.fi.</a></p>

<h2>Liitteet</h2>

    <ul class="list-bullets">
        
    <li><a href="<?=$this->fileSrc('Peliohjeet_oppilaalle.pdf')?>" target="_blank">Peliohjeet oppilaalle (pdf)</a></li>
    
    <li><a href="<?=$this->fileSrc('Lukuliekkiohjeet_opettaja.pdf')?>" target="_blank">Peliohjeet opettajalle (pdf)</a></li> 
    </ul>  
</div>
    </div>
        </div>



<!-- END of: Content/lukuliekki-peli.phtml -->