<!-- START of: Content/lukuhaaste.fi.phtml -->

<? $this->headTitle('Lukuhaaste 2025'); $this->content()->setHeading('Lukuhaaste 2025'); ?>
<div class="row">
    <div class="col-xs-12 hidden-sm hidden-md hidden-lg" style="margin-bottom: 30px;">  
        <p><img src="<?=$this->imageLink('lukuhaaste24_banneri_pieni.jpg');?>" alt=""/></p>
    </div>
</div>
   
<div class="row">
    <div class="col-sm-12 hidden-xs" style="margin-bottom: 30px;">
        <p><img src="<?=$this->imageLink('lukuhaaste25_banneri.jpg');?>" alt=""/></p>
        <!--<p><img src="<?=$this->imageLink('lukuhaaste24_banneri.jpg');?>" alt=""/></p>-->
    </div>
</div>

<div class="row">
    <div class="haasteluokka">
    <div class="col-xs-12 col-sm-7">
        <h2>Osallistu haasteeseen</h2>
        <p>Voit osallistua lukuhaasteeseen joko sähköisellä lomakkeella tai tulostamalla lomakkeen ja palauttamalla sen kirjastoon.</p>
        <ul class="list-bullets">
            <li><a href="https://link.webropolsurveys.com/Participation/Public/f45e6565-85bb-4fdc-8e04-05c7d5db6db4?displayId=Fin3259640" target="blank">Lähetä sähköinen lomake (webropolsurveys.com)</a></li>
            <li><a href="<?= $this->fileSrc('lomake_2025_tulostettava.pdf')?>" target="_blank">Tulosta lomake (pdf)</a></li>
            <li><a href="<?= $this->fileSrc('kyyti-lukuhaaste_2025_tulostettava.pdf')?>" target="_blank">Lukuhaasteen esite (pdf)</a>. Esitteitä saa myös kirjastosta.</li>
        </ul>

        <h2>Kirjat</h2>
        <p>Kirjojen kansikuvia napauttamalla näet paperikirjojen tiedot ja saatavuuden. Monia haasteen kirjoja voi lainata myös äänikirjana sekä e-kirjana tai e-äänikirjana E-kirjastosta.</p>
        
        <h3>Tammikuu</h3>
        <p>Vinkkilista: 150 vuotta Anni Swanin syntymästä</p><?= $this->feed('lukuhaaste_25_01_150_vuotta_Anni_Swanin_syntymasta'); ?> 
        <p>Vaihtoehto: 110 vuotta Anni Polvan syntymästä</p><?= $this->feed('lukuhaaste_25_01_110_vuotta_anni_polvan_syntymasta'); ?>
        <br>
        <h3>Helmikuu</h3>
        <p>Vinkkilista: Kaunokirjallisuutta Tanskasta</p><?= $this->feed('lukuhaaste_25_02_kaunokirjallisuutta_tanskasta'); ?>
        <p>Vaihtoehto: Kirja vieraasta maanosasta</p><?= $this->feed('lukuhaaste_25_02_kirja_vieraasta_maanosasta'); ?>
        <br>
        <h3>Maaliskuu</h3>
        <p>Vinkkilista: Hoitoalalle sijoittuva romaani</p>
        <?= $this->feed('lukuhaaste_25_03_hoiva_ala'); ?>
        <p>Vaihtoehto: Hyvinvointia käsittelevä tietokirja</p><?= $this->feed('lukuhaaste_25_03_hyvinvointia_kasitteleva_tietokirja'); ?>
        <br>
        <h3>Huhtikuu</h3>
        <p>Vinkkilista: Samannimisistä kirjoista toinen, vaihtoehto 1</p><?= $this->feed('lukuhaaste_25_04_samannimisista_kirjoista_toinen_vaihtoehto_1'); ?> 
        <p>Vaihtoehto: Samannimisistä kirjoista toinen, vaihtoehto 2</p><?= $this->feed('lukuhaaste_25_04_samannimisista_kirjoista_toinen_vaihtoehto_2'); ?>  
        <br>
        <h3>Toukokuu</h3>
        <p>Vinkkilista: Romaanissa on juhlat</p><?= $this->feed('lukuhaaste_25_05_romaanissa_on_juhlat'); ?> 
        <p>Vaihtoehto: Tietokirja juhlan viettämisestä</p><?= $this->feed('lukuhaaste_25_05_tietokirja_juhlan_viettamisesta'); ?> 
        <br>
        <h3>Kesäkuu</h3>
        <p>Vinkkilista: Psykologinen jännityskirja</p><?= $this->feed('lukuhaaste_25_06_psykologinen_jannityskirja'); ?>
        <p>Vaihtoehto: Historiallinen jännityskirja</p><?= $this->feed('lukuhaaste_25_06_historiallinen_jannityskirja'); ?>
        <br>
        <h3>Heinäkuu</h3>
        <p>Vinkkilista: Runokirja</p><?= $this->feed('lukuhaaste_25_07_runokirja'); ?>
        <p>Vaihtoehto: Elämäkerta runoilijasta</p><?= $this->feed('lukuhaaste_25_07_elamakerta_runoilijasta'); ?>
        <br>
        <h3>Elokuu</h3>
        <p>Vinkkilista: Romaanissa ilmasto- tai ympäristonäkökulma</p><?= $this->feed('lukuhaaste_25_08_romaanissa_ilmasto_tai_ymparistonakokulma'); ?>
        <p>Vaihtoehto: Tietokirja ilmastosta tai ympäristöstä</p><?= $this->feed('lukuhaaste_25_08_tietokirja_ilmastosta_tai_ymparistosta'); ?>
        <br>
        <br>
        <h3>Syyskuu</h3>
        <p>Vinkkilista: Kymenlaaksolaisen kirjailijan kirjoittama kirja</p><?= $this->feed('lukuhaaste_25_09_kymenlaaksolaisen_kirjailijan_kirjoittama_kirja'); ?>
        <p>Vaihtoehto: Kotiseutusi kirjailijan kirjoittama kirja</p>
        <p>Oletko kotoisin muualta kuin Kymenlaaksosta? Lue kirja, jonka on kirjoittanut samalta seudulta kotoisin oleva kirjailija.</p>
        <br>
        <h3>Lokakuu</h3>
        <p>Vinkkilista: Kotimainen klassikkoromaani</p><?= $this->feed('lukuhaaste_25_10_kotimainen_klassikkoromaani'); ?>
        <p>Vaihtoehto: Ulkomainen klassikkoromaani</p><?= $this->feed('lukuhaaste_25_10_ulkomainen_klassikkoromaani'); ?>
        <br>
        <h3>Marraskuu</h3>
        <p>Vinkkilista: Vuonna 2025 julkaistu kirja</p><?= $this->feed('lukuhaaste_25_11_vuonna_2025_julkaistu_kirja'); ?> 
        <p>Vaihtoehto: Kirja, jonka lukemista olet kauan suunnitellut</p>
        <p>Monella meistä on lista tai pino kirjoista, joita on jo hyvän aikaa aikonut lukea. Tartu tällaiseen kirjaan nyt!</p>
        
        <br>
        <h3>Joulukuu</h3>
        <p>Vinkkilista: Jouluinen romaani</p><?= $this->feed('lukuhaaste_25_12_jouluinen_romaani'); ?>  
        <p>Vaihtoehtoinen lista: Joulusatu</p><?= $this->feed('lukuhaaste_25_12_joulusatu'); ?>
    </div>       

    <div class="col-xs-12 col-sm-5">
    <h2>Tietoa lukuhaasteesta</h2>
        
    <p>Kyyti-lukuhaaste on Kyyti-kirjastojen aikuisten lukuhaaste. Se 
    suoritetaan lukemalla tai kuuntelemalla 12 kirjaa, yksi kustakin 
    kuukausittaisesta teemasta. Jokaiselle pääteemalle on myös tarjolla 
    vaihtoehtoinen teema. Haastevihko sisältää muutamia kirjavinkkejä, 
    mutta luettavaksi voi valita minkä tahansa teemaan sopivan teoksen. 
    Haasteen voi aloittaa milloin vain ja suorittaa omaan tahtiin. Kaikki haastelomakkeen perjantaihin 9.1.2026 mennessä palauttaneet 
    osallistuvat kirjakaupan lahjakortin arvontaan.</p>
    <p>Jos haluat ajankohtaista tietoa lukuhaasteesta, voit liittyä <a href="https://www.facebook.com/groups/kyytilukuhaaste" target="blank">lukuhaasteen Facebook-ryhmään</a>.</p>
    
    <div id="mc_embed_signup">
        <form action="https://finna.us1.list-manage.com/subscribe/post?u=8d171ce1cd7f49e14efcf8aac&amp;id=47de39e453" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
        	<h2>Liity lukuhaasteen postituslistalle (Mailchimp -versio)</h2>
        	<p>Saat kuukausittaisen lukuhaastekirjeen kirjoittamalla sähköpostiosoitteesi
            Sähköpostiosoite-kenttään ja napauttamalla <strong>Tilaa lukuhaastekirje</strong> -painiketta.</p>
            
            <p>Lukuhaastekirje sisältää haastetiimin tervehdyksen, kuukauden teemoja käsittelevän alustuksen ja laajan kirjavinkkilistan. 
            Kirjeet ovat saatavilla myös Kyyti-Finnasta ja paperisena kirjastosta.</p>
            <div class="mc-field-group">
        	<label for="mce-EMAIL">Sähköpostiosoite </label>
        	<br>
        	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" size="30">
            </div>
            	<div id="mce-responses" class="clear">
            		<div class="response" id="mce-error-response" style="display:none"></div>
            		<div class="response" id="mce-success-response" style="display:none"></div>
            	</div>
            	<br>
                <div style="padding: 0;" class="btn btn-primary"><input type="submit" value="Tilaa lukuhaastekirje" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary"></div>
            </div>
        </form>
        <form method="post" action="/Feedback/Form/LukuhaasteEmailSubscription" class="dynamic-form" id="LukuhaasteEmailSubscription">
            <h2>Liity lukuhaasteen postituslistalle (Finnan oma lomake)</h2>
        	<p>Saat kuukausittaisen lukuhaastekirjeen klikkamalla <strong>Tilaa lukuhaastekirje</strong> -painiketta ja täyttämällä avautuvan lomakkeen.</p>
            
            <p>Lukuhaastekirje sisältää haastetiimin tervehdyksen, kuukauden teemoja käsittelevän alustuksen ja laajan kirjavinkkilistan. 
            Kirjeet ovat saatavilla myös Kyyti-Finnasta ja paperisena kirjastosta.</p>
            
            <div style="padding: 0; margin-top:10px;" class="btn btn-primary"><input type="submit" value="Tilaa lukuhaastekirje" name="subscribe" id="lukuhaaste-subscribe" class="btn btn-primary"></div>
        </form>
    </div>
    
    </div>
</div>
</div>

<!-- END of: Content/lukuhaaste.fi.tpl -->
