<!-- START of: Content/mediamaja_fi.phtml -->
<? $this->headTitle('Kouvolan Mediamaja'); $this->content()->setHeading('Kouvolan Mediamaja'); ?>

<div class="row">
    <div class="col-sm-12">
    <p><img src="<?=$this->imageSrc('palvelut/mediamaja_banneri.jpg')?>" alt="3D-tulostimella tulostettuja satuhahmoja 3D-tulostimen edessä" /></p>
    <h2>Esittely</h2>
    <p>Kouvolan pääkirjaston alakerrassa sijaitseva Mediamaja on monitoiminen avoin tila erilaisten tapahtumien, kuten luentojen ja mediakasvatuksellisten työpajojen, järjestämiseen. 
    Mediamajan osaava henkilökunta antaa digiopastusta digilaitteiden ja digitaalisten palveluiden päivittäiseen käyttöön. 
    Meillä on myös laitteita, joilla voit omatoimisesti digitoida vanhempaa aineistoasi, esim. VHS-videoita, valokuvia ja C-kasetteja, digitaaliseen muotoon.</p>
    <p><a href="<?=$this->url('content-page',  ['page' => 'digituki'])?>"><b style="color: #007091;">Tutustu Kouvolan kirjastojen tarjoamaan digitukeen</b></a></p>
    
    <p>Mediamaja on avoinna:</p>
    <ul class="list-bullets">
        <li>Ma-To 11-17. Klo 15-17 ajanvarauksella.</li>
        <li>Pe 10-16. Klo 15-16 ajanvarauksella.</li>
    </ul>
    
    <p>Yhteystiedot</p>
    <ul class="list-bullets">
        <li>Salpausselänkatu 33, 45100 Kouvola</li>
        <li><a href="tel:+358206151333">020 615 1333</a></li>
        <li><a href="mailto:mediamaja@kouvola.fi">mediamaja@kouvola.fi</a></li>
    </ul>

    <h2>Osallistu ja vaikuta</h2>
    <p>Mediamajassa järjestetään tapahtumia konserteista peli-iltoihin. Seiniä koristavat parin kuukauden välein vaihtuvat näyttelyt. Jos sinulla on idea tapahtumasta tai haluat järjestää näyttelyn töillesi, ota yhteyttä. Tapahtumia, pelaamista ja videoesityksiä varten Mediamajassa on liikuteltava äänentoistolaitteisto.</p>
    
    <h2>Kuvaa ja editoi</h2>
    <p>Toteuta visiosi ja lainaa viikonlopuksi videokamera. Mediamajassa voit editoida videomateriaalia tai tehdä kuvankäsittelyä Adoben uusimmilla ohjelmilla.</p>
    
    <h2>Äänitä ja tuota</h2>
    <p>Nauhoita bändisi demo tai sylje riimit raidoille Mediamajan studiossa. Käytössäsi on myös Roland TD-11 -sähkörummut, midikoskettimisto, basso, akustinen kitara, sekä sähkökitara efektipedaaleineen. Henkilökunta opastaa alkuun.</p>
    
    <h2>Pelaa ja relaa</h2>
    <p>Nappaa ohjain kouraan ja pelaa xboxilla tai pleikkarilla. Retropeleistä kiinnostuneille meiltä löytyy myös kasibittinen Nintendo sekä Commodore-tietokone. Jos videopelit eivät nappaa, niin istu alas ja pelaa kaverisi kanssa lautapelejä tai lysähdä Fatboy-säkkituoliin ja ota vaan iisisti. Voit myös surffailla netissä ja tutustua uusiin ihmisiin.</p>
    
    <h2>Lainattavat esineet</h2>
    <p>Voit lainata kirjastokortilla Mediamajasta videokameroita (Canon Legria FS200 ja HF200), järjestelmäkameran (Canon 550D), piirtopöydän (Trust Slimline), 
    näytön kalibroitilaitteen (Datacolor Spyder4Elite) äänikortin äänittämistä varten (M-audio Fast Track) sekä Nintendo Wiin.</p>
    
    <h2>3D-tulostus</h2>
    <p>3D-tulostin Ultimaker 3 valmistaa fyysisiä esineitä digitaalisista malleista. Voit valita oman tulostettavan esineen internetin mallinnuspankeista tai suunnitella oman mallin. 
    Mediamajan henkilökunta antaa vinkkejä mallinnuksen itseopiskeluun. Tulosteen hinta on 2 € / tuloste, max. varausaika on 3 tuntia. 
    Suosittelemme valitsemaan mallin etukäteen. Sivustoja mallien lataamiseen: <a href="https://www.thingiverse.com" target="blank">www.thingiverse.com</a> ja <a href="https://www.youmagine.com" target="blank">www.youmagine.com</a>.
    3D-tulostuksessa käytetty tiedostomuoto on STL. Ilmaisia mallinnusohjelmia ovat esimerkiksi SketchUp, Blender sekä helposti lähestyttävä, verkkoselaimessa toimiva Tinkercad.</p>

<a href="https://play.google.com/store/apps/details?id=fi.ellibs.ellibs&hl=fi" target="blank">Play-kaupasta (play.google.com)</a>
    
    <p>Katso esittelyvideo Ultimaker 3:sta!</p>
    <p><iframe class="ultimaker_iframe" width="560" height="315" src="https://www.youtube.com/embed/ScfMl3u-uT8" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <h2>Mediamaja sosiaalisessa mediassa</h2>
    <ul class="list-bullets">
        <li><a href="https://www.youtube.com/channel/UC1IxCRsyLP-pWQduB2JiBUA">Youtube</a></li>
        <li><a href="https://www.facebook.com/Kouvolan-kirjaston-Mediamaja-94652417752">Facebook</a></li>
        <li><a href="https://www.instagram.com/mediamajakouvola/?hl=fi">Instagram</a></li>
    </ul>
    </div>
</div>

<!-- END of: Content/mediamaja_fi.tpl -->