<!-- START of: Content/omatoimikirjastot_fi.phtml -->
<? $this->headTitle('Omatoimikirjastot'); $this->content()->setHeading('Omatoimikirjastot'); ?>

<div class="row">
    <div class="col-sm-12">
        <p><img src="<?=$this->imageSrc('palvelut/omatoimi_banneri.jpg')?>" alt="Nainen naputtelee tunnuslukua automaattiin" /></p>
        <div id="Omatoimikirjastot" class="content-section">
            <h2>Mikä omatoimikirjasto?</h2>
            <p>Omatoimikirjastossa voit käydä kirjaston normaalien aukioloaikojen ulkopuolella. Sisään pääset tunnistautumalla jollakin Kyyti-kirjastojen kirjastokortilla ja 
            samalla nelinumeroisella tunnusluvulla, jota käytetään lainausautomaateilla ja verkkokirjastossa.</p>
            <p>Omatoimiaikana toimit kirjastossa itsenäisesti. Vaikka henkilökuntaa olisi paikalla, he tekevät muita työtehtäviä kuin asiakaspalvelua.</p>
            <p>Omatoimikirjastoissa on tallentava kameravalvonta.</p> 
            
            <h2>Mitä voit tehdä omatoimiaikana</h2>
            <p>Omatoimiaikana voit:</p>
            <ul class="list-bullets">
                <li>Lainata ja palauttaa aineistoa automaateilla ja noutaa varauksesi.</li>
                <li>Opiskella ja lukea kirjaston tiloissa.</li>
                <li>Käyttää tietokoneita.</li>
            </ul>
            <p>Kirjaston tietokoneilla on internet-selaimen lisäksi Microsoftin tekstinkäsittely-, taulukkolaskenta-, kuvankäsittely- ja esitysohjelmat. 
            Voit myös kopioida, tulostaa ja skannata ja käyttää USB-muistitikkuja.</p>
            
            <h2>Aukioloajat</h2>
            <p>Omatoimikirjastojen aukioloajat vaihtelevat toimipisteittäin. <a href="https://kyyti.finna.fi/OrganisationInfo">Tarkasta kirjastosi aukioloajat täältä</a>.</p>
            
            <h2>Omatoimikirjastojen käyttösäännöt</h2>
            <ul class="list-bullets">
                <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_kouvola.pdf')?>">Kouvola (pdf)</a></li>
                <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_kotka.pdf')?>">Kotka (pdf)</a></li>
                <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_hamina.pdf')?>">Hamina (pdf)</a></li>
                <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_iitti.pdf')?>">Iitti (pdf)</a></li>
                <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_pyhtaa.pdf')?>">Pyhtää (pdf)</a></li>
                <li><a target="_blank" href="<?=$this->fileSrc('omatoimikirjaston_kayttosaannot_virolahti.pdf')?>">Virolahti (pdf)</a></li>
            </ul>
        </div>
    </div>
</div>

<!-- END of: Content/omatoimikirjastot_fi.tpl -->