<!-- START of: Content/pelaaminen_kirjastoissa.phtml -->

<? $this->headTitle('Pelaaminen kirjastoissa'); $this->content()->setHeading('Pelaaminen kirjastoissa'); ?>

<div class="row">
    <div class="col-sm-12">
        <h2>Kotkan kirjastot</h2>
        <h3>Pääkirjasto</h3>
        <p>Lasten- ja nuortenosastolla voit pelata Playstation 3 -pelejä ja lautapelejä.</p>
        <h3>Karhulan kirjasto</h3> 
        <p>Karhulan kirjastossa voit pelata Playstation 4-pelejä ja PSVR-virtuaalipelejä sekä lautapelejä.</p>
        <h3>Karhuvuoren kirjasto</h3> 
        <p>Karhuvuoren kirjastossa voit pelata lautapelejä kirjaston tiloissa.</p>
        
        <h3>Kysy lisää pelaamisesta</h3>

        <p>Yhteystiedot</p>
        <ul class="list-bullets">
            <li>Kotkan pääkirjaston lasten- ja nuortenpalvelut: 040 688 3752</li>
            <li>Karhulan kirjasto: 040 688 3587</li>
            <li>Karhuvuoren kirjasto p. 040 158 7338</li>
        </ul>
        
        <h2>Kouvolan kirjastot</h2>
        
        <p>Voit lainata lautapelejä kaikista kirjastoista. Useimmissa kirjastoissa on myös kirjastossa pelattavia pelejä. Lisätietoja saat kirjastoista.</p>
        
        <p>Kouvolan pääkirjaston Mediamajassa pääset pelaamaan lautapelien lisäksi myös konsolipelejä. Pelattavaa löytyy klassikkopeleistä aina uudempiin saakka. 
        Mediamajassa on myös VR-lasit. Kysy lisää niiden käytöstä tai muista peleistä puhelimitse tai sähköpostillla. 
        
        <p>Mediamajan yhteystiedot</p>
        <ul class="list-bullets">
            <li>Puhelimella: 020 615 1333</li>
            <li>Sähköpostilla: mediamaja[at]kouvola.fi</li>
        </ul>

        <h2>Haminan kirjastot</h2>
        
        <p>Pääkirjastossa on valikoima lauta- ja korttipelejä, joita voit pelata kirjaston tiloissa.</p>
        
        <p>Pääkirjaston pelipisteellä voit pelata PlayStation 5 -pelikonsolilla yksin tai kaverin kanssa. Peliajat varataan asiakaspalvelusta.</p>
    </div>
</div>
   
<!-- END of: Content/pelaaminen_kirjastoissa.phtml -->