<? $this->headTitle('Pikkuvarpaat sananjalkapolulla');?>
<div class="pikkuvarpaat">
    <div class="hankelogo">
        <img src="<?=$this->imageSrc('pikkuvarpaat_sananjalkapolulla/pikkuvarpaat_logo.png')?>" alt="Pikkuvarpaat sananjalkapolulla hankelogo" />
    </div>
    <div class="row">
        <?= $this->feed('pikkuvarpaat_sananjalkapolulla'); ?>
    </div>
    <div class="tekstiosio">
        <div class="row">
            <div class="col-lg-6">
                <h3>Lyhyesti</h3>
                <p>
                    Pikkuvarpaat sananjalkapolulla ‑hankkeessa rakennetaan Kymenlaaksoon varhaisvaiheen lukemista edistävä verkosto ja toimivat rakenteet sekä pilotoidaan erilaisia lukemisen edistämisen menetelmiä, joissa erityishuomio on yhteisöllisissä menetelmissä. 
                </p>
                <p>
                    <i>Kun sängyssä lapsia on yksitoista<br>
                    ja hännät on solmittu yhteen,<br>
                    niin myös peikkomummo<br>
                    hän lapsille laulaa<br>
                    näin kaikista kauneimman laulun:<br>
                    huu ai-ai-ai-ai puff,<br>
                    huu ai-ai-ai-ai puff,<br>
                    huu ai-ai-ai-ai puff, puff,<br>
                    huu ai-ai-ai-ai puff.<br></i>
                </p>
                <p>
                    Margit Holmberg<br>
                    Suom. Sauvo Puhtila<br>
                    Sov. Piia Kleimola<br>
                </p>
            </div>
            <div class="col-lg-6">
                <img class="peikkomummo-kuva" src="<?=$this->imageSrc('pikkuvarpaat_sananjalkapolulla/peikkomummo_02')?>" alt="Kuva peikkomummosta lukemassa peikkolapselle kirjaa" />
                <div class="taiteilija"><p>Kuva: Päivi Pöyhölä</p></div>
            </div>
        </div>
    </div>
    <div class="tekstiosio">
        <div class="row">
            <div class="col-lg-6">
                <img class="peikkomummo-kuva" src="<?=$this->imageSrc('pikkuvarpaat_sananjalkapolulla/peikkomummo_01')?>" alt="Kuva peikkomummosta lukemassa peikkolapselle kirjaa" />
                <div class="taiteilija"><p>Kuva: Päivi Pöyhölä</p></div>
            </div>
            <div class="col-lg-6">
                <h3>Hankekoordinaattori</h3>
                <div class="yhteystiedot">
                    <ul>
                        <li>Piia Kleimola</li>
                        <li><a href="tel:+358206159092">020 615 9092</a></li>
                        <li>piia.kleimola@kouvola.fi</li>
                    </ul>
                </div>

                <h3>Hankkeessa mukana</h3>
                <p>Pikkuvarpaat sananjalkapolulla -hanke toteutetaan yhteistyössä Kouvolan kaupunginkirjaston sekä muiden Kymenlaaksolaisten Kyyti-kirjastojen, 
                Kymenlaakson hyvinvointialueen perhekeskusten ja neuvolapalveluiden, kuntien varhaiskasvatusten palveluiden sekä Mannerheimin 
                Lastensuojeluliiton Kaakkois-Suomen piirin sekä muiden mahdollisten toimijoiden kanssa.</p>
                <p>Hanke toteutuu ajalla 1.9.2024 – 31.12.2025.</p>
                <p>Aluehallintovirasto on myöntänyt Kouvolan kaupunginkirjaston Pikkuvarpaat sananjalkapolulla –hankkeelle valtionavustusta 39 000 €.</p>
            
            </div>
        </div>
    </div>
    <div cass="row">
        <?= $this->feed('facebook'); ?>
    </div>
    <div class="Logot ">
        <div class="hankelogot">
            <img src="<?=$this->imageSrc('pikkuvarpaat_sananjalkapolulla/Kouvola_logo_musta.png')?>" alt="Kouvolan kaupungin logo"/>
            <img src="<?=$this->imageSrc('pikkuvarpaat_sananjalkapolulla/2020-02_AVI_logo_rgb_FI.png')?>" alt="Aluehallintoviraston logo"/>
             <img src="<?=$this->imageSrc('pikkuvarpaat_sananjalkapolulla/kymenlaakson_hva_logo.svg')?>" alt="Kymenlaakson hyvinvointialueen logo"/>
        </div>
        
    </footer>

</div>
