<!-- START of: Content/ryhmakaynnit_fi.phtml -->

<? $this->headTitle('Ryhmäkäynnit'); $this->content()->setHeading('Ryhmäkäynnit'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>
    <div class="col-sm-9">
        <img src="<?=$this->imageSrc('palvelut/ryhmakaynnit_banneri.jpg')?>" alt="Kaksi lasta lukee sohvalla kirjoja" />
        <div id="Kouvola" class="content-section">    
            <h2>Kouvola</h2>
            <h3>Ryhmäkäynnin varaaminen</h3>
            <p>Kirjasto tarjoaa erilaisille ryhmille kirjastonkäytön ja tiedonhaun 
            opetusta ja kirjavinkkausta.</p>
            
            <p>Pelkkää lainaus- ja palautuskäyntiä varten ei tarvitse tarvitse varata aikaa, 
            jos tulette kirjastoon normaaleina aukioloaikoina. Muussa tapauksessa ottakaa yhteyttä
            kirjastoon etukäteen.</p>
            
            <h3>Pääkirjaston ohjatut ryhmäkäynnit</h3>
            
            <ul class="list-bullets">
            	<li>Alle kouluikäiset ja luokat 1-6, Anne Patrikainen: <a href="tel:+358206159183">020 615 9183</a></li>
            	<li>Yläkoulu, Outi Harju: <a href="tel:+358206154450">020 615 4450</a></li>
            	<li>Lukio, ammattiopisto ja XAMK, Raija Hasu: <a href="tel:+358206155786">020 615 5786</a></li>
            	<li>Aikuiset, Raija Hasu: <a href="tel:+358206155786">020 615 5786</a></li>
            	<li>Maahanmuuttajat, Outi Kauppala: <a href="tel:+358206155671">020 615 5671</a></li>
            	<li>Työikäiset, <a <a href="<?=$this->url('content-page', ['page' => 'lukemalla_jaksaa'])?>">Lukemalla jaksaa -hanke</a></li>
            </ul>
            
            <p>Neuvonta: <a href="tel:+358206154293">020 615 4293</a>, <a href="mailto:kirjasto@kouvola.fi">kirjasto@kouvola.fi</a></p>
            
            <p>Sähköpostiosoitteet: etunimi.sukunimi@kouvola.fi</p>
            
            <h3>Mediamajan opetustarjonta</h3>
            
            <p>Videotuotanto, äänenkäsittely, mediakasvatus ja sosiaalinen media.</p>
            
            <p>Mediamaja: <a href="tel:+358206151333">020 615 1333</a>, <a href="mailto:mediamaja@kouvola.fi">mediamaja@kouvola.fi</a></p>
            <p><a target="_blank" href="https://mediamajakouvola.blogspot.fi/p/suosittelemme.html"> Mediamajan aukioloajat (Mediamajan blogi)</a></p>
            
            
            <h3>Lähikirjastojen palvelut päiväkodeille ja kouluille</h3>
            
            <h4>Päiväkodit ja alakoulut</h4>
            <p>Päiväkodeille ja alakouluille kirjastonkäytön ja tiedonhaun opetusta antaa lähikirjasto. <a href="https://kyyti.finna.fi/OrganisationInfo/Home">Lähikirjastojen yhteystiedot</a>.</p>
            <p>Ole yhteydessä alueesi kirjavinkkaajaan:</p>
            
            <ul class="list-bullets">
            	<li>Kouvolan pääkirjastossa: Mana Rautiainen: <a href="tel:+358206151262">020 615 1262</a></li>	
            	<li>Haanojan kirjastossa Eeva Erolin: <a href="tel:+358206156433">020 615 6433</a></li>
            	<li>Kuusankosken, Valkealan ja Jaalan kirjastossa Aki Lankinen: <a href="tel:+358206159028">020 615 9028</a></li>
            	<li>Elimäen, Inkeroisten ja Myllykosken kirjastossa Sirpa Salonen: <a href="tel:+358206155784">020 615 5784</a></li>
            	<li>Korian kirjastossa Anne Patrikainen: <a href="tel:+358206159183">020 615 9183</a></li>
            </ul>
            
            <p>Sähköpostiosoitteet: etunimi.sukunimi@kouvola.fi
            <h4>Yläkoulut</h4>
            <p>Yläkouluille kirjastonkäytön ja tiedonhaun opetusta antaa lähikirjasto. Ole yhteydessä lähikirjastoon. <a href="https://kyyti.finna.fi/OrganisationInfo/Home">Lähikirjastojen yhteystiedot</a>.</p>
            
            <p>Ole yhteydessä alueesi kirjavinkkaajaan:</p>
            <ul class="list-bullets">
                <li>Kouvolan pääkirjastossa Outi Harju: <a href="tel:+358206154450">020 615 4450</a></li>
            	<li>Kuusankosken ja Valkealan kirjastossa Annukka Harjula: <a href="tel:+358206159169">020 615 9169</a></li>
                <li>Elimäen, Haanojan, Inkeroisten ja Myllykosken kirjastossa Anne Patrikainen: <a href="tel:+358206159183">020 615 9183</a></li>
            </ul>
            
            <p>Sähköpostiosoitteet: etunimi.sukunimi@kouvola.fi<br />
            <br />
            Tervetuloa ohjatulle kirjastokäynnille!</p>
        </div>
        
        <div id="Kotka" class="content-section"> 
            <h2>Kotka</h2>
            <h3>Ryhmävierailut Kotkassa</h3>
            <p>Kotkassa kirjastonkäytön ja tiedonhaunopastusta sekä kirjaston tilojen ja toiminnan 
            esittelyä annetaan kouluille, päiväkodeille ja muille ryhmille. Kirjaston henkilökunta
            tulee myös pyydettäessä esittelemään kirjastoaineistoa ja kertomaan kirjaston 
            toiminnasta erilaisiin tilaisuuksiin.</p>
            
            <h3>Päiväkodit ja koulut</h3>
            <p>Räätälöimme mielellämme opettajan tai ryhmän toiveiden mukaan opetushetkiä ja
            ryhmäkäyntejä. Varaa aika opetushetkiin ja ryhmäkäynteihin hyvissä ajoin.</p>
            
            <p>Esikoululaisille järjestetään kulttuuripolkuun liittyvä kirjastokäynti. 
            Käynnin aikana saadaan vastaus kysymyksiin: Miten lainataan ja palautetaan? 
            Miten kirjaa käsitellään? Mitä kirjastossa on ja miten kirjastossa käyttäydytään?</p>
            
            <p>Ala- ja yläkoululaisten kirjastonkäyttöön, tiedonhankintaan ja lukuvinkkaukseen liittyvät 
            kirjasto- ja ryhmäkäynnit löydät 
            <a href="https://peda.net/kotka/kkk" target="_blank">Kotkan kaupunginkirjaston Peda.netin sivuilta</a>.</p>
            
            <h3>Aikuisryhmät</h3>
            <p>Erilaisten aikuisryhmien ja opiskeluryhmien on mahdollista tilata aika esim. kirjastokierrokselle, kirjaston palvelujen esittelylle tai tiedonhankinnan opastukseen.</p>
            <p>Pääkirjasto järjestää myös etukäteen varattavia Koe kirjastosi! -ryhmävierailuita torstaisin kello 10.00–11.30. 
            Ryhmävierailu alkaa kirjastopalvelujen esittelyllä ja jatkuu kirjastokierroksella. Vierailun kokonaiskesto on 90 minuuttia ja sen jälkeen on kahvitarjoilu Cafe Sonetissa.
            Ryhmän koko voi olla 5-15 henkeä.</p>

            <h3>Yhteystiedot:</h3>
            
            <ul class="list-bullets">
            	<li>Kotkan pääkirjasto, aikuistenosaston tietopalvelu: <a href="tel:+358403883754 "> 040 388 3754</a></li>
            	<li>Kotkan pääkirjasto, lastenosasto: <a href="tel:+358406883752 "> 040 688 3752</a></li>
            	<li>Kotkan pääkirjasto, Koe kirjastosi! -kierrosten varaukset: <a href="tel:+358400381442"> 040 038 1442</a></li>
            	<li>Karhulan kirjasto: <a href="tel:+358406883587">040 688 3587</a></li>
            	<li>Karhuvuoren kirjasto: <a href="tel:+358401587338">040 158 7338</a></li>
            </ul>
        </div>
        
        <div id="Hamina" class="content-section"> 
            <h2>Hamina</h2>
            <h3>Ryhmävierailut Haminassa</h3>
            <p>Haminan kirjastoissa kirjaston käytön opastusta, kirjaston tilojen ja toimintojen esittelyä, tiedonhaun opastusta ja kirjavinkkausta annetaan esimerkiksi kouluille, päiväkodeille ja muille ryhmille tilauksesta sovittuina aikoina. Luokat ja muut ryhmät ovat tervetulleita lainaamaan kirjastoon myös ennen kirjaston aukeamista etukäteen sovittaessa. Kirjastonhoitajaa voi pyytää myös esittelemään kirjastoaineistoa ja kirjaston toimintaa erilaisiin tilaisuuksiin esimerkiksi kouluihin.</p>
            
            <h3>Yhteydenotot</h3>
            <ul class="list-bullets">
                <li>Pääkirjasto: <a href="tel:+358401991310">040 199 1310</a></li>
                <li>Aikuisten osasto: <a href="tel:+358401991487">040 199 1487</a></li>
                <li>Lasten- ja nuortenosasto: <a href="tel:+358401991255">040 199 1255</a></li>
                <li>Musiikin tiedonhaun opastukset: <a href="tel:+358401991194">040 199 1194</a></li>
                <li>Ruissalon kirjasto: <a href="tel:+358401991322">040 199 1322</a></li>
            </ul>
        </div>
     
        <div id="Iitti" class="content-section"> 
            <h2>Iitti</h2>
            <p>Iitin kunnankirjastossa kirjaston käytön opastusta, kirjaston tilojen ja toimintojen 
            esittelyä, tiedonhaun opastusta ja kirjavinkkausta annetaan esimerkiksi kouluille, 
            päiväkodeille ja ryhmille tilauksesta sovittuina aikoina. Luokat ovat aina tervetulleita 
            lainaamaan kirjastoon aukioloaikoina. Kirjastotäti tulee mielellään esittelemään 
            kirjastoaineistoa ja kirjaston toimintaa erilaisiin tilaisuuksiin.</p>
            
            <p>Yhteydenotot, kirjastonhoitaja: <a href="tel:+358206159732">040 483 3800</a>
            tai sähköpostilla <a href="mailto:kirjasto@iitti.fi">kirjasto@iitti.fi</a>.</p> 
        </div>
    </div>
</div>

<!-- END of: Content/ryhmakaynnit_fi.tpl -->
