<!-- START of: Content/somekanavat_fi.phtml -->

<? $this->headTitle('Kyyti-kirjastot sosiaalisessa mediassa'); $this->content()->setHeading('Löydät meidät myös somesta'); ?>

<div class="col-sm-12">
    <img src="<?=$this->imageSrc('some_banneri.jpg')?>" alt="Facebookin logo" />
    <br>
    <br>
    <h2>Kouvola</h2>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/Kouvolankirjasto" target="blank" style="color:#007091;">Kouvolan kirjastot Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/Kuusankoskenkirjasto" target="blank" style="color:#007091;">Kuusankosken kirjasto Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/Myllykoskenkirjasto" target="blank" style="color:#007091;">Myllykosken kirjasto Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/Kouvolan-kirjaston-Mediamaja-94652417752" target="blank" style="color:#007091;">Mediamaja Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.instagram.com/explore/tags/kouvolankirjastot/?hl=fi" target="blank" style="color:#007091;">Kouvolan kirjastot Instagramissa</a></p>
    <p style="color:#000"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.instagram.com/explore/tags/mediamajakouvola/?hl=fi" target="blank" style="color:#007091;">Mediamaja Instagramissa</a></p>
    <p style="color:#000"><i class="fa fa-youtube fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.youtube.com/user/Kouvolankirjasto/videos" target="blank" style="color:#007091;">Kouvolan kirjastot YouTubessa</a></p>
    <p style="color:#000"><i class="fa fa-youtube fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.youtube.com/user/Mediamaja/videos" target="blank" style="color:#007091;">Mediamaja YouTubessa</a></p>

    <br>
    <h2>Kotka</h2>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/Kotkankaupunginkirjasto" target="blank" style="color:#007091;">Kotkan kirjastot Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.instagram.com/explore/tags/kotkankirjasto/?hl=fi" target="blank" style="color:#007091;">Kotkan kirjastot Instagramissa</a></p>
    <p style="color:#000"><i class="fa fa-youtube fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.youtube.com/user/Kirjastokanava/videos" target="blank" style="color:#007091;">Kotkan kirjastot YouTubessa</a></p>
    <p style="color:#000"><i class="fa fa-link fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://kotka.fi/kirjastot" target="blank" style="color:#007091;">Kotkan kirjastojen kotisivut</a></p>


    <br>
    <h2>Hamina</h2>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/haminankirjastot" target="blank" style="color:#007091;">Haminan kirjastot Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.instagram.com/haminankirjastot/" target="blank" style="color:#007091;">Haminan kirjastot Instagramissa</a></p>

    <br>
    <h2>Iitti</h2>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/iitinkunnankirjasto" target="blank" style="color:#007091;">Iitin kirjasto Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.instagram.com/explore/tags/iitinkirjasto/?hl=fi" target="blank" style="color:#007091;">Iitin kirjasto Instagramissa</a></p>
  
    <br>  
    <h2>Pyhtää</h2>
    <p style="color:#000"><i class="fa fa-facebook-square fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.facebook.com/pyhtaankirjasto" target="blank" style="color:#007091;">Pyhtään kirjasto Facebookissa</a></p>
    <p style="color:#000"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.instagram.com/pyhtaankirjasto" target="blank" style="color:#007091;">Pyhtään kirjasto Instagramissa</a></p>

    <br>
    <h2>Kyyti-kirjastot</h2>
    <p style="color:#000"><i class="fa fa-youtube fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://www.youtube.com/channel/UCInR2giVFpR5f6ya9Z-9Kmw/videos" target="blank" style="color:#007091;">Kyyti-kirjastojen lasten ja nuorten kanava YouTubessa</a></p>

</div>

<!-- END of: Content/somekanavat_fi.tpl -->