<!-- START of: Content/sovellukset_fi.phtml -->
    
<? $this->headTitle('Mobiilikortti puhelimeesi'); $this->content()->setHeading('Näin asennat Kouvola mobiilissa -sovelluksen ja käytät sähköistä kirjastokorttia'); ?>

<div class="row">
    <div class="col-sm-12">
        <ol class="list-numbers">
            <li>Siirry Kouvola mobiilissa -sovelluksen lataussivulle:
                <ul class="list-bullets">
                    <li>Android-laitteilla Googlen <a href="https://play.google.com/store/apps/details?id=fi.hamina.hamina" target="blank">Play-kauppaan (play.google.com)</a> tai</li>
                    <li>Applen laitteilla <a href="https://apps.apple.com/us/app/hamina/id1600544395" target="blank">App Storeen (apps.apple.com)</a></li>
                </ul>
            </li>
            <li>Napauta <strong>Asenna</strong>-painiketta.
            <br>
            <img src="<?=$this->imageSrc('sovellukset/ohje_asenna.jpg')?>" width="300" alt="asennuspainike sovelluskaupassa"><br><br></li>
            <li>Kun sovellus on asentunut, napauta <strong>Avaa</strong>-painiketta.
            <br>
            <img src="<?=$this->imageSrc('sovellukset/ohje_avaa.jpg')?>" width="300" alt="sovelluksen avauspainike sovelluskaupassa">
            <br><br></li>
            <li>Napauta sovelluksessa menu-valikon kuvaketta (kolme viivaa).
            <br>
            <img src="<?=$this->imageSrc('sovellukset/ohje_menuvalikko.jpg')?>" width="300" alt="menu-valikko sovelluksessa"><br><br></li>
            <li>Valitse <strong>Kirjastokortti</strong>.
            <br>
            <img src="<?=$this->imageSrc('sovellukset/ohje_korttipainike.jpg')?>" width="200" alt="kirjastokortti-painike sovelluksessa"><br><br></li>
            <li>Syötä kirjastokortin numero ja korttiin liitetty nelinumeroinen tunnusluku <strong>Kortin numero</strong>- ja <strong>Salasana</strong>-kenttiin ja napauta <strong>Kirjaudu</strong>-painiketta.
            <br>
            <img src="<?=$this->imageSrc('sovellukset/ohje_kirjaudupainike.jpg')?>" width="300" alt="kirjautumispainike sovelluksessa"><br><br></li>
            <li>Kirjastokortti avautuu ruudulle ja voit käyttää sitä kuin normaalia kirjastokorttia.
            <br>
            <img src="<?=$this->imageSrc('sovellukset/ohje_viivakoodi.png')?>" width="300" alt="kirjastokorttinäkymä sovelluksessa"></li>
        </ol>
    </div>
 </div>

<!-- END of: Content/sovellukset_fi.phtml -->