<!-- START of: Content/tapahtumat.fi.phtml -->

<? $this->headTitle(''); $this->content()->setHeading(''); ?>

<!-- Välilehdet -->
<div class="row">
    <div class="col-sm-12">
        <script type='text/javascript' src='https://www.kymenlaaksonyt.fi/widget-loader/66f517ed9ac88141ab5522f4'>
        </script><div id='EVENTZWIDGET-66f517ed9ac88141ab5522f4' class='EVENTZWIDGET'></div>
        
        <?php
        $script = <<<JS
        const searchTerms = new Map([
                    ['Valitse aihe',''],
                    ['Digiopastukset','Digiopastus'],
                    ['Elokuvat','Elokuvat'],
                    ['Kirjailijavieraat','kirjailija'],
                    ['Kirjallisuus','Kirjallisuus'],
                    ['Lukukoirat','lukukoiratt'],
                    ['Lukupiirit','lukupiiiri'],
                    ['Musiikki','Musiikki'],
                    ['Näyttelyt','Näyttelyt'],
                    ['Satutuokiot','satutuokio']
        ]);
                    
        waitForWidgets(searchTerms);
        JS;
        echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
        ?>
    </div>
</div>
<!-- END of: Content/tapahtumat.fi.tpl -->