<? $this->headTitle('Tietosuojaselosteet'); $this->content()->setHeading('Tietosuojaselosteet'); ?>

<div>
    <ul class="list-bullets">
        <li><a href="<?= $this->fileSrc('Informointiasiakirja_kirjasto_Kyyti-kirjastot.pdf')?>" target="_blank">Informointiasiakirja: Kyyti-kirjastot (pdf)</a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'register_details'])?>"><?=$this->transEsc('navigation_register_details');?></a></li>
    </ul>
</div>



    
        
       