<!-- START of: Content/tilat_fi.phtml -->

<? $this->headTitle('Tilat'); $this->content()->setHeading('Tilat'); ?>

<div class="row">
    <div class="col-sm-3 sidebar">
        <div class="content-navigation-menu"></div>
    </div>

    <div class="col-sm-9">
        <img src="<?=$this->imageSrc('palvelut/tilat_banneri.jpg')?>" alt="Kirjaston oleilunurkkaus, jossa punainen kulmasohva, pöytä ja kirjahyllyjä" />
        <div id="Kouvola" class="content-section">
            <h2>Kouvola</h2>
            <p>Voit tutustua Kouvolan kirjastojen tiloihin ja varata tiloja Varaamo-palvelussa.</p>
            <p><a href="https://varaamo.kouvola.fi/" target="_blank">Siirry Varaamoon (varaamo.kouvola.fi)</a></p>
        </div>

        <div id="Kotka" class="content-section">
            <h2>Kotka</h2>
            <h3>Tilojen varaaminen ja käyttö</h3>
            
            <p>Kirjastolla on useita erikokoisia varattavia tiloja. Tilojen varaaminen on auditoriota lukuun ottamatta maksutonta. Tiloja ei saa käyttää yritysten kaupalliseen toimintaan.</p>
 
            <p>Voit varata pääkirjaston tiloja joko
            <ul class="list-bullets">
                <li>tietopalvelusta: <a href="mailto:kirjasto@kotka.fi">kirjasto@kotka.fi</a> / <a href="tel:+358406883754">040 688 3754</a> tai</li>
                <li>vahtimestareilta: <a href="tel:+358400209674">040 020 9674</a>.</li>
                <li>Auditorion varaushakemukset tehdään Kotkan kaupungin Timmi-tilavarausohjelman kautta: <a href="https://www.kotka.fi/asioi-ja-osallistu/tilavaraus/timmi-tilavarausjarjestelman-ohjeet/" target "blank">Linkki tilavarausjärjestelmään</a> </li>
            </ul>
            <p>Karhulan kirjaston tiloja voit varata sähköpostilla: <a href="mailto:karhula.kirjasto@kotka.fi">karhula.kirjasto@kotka.fi</a> tai
            puhelimella: <a href="tel:+358406883587">040 688 3587</a>.</p>
            
            <p>Kerro varatessa laitetarpeesi. Eri tilojen laitteet on lueteltu tilojen kuvauksissa. 
            Lisäksi asiakaspalvelusta voi lainata kannettavan tietokoneen kirjastokortilla.</p>
            
            <p>Kirjastossa on langaton verkko: </p>
            <ul class="list-bullets">
                <li>verkon nimi: Kirjasto-vierailija</li>
                <li>salasana: kirjasto</li>
            </ul>
            
            <p>Kahvilapalveluja tarjoaa Café Sonetti: p. <a href="tel:+358449851556">044 985 1556</a>, <a href="mailto:makuharmonia@gmail.com">makuharmonia@gmail.com</a>.</p>
            
            <p>Kunkin tilan varaustilanteen näet napauttamalla tilan tiedoissa "Tilan varauskalenteri"-painiketta. Kalenterista ei voi varata tiloja.</p>

            <br>
            <h3 id="Paakirjasto">Pääkirjaston tilat</h3>
                        <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_auditorio_kuva_2_2024.jpg')?>" alt="Auditorio" />
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Auditorio"></a>Auditorio</h4>
                    <p style="color:#000">Iso tila yleisötilaisuuksille</p>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000" title="henkilömäärä"></i> 266 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> kannettavatietokone, dataprojektori, äänentoisto, 4 langallista mikrofonia, 2 langatonta mikrofonia + yksi headset, dokumenttikamera, internetyhteys, vierailijaverkko, flyygeli, fläppitaulu</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-regular fa-credit-card" aria-hidden="true" style="color:#000"></i> maksullinen, <a href="https://kyyti.finna.fi/Content/maksut-kotka#tilat">katso varaushinnat tästä</a></p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 1.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/1_kerros.png')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5936&adminAreaId=3"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            
                        <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_katariinan_kammari_2_2024.jpg')?>" alt="Katariinan kammari" />
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Katariinan-kammari"></a>Katariinan kammari</h4>
                    <p style="color:#000">Olohuonemainen kokoontumistila</p>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000" title="henkilömäärä"></i> 30 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> tietokone, televisio, esityslaitteet</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 3.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/3_kerros_2024.jpg')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5927&adminAreaId=3" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_uusittumediatila_2_2024.jpg')?>" alt="mediatila" />
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Mediatila"></a>Mediatila</h4>
                    <p style="color:#000">Monitoimitila tilaisuuksille</p> 
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 40 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> tietokone, esityslaitteet, DVD-/Blu-ray-soitin, fläppitaulu</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> Varattavissa kirjaston aukioloaikoina. Tiistaisin varattu kirjaston omaan käyttöön.</p>
                   <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 3.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/3_kerros_2024.jpg')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5928&adminAreaId=3" target="blank" style="color:#007091;">Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_hildan_huone_2_2024.jpg')?>" alt="Hildan huone" />
                </div>
            
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Hildan-huone"></a>Hildan huone</h4>
                    <p style="color:#000">Kokoushuone</p>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 12 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> tietokone, esityslaitteet</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 1.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/1_kerros.png')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5921&adminAreaId=3" target="blank" style="color:#007091;">Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            <div class="row infobox">
            <div class="col-sm-12 col-md-6 col-lg-6">
            <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_stage_2.jpg')?>" alt="Stage-esiintymislava" />
            </div>
            
            <div class="col-sm-12 col-md-6 col-lg-6">
            <h4 style="color:#000"><a id="Stage"></a>Stage</h4>
            <p style="color:#000">Esiintymislava</p>
            <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 90 henkilöä</p>
            <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> tietokone, esityslaitteet, piano</p>
            <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
            <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 2.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/2_kerros_2024.png')?>" target="blank">kartta</a>)</p>
            <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5925&adminAreaId=3" target="blank" style="color:#007091;">Varauskalenteri (vain selaus)</a></p>
            </div>
            </div>
            
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img src="<?=$this->imageSrc('tilat/kotka_tilat_ryhmatyotila_2_2024.jpg')?>" alt="Ryhmätyötila" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Ryhmätyötilat"></a>Ryhmätyötilat</h4>
                    <p style="color:#000">Kolme pientä ryhmätyötilaa</p>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 4 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-info-circle fa-lg" aria-hidden="true" style="color:#000"></i> Voit varata tilan korkeintaan viikoksi kerrallaan. Jos et nouda ryhmätyötilan avainta tunnin kuluessa varauksen alkamisesta, tila voidaan luovuttaa toiselle asiakkaalle.</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 3.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/3_kerros_2024.jpg')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5932&adminAreaId=3" target="blank" style="color:#007091;">1. ryhmätyötilan varauskalenteri (vain selaus)</a></p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5930&adminAreaId=3" target="blank" style="color:#007091;">2. ryhmätyötilan varauskalenteri (vain selaus)</a></p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5920&adminAreaId=3" target="blank" style="color:#007091;">3. ryhmätyötilan varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img src="<?=$this->imageSrc('tilat/kotka_tilat_tutkijanhuone_2_2024.jpg')?>" alt="Tutkijanhuone" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Tutkijanhuone"></a>Tutkijanhuone</h4>
                    <p style="color:#000">Pidemmäksi aikaa varattava työhuone</p>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 1 henkilö</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> kaapisto, verkkoliitäntä</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-info-circle fa-lg" aria-hidden="true" style="color:#000"></i> Voit varata tilan korkeintaan kolmeksi kuukaudeksi kerrallaan.</p>
                   <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 3.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/3_kerros_2024.jpg')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5931&adminAreaId=3" target="blank" style="color:#007091;">Varauskalenteri (vain selaus)</a></p>
                    <!-- <p><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#007091;"></i> <a href="https://webtimmi.kotka.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5750&adminAreaId=3" target="blank" style="color:#007091;">2. tutkijanhuoneen varauskalenteri (vain selaus)</a></p> -->
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_näyttelytila_2.jpg')?>" alt="Näyttelytila" />
                </div>
                    
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Näyttelytilat"></a>Näyttelytilat</h4>
                    <p style="color:#000">Kirjastossa on kaksi näyttelytilaa ala-aulassa ja 2. kerroksessa.</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-info-circle fa-lg" aria-hidden="true" style="color:#000;"></i> Ala-aulan näyttelytilan varauksia hoitaa kirjastonhoitaja Jaana Elsilä, p. <a href="tel:+358408454280">040 845 4280</a>, sähköposti <a href="mailto:jaana.elsila@kotka.fi">jaana.elsila@kotka.fi</a>.</p>
                    <p style="color:#000"><i class="fa fa-info-circle fa-lg" aria-hidden="true" style="color:#000;"></i> 2. kerroksen näyttelytilan voit varata tietopalvelusta: <a href="mailto:kirjasto@kotka.fi">kirjasto@kotka.fi</a>, p. <a href="tel:+358406883754">040 688 3754</a>.</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 1.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/1_kerros.png')?>" target="blank">kartta</a>)</p>
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_3D_ja_digitointi_2_2024.jpg')?>" alt="3D-tulostus/digitointi" />
                </div>
                    
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="3D-tulostus/digitointi"></a>3D-tulostus/digitointi</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 1 henkilö</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> Prenta Duo XL SE -tulostin 2kpl, Simplify3D-viipalointiohjelma, LG-videonauhuri, Adobe Premiere Pro CC -videoeditointiohjelma, Epson Perfection V500 Photo -tasoskanneri, Photoshop Elements 12 -kuvankäsittelyohjelma, Reflecta-kaitafilmiskanneri (Super 8 ja Normal 8)</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 3.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/3_kerros_2024.jpg')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-info-circle fa-lg" aria-hidden="true" style="color:#000;"></i> 3D-tulostamiseen ja digitointiin voit varata opastuksen kirjaston tietopalvelusta <a href="mailto:kirjasto@kotka.fi">kirjasto@kotka.fi</a>, p. <a href="tel:+358406883754">040 688 3754</a>.</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=88919&adminAreaId=3" target="blank" style="color:#007091;">Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_aanistudio_2_2024.jpg')?>" alt="Studio" />
                </div>
                
                    
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Studio"></a>Studio</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 4 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> <a href="https://bit.ly/3tGzbVV" target="blank" style="color:#007091;"> Laite- ja ohjelmistolista (Google Docs)</a> </p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pääkirjasto, 3.kerros (<a href="<?= $this->imageSrc('pohjapiirrokset/3_kerros_2024.jpg')?>" target="blank">kartta</a>)</p>
                    <p style="color:#000"><i class="fa fa-info-circle fa-lg" aria-hidden="true" style="color:#000;"></i> Studio on yli 15-vuotiaiden asiakkaiden käytettävissä maksutta kirjaston aukioloaikoina ja sitä voi varata neljäksi tunniksi kerrallaan. Studiossa voit soittaa, äänittää ja harjoitella omaa instrumenttiasi, käyttää kirjaston soittimia tai äänittää vaikka podcastia.
                    <br><br>
                    Sinun ei tarvitse olla musiikin ammattilainen tai huippuosaaja käyttääksesi äänitysstudiota. Studio-opastaja on paikalla varauksen alkaessa ja auttaa tarvittaessa 
                    studion käytössä.
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5926&adminAreaId=3" target="blank" style="color:#007091;">Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            <br>
            <h3 id="Karhula">Karhulan kirjaston tilat</h3>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_riihi_2.jpg')?>" alt="riihi" />
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Riihi"></a>Riihi</h4>
                    <p style="color:#000">Kokoushuone</p>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 12 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> televisio, fläppitaulu</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> Karhulan kirjasto</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://kotka.timmi.fi/WebTimmi/login.do?loginName=GUEST&password=NO&roomId=5982&adminAreaId=3" target="blank" style="color:#007091;">Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <img class="marginauto" src="<?=$this->imageSrc('tilat/kotka_tilat_näyttelytila_karhula_2.jpg')?>" alt="Karhulan näyttelytila" />
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Näyttelytila-Raami"></a>Näyttelytila Raami</h4>
                    <p style="color:#000">Näyttelytilan voit varata puhelimella <a href="tel:+358405596827">040 559 6827</a> tai sähköpostilla <a href="mailto:anne.vilska@kotka.fi">anne.vilska@kotka.fi</a>.</p>
                </div>
            </div>
        </div>

        <br>
        <div id="Hamina" class="content-section">
            <h2>Hamina</h2>
            <h3>Tilojen käyttäminen</h3>
            <p>Kirjaston tilojen käyttäminen on ilmaista lukuun ottamatta Kasper-salin ja Aladin-työtilan varaamista. Varaushinnat voit tarkistaa
            <a href="https://kyyti.finna.fi/Content/maksut-hamina#tilat">hinnastosta</a>. Myös Aladin-työtilaa voi käyttää ilmaiseksi silloin, kun 
            se ei ole varattu. Maksuttomia tiloja ei saa käyttää yritysten kaupalliseen toimintaan.</p>
            <p>Yhteystiedot:</p>
            <ul class="list-bullets">
                <li>Pääkirjasto: <a href="mailto:kirjasto@hamina.fi">kirjasto@hamina.fi</a> / <a href="tel:+358401991310">040 199 1310</a></li>
                <li>Ruissalon kirjasto: <a href="mailto:ruissalo.kirjasto@hamina.fi">ruissalo.kirjasto@hamina.fi</a> / <a href="tel:+358401991322">040 199 1322</a></li>
            </ul>
            <p>Ruissalon kirjasto sijaitsee Vehkalahtitalossa, jossa ovat myös Vehkalahtisali ja kerhohuone. Voit varata näitä tiloja Vehkalahden koulun kautta.</p> 
            <p><a href="https://www.hamina.fi/peruskoulut/vehkalahden-koulu/vehkalahtitalo/" target="_blank">Siirry Vehkalahtitalon sivulle (hamina.fi)</a></p>
            <p>Kerro varausta tehdessä, mitä laitteita tarvitset. Eri tilojen laitteet on lueteltu tilojen kuvauksissa.</p>
            <p>Kirjastossa on langaton verkko: </p>
            <ul class="list-bullets">
                <li>verkon nimi: Kirjasto-vierailija</li>
                <li>salasana: kirjasto</li>
            </ul>
            <p>Jos et nouda ryhmätyötilojen tai työhuoneiden (Ester, Elli, Hugo, Helvi) avaimia vartin kuluessa varauksen alkamisesta, tila voidaan luovuttaa toiselle asiakkaalle.</p>
            
            <h3>Haminan pääkirjasto</h3>
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_kasper.jpg')?>" alt="Kasper-sali" />
                    </div>
                </div>
            
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000" id="Kasper-sali">Kasper-sali</h4>
                    <p style="color:#000">Maksullinen monitoimitila tilaisuuksille</p>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 80 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> kannettava tietokone, esityslaitteet, mikrofoni, DVD-/Blu-ray-soitin, fläppitaulu, piano</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa myös kirjaston aukioloaikojen ulkopuolella</p>
                    <p style="color:#000"><i class="fa fa-regular fa-credit-card" aria-hidden="true" style="color:#000"></i> maksullinen, <a href="https://kyyti.finna.fi/Content/maksut-hamina#tilat">katso varaushinnat tästä</a></p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> 1. kerros, sisäänkäynti pääovesta</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://asp3.timmi.fi/WebTimmi/login.do?loginName=GUEST_HAMINA&password=NO&roomId=513021&adminAreaId=2591" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>

            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_aladin.jpg')?>" alt="Hiljainen työtila" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="aladin"></a>Hiljainen työtila Aladin</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 20 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> kannettava tietokone, esityslaitteet, mikrofoni</p>  
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> avoinna kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-regular fa-credit-card" aria-hidden="true" style="color:#000"></i> Vapaasti käytettävissä. Varaaminen tilaisuuksiin maksullista. <a href="https://kyyti.finna.fi/Content/maksut-hamina#tilat">Katso varaushinnat tästä.</a></p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> 1. kerros</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://asp3.timmi.fi/WebTimmi/login.do?loginName=GUEST_HAMINA&password=NO&roomId=1065486&adminAreaId=2591" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>

            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_esteri.jpg')?>" alt="Ryhmätyötila" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Tyotila"></a>Ryhmätyötila Ester</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 4 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> PlayStation 5 -pelikonsoli, televisio</p>  
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> Vapaasti käytettävissä kirjaston aukioloaikoina. Jos haluat varmistaa ajan, voit varata tilan etukäteen kahdeksi tunniksi kerrallaan. Pelipiste varataan kirjaston asiakaspalvelusta, eikä sitä voi varata ennakkoon.</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> 1. kerros</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://asp3.timmi.fi/WebTimmi/login.do?loginName=GUEST_HAMINA&password=NO&roomId=1065482&adminAreaId=2591" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_elli.jpg')?>" alt="Työpiste" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Rauhallinen_tyotila"></a>Rauhallinen työpiste Elli</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 1 henkilö</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> Vapaasti käytettävissä kirjaston aukioloaikoina. Jos haluat varmistaa ajan, voit varata tilan kahdeksi tunniksi kerrallaan.</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> 1. kerros</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://asp3.timmi.fi/WebTimmi/login.do?loginName=GUEST_HAMINA&password=NO&roomId=1065483&adminAreaId=2591" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>            

            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_hugo.jpg')?>" alt="Työhuoneet" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Työhuoneet"></a>Työhuone Hugo</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 1 henkilö</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa päiväksi kerrallaan kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pohjakerros</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://asp3.timmi.fi/WebTimmi/login.do?loginName=GUEST_HAMINA&password=NO&roomId=1065484&adminAreaId=2591" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>

            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_helvi.jpg')?>" alt="Työhuoneet" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Työhuoneet"></a>Työhuone Helvi</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 1 henkilö</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa neljäksi tunniksi kerrallaan kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pohjakerros</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://asp3.timmi.fi/WebTimmi/login.do?loginName=GUEST_HAMINA&password=NO&roomId=1065485&adminAreaId=2591" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>

            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_pelle.jpg')?>" alt="Soittohuone" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Soittohuone"></a>Soittohuone Pelle</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 6 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> sähköpiano, sähkörummut, mikrofoni, kaksi sähkökitaraa, neljä ukulelea</p>  
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjastokortilla asiakaspalvelusta kirjaston aukioloaikoina </p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> pohjakerros</p>
                    <p style="color:#000"><i class="fa fa-info-circle fa-lg" aria-hidden="true" style="color:#000"></i> Voit soittaa myös omia soittimia. Tila on äänieristetty.</p> 
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> <a href="https://asp3.timmi.fi/WebTimmi/login.do?loginName=GUEST_HAMINA&password=NO&roomId=1065117&adminAreaId=2591" target="blank" style="color:#007091;"> Varauskalenteri (vain selaus)</a></p>
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto"src="<?=$this->imageSrc('tilat/hamina_tilat_kirjastogalleria.jpg')?>" alt="Kirjastogalleria" />
                    </div>
            </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Kirjastogalleria"></a>Kirjastogalleria</h4>
                    <p style="color:#000">170 neliömetrin näyttelytila</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> Näyttelytilan voit varata kulttuurituottajalta joko puhelimella <a href="tel:+358407223687">040 722 3687</a> tai sähköpostilla <a href="mailto:henni.kiri@hamina.fi">henni.kiri@hamina.fi</a>.</p>
                </div>
            </div>

            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_kotiseutukokoelma.jpg')?>" alt="Kotiseutukokoelmahuone" />
                    </div>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Kotiseutuhuone"></a>Kotiseutuhuone</h4>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> CD-soitin, mikrofilmiskanneri, tulostin</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> avoinna kirjaston aukioloaikoina</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> 1. kerros</p>
                </div>
            </div>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_lasilinnut.jpg')?>" alt="Oiva Toikka Lasilinnut" />
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="lasilintukokoelma"></a>Oiva Toikan lasilintukokoelma</h4>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> avoinna kirjaston aukioloaikoina, kun Kasper-salia ei ole varattu muihin tilaisuuksiin.</p>
                    <p style="color:#000"><i class="fa fa-location-arrow fa-lg" aria-hidden="true" style="color:#000"></i> 1. kerros, Kasper-sali</p>
                </div>  
            </div>

            <h3>Ruissalon kirjasto</h3>
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img class="marginauto" src="<?=$this->imageSrc('tilat/hamina_tilat_ryhmatyohuone.jpg')?>" alt="Ryhmätyöhuone" />
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Ryhmätyötila"></a>Ryhmätyötila</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 6 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> fläppitaulu, ompelukone</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> varattavissa kirjaston henkilökunnan ollessa paikalla</p>
                </div>  
            </div>
        </div>
        
        <div id="Iitti" class="content-section">
            <h2>Iitti</h2>
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img src="<?=$this->imageSrc('tilat/iitti_tilat_kirmo.jpg')?>" alt="Monitoimitila Kirmo" />
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="kirmo"></a>Monitoimitila Kirmo</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 20 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> Näyttelytilan voi varata 1 kuukaudeksi kerrallaan. Kokouskäyttöön tilaa ei voi varata omatoimiajaksi, mutta jos tila on vapaa, se on käytettävissä (videotykki ei).</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> videotykki ja valkokangas</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> Varaukset: <a href="tel:+358404833800"> 040 483 3800</a> / <a href="mailto:kirjasto@iitti.fi">kirjasto@iitti.fi</a></p>
                </div>  
            </div>            
            
            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img src="<?=$this->imageSrc('tilat/iitti_tilat_pelihuone.jpg')?>" alt="Pelihuone" />
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="pelihuone"></a>Pelihuone</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 4 henkilöä</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> Varataan enintään tunniksi kerrallaan. Samoille pelaajille varataan korkeintaan kaksi pelivuoroa päivässä. Jokaisella pelaajalla pitää olla mukana kirjastokortti, joka jää pelaamisen ajaksi pantiksi.</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> PS4-pelikonsoli</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> Varaukset: <a href="tel:+358404833800"> 040 483 3800</a> / <a href="mailto:kirjasto@iitti.fi">kirjasto@iitti.fi</a></p>
                </div>  
            </div>            

            <div class="row infobox">
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <div class="verticalcenter">    
                        <img src="<?=$this->imageSrc('tilat/iitti_tilat_tutkijanhuone.jpg')?>" alt="Tutkijanhuone" />
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6">
                    <h4 style="color:#000"><a id="Tutkijanhuone_iitti"></a>Tutkijanhuone</h4>
                    <p style="color:#000"><i class="fa fa-user-circle fa-lg" aria-hidden="true" style="color:#000"></i> 1 henkilö</p>
                    <p style="color:#000"><i class="fa fa-clock-o fa-lg" aria-hidden="true" style="color:#000"></i> käytettävissä kirjaston aukioloaikoina (ovi lukossa)</p>
                    <p style="color:#000"><i class="fa fa-laptop fa-lg" aria-hidden="true" style="color:#000"></i> mikrofilminlukulaite</p>
                    <p style="color:#000"><i class="fa fa-calendar fa-lg" aria-hidden="true" style="color:#000;"></i> Varaukset: <a href="tel:+358404833800"> 040 483 3800</a> / <a href="mailto:kirjasto@iitti.fi">kirjasto@iitti.fi</a></p>
                </div>  
            </div>
        </div>
    
        <div id="Virolahti" class="content-section">
            <h2>Virolahti</h2>
            <h3>Kokoustila</h3>
            
            <p>Virolahden kirjastossa on kokoustila, jota asiakkaat voivat varata pieniin tilaisuuksiin, kokoontumisiin tai työskentelytilaksi kirjaston aukioloaikana. 
            Tilan käyttö on maksutonta. Kirjastolta voi lainata tilaisuuksiin videotykin, dokumenttikameran, kaiuttimet ja valkokankaan. 
            Tilan varaukset: p. <a href="tel:+358407107352">040 710 7352</a> tai <a href="mailto:kirjasto.virolahti@virolahti.fi">kirjasto.virolahti@virolahti.fi</a>. </p>
            
            <h3>Näyttelytila</h3>
            
            <p>Virolahden kirjastossa on näyttelytila, jonka voi varata kuukaudeksi kerrallaan. 
            Tiedustelut ja varaukset: p. <a href="tel:+358407107352">040 710 7352</a> tai <a href="mailto:kirjasto.virolahti@virolahti.fi">kirjasto.virolahti@virolahti.fi</a>.</p>
        </div> 
    </div>
</div>

<!-- END of: Content/tilat_fi.tpl -->